omniosorg/omnios-build

build/p7zip/patches/CVE-2016-9296.patch, build/p7zip/patches/series
This adds a patch for CVE 2016-9296 to p7zip. The same patch is already present in OI.
=> p7zip: Add patch for CVE 2016-9296

build/openssl/build.sh
No security changes in this version but keeping openssl up-to-date in stable makes this a good candidate for backporting.
=> openssl: update to 1.0.2l

build/kayak-kernel/build.sh
Building the `kayak-kernel` package has a number of pre-requisites.
* The build must be performed in the global zone;
* The build must be done by root or a by a user with non-password `sudo` rights.
This change allows setting the SKIP_KAYAK_KERNEL environment variable (possibly in `site.sh`) to skip attempting to build this package which is useful if performing test builds in a zone.
=> Allow skipping the kayak-kernel package build

build/g11n/build.sh, build/gcc44/build.sh, build/illumos/build.sh, build/kayak-kernel/build.sh, build/kayak/build.sh, build/pci.ids/build.sh, build/perl/build.sh, build/pkg/build.sh, build/studio/sunstudio12.1.p5m, lib/config.sh, lib/functions.sh
This PR swaps in new omniosce code repositories for places where code is currently pulled directly from OmniTI servers or their Github area.
It also updates the default for package publishers
=> Replace references to OmniTI code repositories

build/gcc51/build-libgmp.sh
See https://github.com/omniosorg/omnios-build/issues/10
pkglint fails for this package due to a duplicate dependency. This is a workaround for now but I'll leave the issue open to try and fix the underlying cause.
=> Skip pkglint for gcc51/gmp

build/omnios-build-tools/omnios-build-tools.p5m, tools/omnios-build-deps.sh
This PR adds a new meta package, similar to `illumos-tools`, that makes it easy to install of the dependencies required for building `omnios-build`.
=> Omnios build tools

build/buildctl
At present, running an entire OmniOS build via `buildctl build all` builds the packages in effectively a random order as it iterates the keys in an associative bash array.
This PR changes that so that builds are done in alphabetical order and also adds extra output showing which package number is being built alongside the total:
```
***********
*********** (17/199) Building developer/gcc44
***********
===== Build started at Sat Jul  8 08:20:45 UTC 2017 =====
Package name: developer/gcc44
Selected flavor: None (use -f to specify a flavor)
```
=> Build in deterministic order and show more progress information

lib/config.sh
The current method for retrieving the version of the installed libffi package fails if omnios is not the first publisher in the list since there's an extra column in the output showing the publisher name.
```
bloody% pkg publisher
PUBLISHER                   TYPE     STATUS P LOCATION
citrus                      origin   online F https://ips.example.com/
omnios                      origin   online F https://pkg.omniti.com/omnios/bloody/
bloody% pkg list libffi
NAME (PUBLISHER)                                  VERSION                    IFO
library/libffi (omnios)                           3.2.1-0.151023             i--
```
The updated method works regardless:
```
bloody% pkg list -H libffi | awk '{print $(NF-1)}' | cut -d- -f1
3.2.1
```
=> Use better method for libffi version retrieval

lib/config.sh
Backport https://github.com/omniosorg/omnios-build/pull/22 to r151022
=> Use better method for libffi version retrieval (backport to r151022)

build/omnios-build-tools/omnios-build-tools.p5m
This is an update to the `omnios-build-tools` package to add some more dependencies for building `omnios-build` and to fix one line which had conflated openssl and ca-bundle
=> Add some missing dependencies and fix line which had run-together

build/zlib/build.sh
Temporarily disable lint for `library/zlib` pending proper fix.
See: https://github.com/omniosorg/omnios-build/issues/46
=> Disable lint for library/zlib

.gitignore, build/buildctl
This is a set of changes to `buildctl` to reduce the time needed to iteratively build OmniOS in the event that parts of the build fail and require fixing.
It adds some new options to the `buildctl` command:
```
./buildctl
...
build continue            (continue interrupted build)
build from <pkg>          (build <pkg> then those after)
```
and also will prompt if a full build is started when there is a cache file left over from a previous build, if not in batch mode.
Example, starting a full build and interrupting it after the first package has built.
```
% ./buildctl build all
***********
*********** (1/200) Building archiver/gnu-tar
***********
===== Build started at Thu Jul 13 10:56:32 UTC 2017 =====
--- Published archiver/gnu-tar@1.29,5.11-0.151023
Done.
***********
*********** …
```
=> Add options for resuming builds after fixing problems

build/pkg/build.sh
Following a build of the `package/pkg`  server, the repository is left with a package under the `pkg5-localizable` publisher which is not used in OmniOS but needs removing before the resulting repository can be published.
```
build:omnios-build:master% pkgrepo -s ../../_repo info
PUBLISHER        PACKAGES STATUS           UPDATED
pkg5-localizable 1        online           2017-07-13T09:25:49.100952Z
omnios           6        online           2017-07-13T09:25:55.340845Z
```
This change removes the publisher as a cleanup step at the end of the `package/pkg` build.
There's also a small change to one of the touch commands so that an error message is not produced if no files are found.
=> pkg: Clean up pkg5-localizable publisher

build/zlib/build.sh
Temporarily disable lint for library/zlib pending proper fix.
See: #46
=> Disable lint for library/zlib (r151022 branch)

build/git/build.sh
Straightforward upgrade to git 2.13.3
Ref: https://github.com/omniosorg/omnios-build/issues/34
```
bloody# git --version
git version 2.13.3
```
Moved to .xz version of man-pages too.
=> git: update to 2.13.3

build/entire/entire.p5m, build/jeos/omnios-userland.p5m, build/screen/build.sh, build/screen/patches/xnet-hack.patch
Closes issue https://github.com/omniosorg/omnios-build/issues/26
```
bloody% screen --version
Screen version 4.06.01 (GNU) 10-Jul-17
```
=> screen: update to 4.6.1

build/openjdk/build.sh
change openjdk build to use ooce build dependencies:
https://github.com/omniosorg/omnios-extra/pull/8
https://github.com/omniosorg/omnios-extra/pull/7
future potential: https://github.com/omniosorg/omnios-build/issues/6#issuecomment-313701726
=> make openjdk ooce aware

build/iso-codes/build.sh
change iso-codes build to use ooce build dependencies:
https://github.com/omniosorg/omnios-extra/pull/9
=> make iso-codes ooce aware

build/entire/entire.p5m, build/grep/build.sh, build/jeos/omnios-userland.p5m
```shell
hadfl@mars:~$ ggrep -V
ggrep (GNU grep) 3.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Mike Haertel and others, see <http://git.sv.gnu.org/cgit/grep.git/tree/AUTHORS>.
```
=> gnu-grep: update to ggrep 3.1

build/diffutils/build.sh, build/entire/entire.p5m, build/jeos/omnios-userland.p5m
```
hadfl@mars:~$ gdiff -v
diff (GNU diffutils) 3.6
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Paul Eggert, Mike Haertel, David Hayes,
Richard Stallman, and Len Tower.
```
=> gnu-diffutils: update to 3.6

build/mercurial/build.sh
```
Mercurial Distributed SCM (version 4.2.2)
```
`hg clone` for `openjdk` source fetch successful.
=> mercurial: update to 4.2.2

build/git/build.sh, build/git/testsuite.log, lib/functions.sh
Some packages that we build have a built-in test suite (e.g. git).
This PR adds a small framework for running that test suite so that we can record changes in test results as part of each PR.
As an example, I've enabled this for the `git` package and included that in this PR.
I manually compared the test results with the previous version of git (2.13.0) and the same test failed before and after.
We should enable this for each package that supports it as we upgrade them.
=> Add testsuite framework and enable for git

build/pciutils/build.sh, build/pciutils/local.mog, doc/packages.md
Update pciutils to version 3.5.5 and drop the `update-pciids` utility and man page from the package since the PCI IDs themselves are delivered by the `system/pciutils/pci.ids` package and the `update-pciids` utility doesn't work anyway.
=> pciutils: update to 3.5.5

build/dbus/build.sh, build/dbus/testsuite.log, build/jeos/omnios-userland.p5m, doc/packages.md
Straightforward upgrade of the dbus package.
(NB: This adds a testsuite run which depends on the merge of https://github.com/omniosorg/omnios-build/pull/83)
=> dbus: update to 1.11.14

build/zlib/build.sh, build/zlib/local.mog, build/zlib/testsuite.log
The `/lib/64` symlink is delivered by both `system/library` and `library/zlib` causing a conflict that is detected by the pkglint process.
```
reaper% pkg contents -m system/library | grep path=lib/64\
link path=lib/64 target=amd64
reaper% pkg contents -m library/zlib | grep path=lib/64\
link path=lib/64 target=amd64
```
...
```
ERROR pkglint.dupaction010.2      path lib/64 has missing mediator attributes across actions in pkg://omnios/system/library@0.5.11,5.11-0.151023:20170713T011155Z pkg:/library/zlib@1.2.11,5.11-0.151023
```
This change removes the link from the `library/zlib` package and re-enables lint for this package.
Since library/zlib depends on system/zlib, nothing is lost.
Also, as there is a test suite for zlib, this is enabled.
=> zlib: Fix pkglint (and add testsuite)

build/automake/build.sh, build/automake/testsuite.log, doc/packages.md
```shell
hadfl@mars:~$ automake --version
automake (GNU automake) 1.15.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Tom Tromey <tromey@redhat.com>
and Alexandre Duret-Lutz <adl@gnu.org>.
```
test-suite diff from 1.15:
```diff
============================================================================
-Testsuite summary for GNU Automake 1.15
+Testsuite summary for GNU Automake 1.15.1
============================================================================
-# TOTAL: 2573
-# PASS:  2371
-# SKIP:  123
+# TOTAL: 2575
+# PASS:  2386
+# SKIP:  125
-# FAIL:  25
+# FAIL:  12 …
```
=> automake: update to 1.15.1

build/gcc51/build-libgmp.sh, build/gcc51/libgmp-final.mog, lib/functions.sh
Fix the last remaining pkglint problem in the build.
Extends the package creation framework to accept an additional `.mog` file that is applied after package dependencies have been determined.
Fixes https://github.com/omniosorg/omnios-build/issues/10
=> libgmp-gcc51: Resolve duplicate dependency

build/gzip/build.sh, build/gzip/local.mog
Here's one that took a lot less time to fix than diagnose!
gzip delivers a binary called `uncompress` which is a hard link to `gunzip`. However, `uncompress` is also delivered by `system/extended-system-utilities` so there is a conflict.
Sometimes the gzip package manifest is generated so that it looks like:
```
file usr/bin/gunzip group=bin mode=0755 owner=root path=usr/bin/gunzip
hardlink path=usr/bin/uncompress target=gunzip
```
which is fine, the hardlink is removed by an entry in `local.mog`.
However, half of the time, the manifest looks like:
```
file usr/bin/uncompress group=bin mode=0755 owner=root path=usr/bin/uncompress
hardlink path=usr/bin/gunzip target=uncompress
```
That is, the uncompress binary is found first then gunzip is added as a hard link to that. In this case, …
=> gzip: fix non-deterministic packaging

build/ncurses/build.sh, doc/packages.md
Fixes:
CVE 2017-10684
CVE-2017-10685
CVE-2017-11112
CVE-2017-11113
```
bloody# greset -V
ncurses 6.0.20170722
```
Have tested vim, less and tmux for basic functionality.
=> ncurses: update to 6.0-20170722

build/gtar/build.sh
See https://github.com/omniosorg/illumos-omnios/issues/25
```
bloody% pkg contents -m gnu-tar | grep require
depend fmri=compress/bzip2 type=require
depend fmri=compress/gzip type=require
depend fmri=compress/xz type=require
depend fmri=pkg:/system/library@0.5.11-0.151022 type=require
depend fmri=system/extended-system-utilities type=require
```
Backport for r151022l
=> gtar: Add missing dependencies

build/flex/build.sh, build/flex/testsuite.log
https://github.com/omniosorg/omnios-build/issues/37
OmniOS has had flex 2.6.0 since r151018.
Flex 2.6.4 has lots of specific bug fixes for issues reported with 2.6.0 so we should incorporate those into bloody.
Since flex is used for building parts of OmniOS, I've run a full end-to-end test build using flex 2.6.4 and it was successful.
=> Flex: update to 2.6.4

build/git/build.sh, build/mercurial/build.sh, doc/packages.md
- CVE-2017-1000117
- CVE-2017-1000116
```
hadfl@mars:/omniosorg/build/bloody/omnios-build$ git version
git version 2.13.5
hadfl@mars:/omniosorg/build/bloody/omnios-build$ hg version
Mercurial Distributed SCM (version 4.2.3)
```
=> security fixes for git and hg

build/mercurial/build.sh
Considering the latest security fix release notes:
> Note that since we dropped Python 2.6 and these issues are pretty bad, we did the back port to 4.2.3. We may not do further 4.2 releases, so please plan around Python 2.7 in the near future if you haven't already.
and since we are up to Python 2.7, I think we should head to 4.3.x for r24.
```
Mercurial Distributed SCM (version 4.3.1)
```
=> update mercurial to version 4.3.1

build/entire/entire.p5m
considering LX zones are no longer beta in OmniOS they should be part of core installation for r24+
open for discussion.
=> make LX zones part of core OmniOS

build/entire/entire.p5m
This will remove `poold` being part of OmniOS core installation for r24+.
It does not mean that `poold` (and likely Java) are removed from the core repo immediately, but it is a first step. Once removing it completely, the Java incorporation in `omnios-userland` should be removed, too.
Due to "misplaced" manifest and svc method of `poold`, it also depends on this upstream fix: https://www.illumos.org/issues/8549 (or we have to fix that in OmniOS)
Open for discussion.
cf. https://github.com/omniosorg/omnios-build/issues/6
=> make poold optional

build/expat/build.sh, doc/packages.md
Although the Expat release notes indicate that this is a security release, the security issue is windows specific. No backport to do for this update.
=> expat: update to 2.2.3

build/entire/entire.p5m, build/jeos/omnios-userland.p5m, build/sqlite3/build.sh, doc/packages.md
Maintenance update to sqlite3
```
bloody% sqlite3
SQLite version 3.20.0 2017-08-01 13:24:15
Enter ".help" for usage hints.
Connected to a transient in-memory database.
```
=> sqlite3: update to 3.20.0

build/curl/build.sh, doc/packages.md
```
bloody# curl -V
curl 7.55.1 (i386-pc-solaris2.11) libcurl/7.55.1 OpenSSL/1.0.2l zlib/1.2.11 nghttp2/1.24.0
Release-Date: 2017-08-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy
```
=> curl: update to 7.55.1

build/git/build.sh, build/git/testsuite.log, build/jeos/omnios-userland.p5m, doc/packages.md
```
bloody# git --version
git version 2.14.1
bloody# git clone https://github.com/omniosorg/omnios-build /tmp/l
Cloning into '/tmp/l'...
remote: Counting objects: 13404, done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 13404 (delta 21), reused 31 (delta 8), pack-reused 13351
Receiving objects: 100% (13404/13404), 45.07 MiB | 275.00 KiB/s, done.
Resolving deltas: 100% (7299/7299), done.
```
=> git: update to 2.14.1

build/libxml2/build.sh, lib/functions.sh
Building libxml2 on bloody now fails because it was originally packaged with automake 1.15 and bloody has 1.15.1. The patch for CVEs VE-2017-9049 & CVE-2017-9050 updates Makefile.pm which causes automake to be run as part of the build and this fails due to the automake version mismatch.
This PR fixes that along with an explanatory comment.
=> libxml2: fix build with newer automake

build/openssl/local.mog
Missing slash in pkgconfig path.
=> openssl: fix pkgconfig path

build/openssl/build.sh
The openssl package re-assigns the PKG variable a couple of times which is picked up on by `buildctl` as an additional package.
```
build:omnios-build:master% ./buildctl list
* $oPKG
* ${PKG}_legacy
* archiver/gnu-tar
* compress/bzip2
```
The fix is to add ##IGNORE## to the lines.
=> ignore $PKG reassignments

build/sqlite3/build.sh, doc/packages.md
```
% ./sqlite3
SQLite version 3.20.1 2017-08-24 16:21:36
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite>
```
Performed basic testing against a database created with 3.20.0
=> sqlite3: update to 3.20.1

build/cdrtools/build.sh
cdrecord installs the security profiles that it needs as `DESTDIR/etc/security/exec_attr.d/exec_attr` instead of using a package-specific name like `cdrecord`
This doesn't currently conflict with anything else but the name should be changed to reflect the purpose of the profiles.
=> cdrecord: use package-specific security profile

build/buildctl, lib/functions.sh
Always create local repo, even for plain manifest imports.
Centralise duplicated repository initialisation logic to new function.
Previously, building a package like `release/name` which contains a small amount of filesystem content from within the build directory would fail if the local staging repository was absent.
This corrects that by initialising the repository for all manifest packages. I also moved the initialisation logic into a new function in lib/functions.sh
=> Always create local repo, even for plain manifest imports.

build/illumos/build.sh
The illumos-gate supports either pulling packages from a pre-built illumos environment (via PREBUILT_ILLUMOS), or checking out and performing a full illumos build automatically.
The second option does not currently work and predates the addition of support for PREBUILT_ILLUMOS which is now being used for builds.
This PR removes the legacy 'fetch-and-build' code.
There's one other change in here - it's possible to pick a single package for publication via the `-f` flag.
```
bloody:omnios-build:master% ./build.sh -f runtime/perl/module/sun-solaris
===== Build started at Tue Aug 29 20:54:23 GMT 2017 =====
Package name: illumos-gate
Selected Flavor: runtime/perl/module/sun-solaris
Selected build arch: both
Extra dependency: None (use -d to specify a version)
Verifying dependencies
Preparing …
```
=> illumos-gate build updates

build/gcc5/build.sh, build/gcc5/gcc-final.mog
When building the `gcc5` package, automatic dependency resolution adds a require-any dependency for either the system libgmp or the internal gcc5 private version. This PR removes that and adds an explicit dependency for the private version.
```
bloody:omnios-build:master% pkg contents -t depend -o fmri,type gcc5 | grep gmp
['pkg:/developer/gcc5/libgmp-gcc5@6.1.2-0.151023', 'pkg:/library/gmp@6.1.2-0.151023'] require-any
```
```
bloody:omnios-build:master% pkg contents -g ../_repo -t depend -o fmri,type gcc5 | grep gmp
pkg:/developer/gcc5/libgmp-gcc5                  require
```
=> gcc5: fix libgmp dependency

build/pkg/build.sh
The `pkg` build already allow for overriding the source repository but not the branch. Fix that.
=> Allow branch override during pkg build

build/buildctl
The first commit addresses this but showed up many inconsistencies in whitespace, hence the second.
```
% ./buildctl build 'python.*27'
```
instead of
```
% ./buildctl list 'python.*27' | awk '{print $2}' | xargs ./buildctl build
```
=> Allow 'buildctl build' to take a regular expression as an argument

.gitignore, build/gcc5/build-libgcc_s.sh, build/gcc5/build-libgmp.sh, build/gcc5/build-libmpc.sh, build/gcc5/build-libmpfr.sh, build/gcc5/build-libstdc++.sh, build/gcc5/build.sh
illumos has had __cxa_atexit since 2013 (https://github.com/illumos/illumos-gate/commit/5c069a6c4b95a7360294695998bf1d3b12473abf) but the gcc configure only enables it by default on systems with SunOS 5.12+ in their uname.
Explicitly enable this at gcc build time to provide fully standards-compliant handling of static destructors in C++.
Also use a distinct build log file for each component of gcc to avoid clobbering.
=> Enable __cxa_atexit in C++ build

build/buildctl
When doing a full build and it got to `illumos-gate`, `buildctl` would sometimes build gate and sometimes the gate incorporation (`incorporation/jeos/illumos-gate`) since which one ended up in the `packages` array depended on filesystem inode.
This is fixed by changing the packages array so that it maps package suffixes to full package fmri and always using fullpackages to find the relevant build script.
I've also changed:
* Only treat the argument to `build` as a wildcard if it includes a \*;
* Moved repeated code to functions;
* Reformatted some long lines;
* Deferred time-consuming actions until needed;
* Fixed some inconsistencies in approach.
=> buildctl: Fix indeterminate build order for ambiguous packages

build/pkg/build.sh
https://github.com/omniosorg/pkg5/commit/f799808053163175ee402f967616b4821bd18184 removed `pkg5-localizable` from being published to the repo; thus `remove-publisher` would fail.
=> remove superfluous cleanup

build/python27/asn1crypto/build.sh, build/python27/cffi/build.sh, build/python27/cheroot/build.sh, build/python27/cherrypy/build.sh, build/python27/coverage/build.sh, build/python27/cryptography/build.sh, build/python27/enum/build.sh, build/python27/functools32/build.sh, build/python27/idna/build.sh, build/python27/ipaddress/build.sh, build/python27/jsonrpclib/build.sh, build/python27/jsonschema/build.sh, build/python27/lxml/build.sh, build/python27/m2crypto/build.sh, build/python27/mako/build.sh, build/python27/numpy/build.sh, build/python27/ply/build.sh, build/python27/portend/build.sh, build/python27/pybonjour/build.sh, build/python27/pycurl/build.sh, build/python27/pylint/build.sh, build/python27/pyopenssl/build.sh, build/python27/pyrex/build.sh, build/python27/pytz/build.sh, build/python27/setuptools/build.sh, build/python27/simplejson/build.sh, build/python27/six/build.sh, build/python27/tempora/build.sh, build/python27/typing/build.sh
Fix copyright messages following the recent mass python update. New modules should have OmniOSce only, updated modules should have OmniOSce added.
=> Update copyrights for OmniOSce

build/pkg-config/build.sh, build/wget/build.sh
Due to updates of underlying software, we no longer need to build `wget` and `pkg-config` using old gcc4 standards.
=> No longer need to use old gcc4 standards level for some packages

build/entire/entire.p5m, build/jeos/omnios-userland.pkg
libxslt has been updated to 1.1.30 so can no longer be installed due to the consolidation.
Rather than just increasing the version by one, drop the minor part of the revision entirely
(It's the main release, e.g. .151023, that we really want to constrain on)
=> drop minor version on libxslt requirement

build/jeos/omnios-userland.pkg, build/python27/build.sh, build/python27/cffi/build.sh, build/python27/lxml/build.sh, doc/packages.md
`pkg(5)` test suite ran with no changes against bloody baseline for all components shipped in OmniOS.
see also: https://github.com/omniosorg/omnios-build/pull/212
=> python and modules update

build/libxslt/build.sh, build/libxslt/local.mog
libxslt 1.1.30 was not properly finding the libxml2 config script in `/usr/bin/xml2-config` resulting in a broken `xslt-config` script. This is fixed through adding `--with-libxml-prefix=/usr` to the configure options.
I've also added a test to catch this if it happens in future and removed the deprecated --with-threads option which is no longer supported.
There was also a problem in that it wasn't possible to build libxslt without cleaning out the build environment, see new comment in build.sh. That is fixed by setting a flag to always clean out the build directory.
Lastly, I've removed the HTML documentation that is installed under /usr/share/doc - this is something that is done for most other packages.
=> libxslt: fix build and remove HTML docs

build/python27/build.sh
`pkg(5)` test suite ran with no changes against r151022 baseline.
`Total tests:1045 Tests run:1045 Errors:64 Failures:11 Skips:2`
=> python: update to 2.7.14

build/jeos/omnios-userland.pkg, build/python27/six/build.sh, doc/packages.md
`pkg(5)` test suite ran with no changes against bloody baseline for all components shipped in OmniOS.
=> six: update to version 1.11.0

build/jeos/omnios-userland.pkg, build/swig/build.sh, doc/packages.md
- `m2crypto` and `numpy` built successfully
- `pkg(5)` test suite ran with no changes against bloody baseline for all components shipped in OmniOS.
=> swig: update to version 3.0.12

build/mercurial/build.sh, doc/packages.md
test: `openjdk` source checkout works.
=> mercurial: update to version 4.3.2

build/tmux/build.sh, build/tmux/patches-libevent/no-arc4random-addrandom.patch, doc/packages.md
Straightforward upgrade but also changed build.sh so that the patch is not reliant on the path to libevent, easing future upgrades.
=> tmux/libevent - update to 2.1.8

build/glib/build.sh, build/glib/local.mog, build/glib/patches/series, build/glib/patches/threadlib.patch, build/glib/patches/zignore.patch
Link with -zignore so that unreferenced objects are removed from libraries during the link phase. Without this the illumos elf check reports errors like:
`unreferenced object=/usr/lib/libpcre.so.1; unused dependency of /usr/lib/libgobject-2.0.so.0.5400.0`
=> glib: Link with -zignore

build/python27/m2crypto/build.sh, build/python27/m2crypto/patches/M2Crypto-crl.patch, doc/packages.md
`pkg(5)` test suite ran with no changes against bloody baseline for all components shipped in OmniOS.
=> m2crypto: update to version 0.26.2

build/illumos/build.sh
Backported option from bloody to support the common case when we only need to prepare a subset of packages.
=> allow selective package publishing via -f

build/python27/build.sh, build/python27/patches/00-bits.patch, build/python27/patches/01-ext-stdio.patch, build/python27/patches/02-setup.patch, build/python27/patches/03-vendor-packages.patch, build/python27/patches/04-solaris-64-bit.patch, build/python27/patches/05-dtrace.patch, build/python27/patches/06-ucred.patch, build/python27/patches/07-dlpi.patch, build/python27/patches/08-encoding-alias.patch, build/python27/patches/09-rbac.patch, build/python27/patches/10-cflags.patch, build/python27/patches/10-gethostname.patch, build/python27/patches/11-closerange.patch, build/python27/patches/13-pic-compile.patch, build/python27/patches/14-py_db.patch, build/python27/patches/15-get_wch.patch, build/python27/patches/16-ossaudiodev.patch, build/python27/patches/18-osconf-long.patch, build/python27/patches/19-recvfrom_into.patch, build/python27/patches/20-bsddb-harmful.patch, build/python27/patches/multiprocessing-hack.patch, build/python27/patches/ncurses-setup.patch, build/python27/patches/series, build/python27/testsuite.log, lib/functions.sh
Usually when a software package is upgraded, local patches against it tend to carry on working but apply with some level of fuzz, offset or whatever.
It's good to be able to re-base patches again so that they apply cleanly to the source, and this also means that they are more likely to apply to the next version too.
So, I've added a `-P` flag to buildctl/build.sh allowing patches to be rebased. It's possible to change to a package directory and run `./build.sh -P`, or to run a full build with the option if necessary/desired (`./buildctl -P build all`)
This PR also includes a rebase of all of the Python patches. I've built python from this, regression tested it and also successfully run the pkg test suite.
I haven't re-based other packages as each one should be tested as it's done, but we …
=> Add patch rebase function and rebase python patches

build/jeos/omnios-userland.pkg, build/python27/asn1crypto/build.sh, build/python27/m2crypto/build.sh, build/python27/m2crypto/patches/M2Crypto-crl.patch, doc/packages.md
this updates the following python modules:
- asn1crypto: update to v0.23.0
- m2crypto: update to v0.26.3
`pkg(5)` test suite ran with no changes against bloody baseline for all components shipped in OmniOS.
=> python module updates

build/git/build.sh, build/git/testsuite.log, doc/packages.md
```
bloody% git --version
git version 2.14.2
```
The test suite run has improved a lot since the previous run so here's a summary:
```
bloody% egrep '^not ok|^# (passed|failed)' testsuite.log
not ok 5 - gettext: Fetching a UTF-8 msgid -> UTF-8
not ok 6 - gettext: Fetching a UTF-8 msgid -> ISO-8859-1
```
The two failing tests are broken in the git source - reversed expected results.
=> git: update to 2.14.2

build/pkg/build.sh
For testing purposes or to reduce build bandwidth requirements, allow `PKG5_CLONE` to be defined in site.cfg in order to use a local checkout as the source rather than pulling from git each time.
=> pkg5: Allow using a local checked out clone

build/python27/numpy/build.sh, doc/packages.md
This version update includes a fix for
- CVE-2017-12852
`pkg(5)` test suite ran with no changes against bloody baseline.
=> numpy: update to 1.13.2

build/mercurial/build.sh, doc/packages.md
```
Mercurial Distributed SCM (version 4.3.3)
```
=> mercurial: update to 4.3.3

build/dbus/build.sh, build/dbus/testsuite.log, doc/packages.md
There are a couple of other cleanups to the build script here too.
* Use `LIBTOOL_NOSTDLIB` feature instead of overriding `make_progxx`;
* Let automatic dependency discovery find SUNWcs.
=> dbus: update to 1.11.18

build/ncurses/build.sh, doc/packages.md
Ncurses update to latest release in preparation for r151024 freeze.
Tested curses applications such as vim and also run the demo applications from the source.
=> ncurses: update to 20170930

build/open-vm-tools/build.sh, build/open-vm-tools/patches/lock.patch, build/open-vm-tools/patches/nicInfo.patch, build/open-vm-tools/patches/no-glib-main-loop-unref.patch, build/open-vm-tools/patches/ucontext.patch, doc/packages.md
This release does not use the build number as part of the archive and directory name which simplifies build.sh slightly.
Also, the glib dependency is automatically detected so I've removed the manual entry from build.sh.
Finally, patches have been re-based.
Tested on bloody with VMware 5.5:
* time sync;
* shutdown / restart;
* snapshot with filesystem quiesce;
* service logs showing communication with ESX.
=> open-vm-tools: update to 10.1.15

build/dbus/build.sh, build/dbus/dbus.mog, build/dbus/libdbus.mog, build/dbus/testsuite.log, doc/packages.md
Also took the opportunity to tidy up the .mog files and drop the following documentation from the library/dbus package:
```
usr/share/doc/dbus
usr/share/doc/dbus/diagram.png
usr/share/doc/dbus/diagram.svg
usr/share/doc/dbus/examples
usr/share/doc/dbus/examples/GetAllMatchRules.py
usr/share/doc/dbus/examples/example-session-disable-stats.conf
usr/share/doc/dbus/examples/example-system-enable-stats.conf
usr/share/doc/dbus/system-activation.txt
```
=> dbus: update to 1.11.20

build/dbus/build.sh
As per comment in commit. With `dbus` >= 1.16, it is not possible to build `illumos` without this change.
=> Remove inline keyword from functions in header

build/dbus/build.sh, build/dbus/patches/inline.patch, build/dbus/patches/series
Second attempt to fix illumos build against dbus >= 1.18
Converting the functions from inline fixed the non-debug build but in the debug build the unused functions produce warnings which are treated as errors.
This PR changes the inline functions to definitions. I've tested a full nightly build with this change.
=> dbus: convert inline functions to define statements

build/python27/cffi/build.sh, doc/packages.md
`pkg(5)` test suite results according to baseline.
=> cffi: update to 1.11.1

build/entire/entire.p5m, build/jeos/omnios-userland.pkg, build/python27/m2crypto/build.sh, build/python27/m2crypto/patches/include.patch, build/python27/m2crypto/patches/series, doc/packages.md
`pkg(5)` test suite ran with no differences to baseline for components that are used in OmniOS.
=> m2crypto: update to 0.27.0

build/gcc.obs/g++4-obs.p5m, build/gcc.obs/gcc4-obs.p5m
Two more obsoleted packages which are no longer required.
=> Remove old gcc 4.8 obsoleted runtimes

build/ntp/local.mog
The Solaris standard was to ship a sample ntp configuration file as "/etc/inet/ntp.client". Recently OmniOS has started delivering a preconfigured ntp.conf file. This file may not be suitable for every installation. So we should allow other packages to overwrite the ntp.conf file by setting the IPS attribute "overlay" to "allow".
[This is the second try, this time without the big merge commit.  In the original PR, Andy Fiddaman commented: "I'm happy with this in principle. Looks like the pre-configured ntp.conf came in with r151022 and it seems like a good idea to have a working configuration out of the box, however I can see the benefit in allowing a local configuration package to overlay it."]
=> Allow other packages to overwrite ntp.conf.

lib/functions.sh
It's sometimes useful to run a package build with `-p` to see full build output on screen, but this causes the log file to be overwritten for each command run.
=> Prevent log file clobber when building with -p

build/net-snmp/build.sh
The function was removed in an earlier commit and replaced by the new `install_smf` action but the function call was missed.
=> Remove old function call

.gitignore, build/buildctl, build/gcc5/common.sh, build/gcc6/common.sh, lib/functions.sh
Here's an enhancement to the OmniOS user-land build system, allowing multiple packages to be built in parallel.
The main motivation is to reduce build time - without this, it was common to see a build server with lots of unused capacity. With the change it's easy to CPU saturate a server or KVM instance.
An example from a KVM with 8 vCPUs and 8GiB of memory:
Standard build:
`./buildctl build all  33799.09s user 2712.54s system 168% cpu 6:02:01.58 total`
Parallel build (6 threads):
`./buildctl build parallel 6  34099.08s user 2711.40s system 424% cpu 2:24:26.81 total`
and the box had almost no idle time throughout.
On another machine (Hyper-V, 6 CPUs, 8GB RAM) the build time went down from 3.8h to 1.6h using 8 parallel threads.
I will back-port this to r151024.
=> Support building in multiple parallel threads

doc/packages.md, tools/test
The bash maintainers have rolled a 4.4.12 tarball and published it on the GNU ftp site. We've had version 4.4.12 for a while now but  this updates the expected version in packages.md
We'll keep tracking the patches for future updates.
=> bash: update expected version

build/gcc.obs/g++4-obs.p5m, build/gcc.obs/gcc4-obs.p5m
This reverts commit 7e56ce9a85d6dba558f9e4cc65980976d78481a7.
Ref #292
=> Revert "Remove old gcc 4.8 obsoleted runtimes" (r151024)

build/gcc.obs/g++4-obs.p5m, build/gcc.obs/gcc4-obs.p5m
This reverts commit 7e56ce9a85d6dba558f9e4cc65980976d78481a7.
Any packages built pre-gcc5 may have dependencies on these obsoleted (actually renamed) packages so they need to stay.
This needs doing in the r151024 branch too.
=> Revert "Remove old gcc 4.8 obsoleted runtimes"

build/ncurses/build.sh, doc/packages.md
fixes `xterm` regression introduced with `6.0-20170930`.
backporting to r24.
=> ncurses: update to 6.0-20171014

lib/functions.sh
In the build system we can specify explicit minimum version dependencies by setting `RUN_DEPENDS_IPS=package/fmri@version` but we can't create dependencies that allow for any version. This change allows for this by specifying a trailing @ without a version number.
Test cases with this patch:
```
RUN_DEPENDS_IPS="library/ncurses"
--- Detected dependencies
depend fmri=pkg:/library/ncurses@6.0.20170722-0.151022 type=require
--- Final dependencies
depend type=require fmri=pkg:/library/ncurses@6.0.20170722-0.151022
```
```
RUN_DEPENDS_IPS="library/ncurses@"
--- Detected dependencies
depend fmri=pkg:/library/ncurses@6.0.20170722-0.151022 type=require
--- Final dependencies
depend type=require fmri=library/ncurses
```
```
RUN_DEPENDS_IPS="library/ncurses@6"
--- Detected dependencies
depend …
```
=> Allow specifying any-version dependencies

build/screen/build.sh, build/screen/local.mog, build/screen/patches/Makefile.in.patch, build/screen/patches/ncurses.patch, build/screen/patches/series, build/screen/patches/xnet-hack.patch, doc/ReleaseNotes.md
Build screen against `libncurses` instead of `libcurses` so it can access the latest terminal information and support more recent terminal types such as _iTerm_ and _PuTTY_.
Replace `/etc/screenrc` with the recommended global template that comes with the source. It was previously the recommended user `.screenrc` (Release notes updated to explain what users may need to do, see below).
Move gnu_cleanup() commands to actions in local.mog
Remove build_isa line since we're only building this as 32-bit (the line previously printed an error and did nothing)
Re-base patches.
=> screen: Use ncurses, update /etc/screenrc

.github/CODEOWNERS
Experimenting with this new GitHub feature which should automatically add reviewers.
=> Add default code owner reviewers

build/coreutils/build.sh, build/coreutils/local.mog, build/coreutils/patches/Makefile.in.patch, build/coreutils/patches/install.c.patch, build/coreutils/patches/man-sections.patch, build/coreutils/patches/mountlist.c.patch, build/coreutils/patches/who.c.patch, build/coreutils/testsuite.log, doc/ReleaseNotes.md
* Re-adding the GNU version of `uname` in /usr/gnu/bin but reporting `illumos` for `-o`.
* Moving link commands to package mog file.
* Tidy mog file.
* Re-basing patches.
* Build with parallel make.
* Removing GNU info.
* Adding test-suite.
pkg contents diff:
```diff
124a125
> usr/gnu/bin/uname
139,140d139
< usr/gnu/share/info
< usr/gnu/share/info/coreutils.info
451a451
> usr/gnu/share/man/man1/uname.1
```
uname
```shell
% /usr/gnu/bin/uname -a
SunOS bloody 5.11 omnios-master-00b591cca2 i86pc i386 i86pc illumos
% /usr/gnu/bin/uname -o
illumos
```
=> coreutils: clean up & add uname

lib/functions.sh
Fix bug in rebasing patches where old diff lines could be retained.
=> When rebasing patches, remove old diff lines

build/buildctl
In addition to showing the job slot status during a parallel build, include the illumos build status too if available:
```
######################################################
-- Job status --
[=]    11736 -  nightly ==== Building OS-Net source at Mon Oct 23 08:27:07
[0]    27891 - (   45s) (  1/182) archiver/gnu-tar
[1]    28345 - (   43s) (  4/182) compress/p7zip
######################################################
```
=> Report illumos stage during parallel build

build/autoconf/local.mog, build/automake/local.mog, build/coreutils/local.mog, build/gcc5/libgmp.mog, build/gcc5/libmpc.mog, build/gcc6/libgmp.mog, build/gcc6/libmpc.mog, build/grep/local.mog, build/groff/local.mog, build/m4/local.mog, lib/global-transforms.mog
GNU info files are excluded from a number of packages but not all, and excluded in differing ways.
Centralise this into the global mog file and remove the individual package exclusions.
=> Centrally discard GNU info files

build/buildctl
When doing a full end-to-end build, skip tests.
(This is already done for parallel builds, making it consistent for single-threaded)
=> Skip tests for full build

build/entire/entire.p5m, build/jeos/omnios-userland.p5m, build/mozilla-nss-nspr/build.sh, build/mozilla-nss-nspr/patches/endian.patch, build/mozilla-nss-nspr/patches/series, build/mozilla-nss-nspr/patches/sse-align.patch
This updates nss & nspr to the latest version and fixes a crash bug that was being experienced by an OmniOS user. See note in sse-align.patch for more details on the latter.
=> nss/nspr: update to 3.33/4.17 + fix sse alignment

lib/config.sh, lib/functions.sh
To easily check what has changed during package version upgrades. This is not done for batch builds.
```diff
--- Published system/library/mozilla-nss/header-nss@3.33,5.11-0.151023
-dir  path=usr/lib/mps/amd64 owner=root group=bin mode=0755
-dir  path=usr/lib/mps/secv1 owner=root group=bin mode=0755
-dir  path=usr/lib/mps/secv1/amd64 owner=root group=bin mode=0755
***
*** Differences found between old and new packages
***
Do you wish to continue anyway? (y/n)
```
=> Automatically show differences between new and old packages

build/omnios-build-tools/omnios-build-tools.p5m, build/python-vcversioner/build.sh, build/python-vcversioner/local.mog
It seems that building the `jsonschema` python package has in the past automatically downloaded and used a local copy of `vcversioner` during the build. This is still happening (and working) in bloody/r151024.
However, the old version of `setuptools` in r151022 attempts to do the download over plain HTTP and recently the source server has been updated to enforce HTTPS, and so the download fails.
So, in order to continue allowing r151022 to build, add this additional python package to the repository (and `omnios-build-tools`)
I won't add this to other versions since they continue to build fine and download the dependency temporarily via HTTPS during build.
=> Add python-vcversioner package (required for python-jsonschema)

build/entire/entire.p5m, build/jeos/omnios-userland.pkg, build/sqlite3/build.sh, doc/packages.md
```
% sqlite3
SQLite version 3.21.0 2017-10-24 18:55:49
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite>
```
=> sqlite3: update to 3.21.0

doc/baseline
Missed this in #333 
but full build currently says:
```
***
*** Checking baseline
***
--- /build/omnios-build/build/../lib/../doc/baseline    Mon Oct 30 15:45:39 2017
+++ /build/tmp/baseline.167775  Mon Oct 30 18:42:50 2017
@@ -19,1 +19,1 @@
-omnios database/sqlite-3 3.20.1-0.151023
+omnios database/sqlite-3 3.21.0-0.151023
Package list does not match baseline
```
=> Fix baseline sqlite3 version

build/ncurses/build.sh, build/ncurses/local.mog, build/ncurses/patches/xterm-no-rep.patch, doc/baseline, doc/packages.md
Also moving scripted symlinks to local.mog and taking the opportunity to simplify the terminfo patch for xterm to give it a better chance of applying cleanly against future versions.
=> ncurses: update to 20111104

build/mercurial/build.sh, doc/baseline, doc/packages.md
```
hadfl@mars:/build$ hg version
Mercurial Distributed SCM (version 4.4)
```
=> hg: update to 4.4

build/mercurial/build.sh, doc/baseline, doc/packages.md
fixing a security issue that got introduced with 4.4 (i.e. no backporting required).
```
hadfl@bloody-build:~$ hg version
Mercurial Distributed SCM (version 4.4.1)
```
=> hg: update to 4.4.1

build/buildctl
The original built cache code used temporary files to try and avoid an unlikely race condition in restoring the built cache to a child process.
(there's no race in the writer since it runs in the master process and receives updates over a pipe).
However, the use of temporary files can occasionally cause entries to be lost between copies so I am removing that part of the function and just reading directly from the cache file. It's extremely unlikely that a restore would happen halfway through a new line being written but in that case all that would happen is that a package might be built twice if the build was restarted for any reason.
=> Stop using temporary files for cache maintenance

build/buildctl, doc/baseline, tools/test
baseline is intended to prove that all packages have been built but it currently checks versions too.
This is unnecessary and adds overhead to every package update.
Will backport to r151024
=> Do not check version numbers in baseline

build/gettext/build.sh
Was printing `./build.sh: line 59: install_license: command not found` during build.
=> gettext: remove call to non-existent function

build/buildctl
Otherwise some packages published at the tail end of the build might not show up.
=> Rebuild package repository prior to evaluating baseline

build/intltool/build.sh, build/intltool/patches/braces.patch, build/intltool/patches/series
The recent perl upgrade has exposed missing escapes for left curly braces in `intltool`.
This is already fixed in an upstream branch at https://code.launchpad.net/intltool so the patch is taken from there.
=> Patch intltool to properly escape braces

build/glib/build.sh, lib/config.sh, lib/functions.sh
Build omnios user-land with gcc 6 instead of gcc 5.
The only package which required a minor change was `glib`.
=> Switch to building with gcc6

lib/config.sh
In particular this came to light when building `numpy` as this assumes a bourne compatible shell when it launches sub-commands.
Let's have a consistent environment.
=> Set SHELL variable so subshells are always started under a known interpreter

build/intltool/build.sh, build/intltool/patches/braces.patch, build/intltool/patches/series
Backport since it seems that this is a problem with perl 5.24 too (although not fatal there)
=> Patch intltool to properly escape braces (r151022)

build/intltool/build.sh, build/intltool/patches/braces.patch, build/intltool/patches/series
Backport since it seems that this is a problem with perl 5.24 too (although not fatal there)
=> Patch intltool to properly escape braces (r151024)

build/libxml2/build.sh, build/libxml2/final.mog, build/libxml2/local.mog, build/libxml2/testsuite.log, doc/packages.md
Also:
* drop examples from package
* remove stray `.la` files which were included in previous package versions by mistake
* clean-up the build script in favour of mog actions
* change package source link.
=> libxml: update to 2.9.7

build/buildctl, lib/site.sh.template
If nothing is put into the local `site.sh`, behaviour is unchanged.
This just makes it possible to set up a list of expensive-to-build packages so that they can be easily skipped when doing test builds. The examples in `site.sh.template` are the usual suspects as of now.
=> Support flagging packages as expensive to build

doc/ReleaseNotes.md
Have now checked and removed the GCC7 comment about changed standards - there were none between gcc 6 & gcc 7.
=> Update release notes

build/python27/build.sh, build/python27/testsuite.log, lib/functions.sh
Remove information that changes between test runs to make it easier to see changes with future updates.
=> Clean up python testsuite.log

build/python27/pycurl/build.sh
This used to be inherited from the Python build but this was removed in #397
=> pycurl: Build with -std=c99

build/curl/build.sh, build/curl/patches/series, build/curl/patches/tests.patch, build/curl/testsuite.log, doc/packages.md
and fix two failing test cases.
(test 1004 still fails due to OmniOS having a different system shell than expected by the test-suite).
Converts a lot of other tests from SKIP to OK too.
Already backported as #410  & #411
=> curl: update to 7.57.0

build/openssh/client.mog
With the switch to 64-bit openssh, the dtrace helper has moved to `/usr/lib/dtrace/64/` and isn't being dropped by the current lines in `client.mog`.
Fixing that and generalising the rule.
=> Drop all dtrace objects from client package

build/mercurial/build.sh, doc/packages.md
```
Mercurial Distributed SCM (version 4.4.2)
```
=> hg: update to 4.4.2

build/dma/build.sh, build/dma/files/aliases, build/dma/local.mog, build/dma/patches/dma-illumos-port.patch, build/dma/patches/mxpref.patch, build/dma/patches/series, build/entire/entire.p5m, build/jeos/omnios-userland.pkg, doc/ReleaseNotes.md, doc/baseline, doc/packages.md
This PR adds "The DragonFly Mail Agent (dma)". `dma` will be the default MTA for a fresh install from r26 on (see r151026 project page). Requirement for `mailwrapper` will be dropped as it is not necessary on an IPS mediated system  (Mailwrapper is still available to support use of packages from non-IPS repositories such as _pkgsrc_; see also: http://lists.omniti.com/pipermail/omnios-discuss/2015-March/004437.html)
> There are now three mediated MTA/MSA packages in OmniOS, `dma`, `sendmail` and `mailwrapper`; only `dma` is installed by default. To switch between them, install the appropriate package and then configure the `mta` mediator implementation.
Major parts for patches taken from @daleghent: https://github.com/corecode/dma/pull/39#issuecomment-189510297
@citrus-it did some testing: …
=> dma added (as default MTA)

build/entire/build-entire.sh, build/entire/entire.pkg
This is part of the entire clean-up task.
The rationale for this is to force fewer reboots for OmniOS updates. For example, if a server does not use lx-branded zones, then it should not have to reboot just because `system/zones/brand/lx` has been updated. The features which fall into this category are:
* lx-branded zones
* KVM
* NFS
* iSCSI
* SMB/CIFS
These packages will be still be installed for a default OmniOS installation including into a non-global zone (see PRs https://github.com/omniosorg/kayak/pull/33 & https://github.com/omniosorg/pkg5/pull/17 for this mechanism) but can subsequently be removed if desired.
* telnet client
* FTP client
* OpenSSH server
* OpenSSH client
* NTP
* Screen
* Curl
* Wget
Some packages are being removed from entire completely because they don't belong …
=> Remove packages from entire and make others optional

build/python27/cheroot/build.sh, build/python27/pycurl/build.sh, doc/packages.md
pkg test suite results match baseline.
also fixed additional manual dependency for cheroot
=>  pycurl: update to 7.43.0.1 

build/openssh/patches/0020-Compatibility-fix-for-ListenAddress.patch
If the only `ListenAddress` directive in `sshd_config` is:
`ListenAddress ::`
then sshd currently only listens on IPv6 whereas it would previously have also listened on IPv4 to retain compatibility with the behaviour of SunSSH.
Long-term we want to drop these compatibility patches entirely but not just yet.
This broke with https://github.com/omniosorg/omnios-build/commit/297a224be5d82809bc7f9e6d9704f56f421b29a8#diff-9d3895d93635e842185781b5fc0eb22fL8
=> Fix ListenAddress compatibility patch

build/pkg/build.sh, doc/ReleaseNotes.md, doc/baseline
Add package contents comparison to `pkg` and co.
Catch up with some missed release-notes changes.
See also https://github.com/omniosorg/pkg5/pull/18
=> Add sparse zones package

build/entire/build-entire.sh, build/entire/entire.pkg
Flag some packages as not required in a sparse zone.
This reduces the list of packages in the sparse zone index and those which have to be evaluated down from 390 to 188.
Since /usr contains all files from the GZ, the fact that the driver and locale packages are not specifically installed does not affect the availability of man pages and locale files.
=> Add S & Z flags for entire.

build/mozilla-nss-nspr/patches/sse-align.patch
Similarly to fdec5eedd5e17d738685cc0d301908df524a502d, gcm_HashMult_hw needs to be properly aligned for SSE.
=> nss: Force alignment for gcm_HashMult_hw (r151022)

build/entire/entire.pkg
Testing has shown that these are too closely linked to libshare and ZFS to not have in a default installation.
Re-adding, but only the `service/...` FMRIs since these packages depend on the accompanying `system/...` ones.
=> Re-add NFS & SMB to entire

build/entire/entire.pkg
The `service/storage/removable-media` package delivers the `network/rpc/smserver` service.
As long as this service is installed, `inetd` cannot be disabled without causing the server to fail to enter multi-user.
Making this optional so that it is present in release/install media but can be removed if unwanted.
=> Make storage/removable-media optional

build/bind/build.sh, build/bind/local.mog
as our other packages do. They're currently under site-packages/ which is wrong.
=> bind: deliver python modules under vendor-packages/

build/ntp/build.sh, build/ntp/local.mog
NTP currently delivers man pages to multiple places, e.g.
```
% pkg contents ntp | grep ntpd.1m
usr/share/man/man1/ntpd.1m
usr/share/man/man1m/ntpd.1m
```
This drops the copies from the non-OmniOS-standard directories.
Also removing HTML documentation
=> ntp: Remove duplicate man pages & HTML docs

build/jeos/omnios-userland.pkg, build/ntpsec/build.sh, build/ntpsec/files/ntp.conf, build/ntpsec/files/ntpsec, build/ntpsec/files/ntpsec.xml, build/ntpsec/files/security/auth_attr, build/ntpsec/files/security/prof_attr, build/ntpsec/local.mog, build/ntpsec/patches/conf.patch, build/ntpsec/patches/mansections.patch, build/ntpsec/patches/pie.patch, build/ntpsec/patches/series, build/ntpsec/testsuite.log, doc/ReleaseNotes.md, doc/packages.md
Provide NTPsec (https://www.ntpsec.org/) as a more modern, lightweight and secure alternative to  NTP Classic. The existing NTP package is not yet being deprecated (but might be in the future).
=> Add NTPsec

build/bind/build.sh, build/libxml2/build.sh, build/libxslt/build.sh, build/mercurial/build.sh, lib/functions.sh
The python module build code in `lib/functions.sh` already automatically deals with moving python files from `site-packages/` to `vendor-packages/` but other packages that deliver python components have this code in their build script. I've split out the code in functions.sh into a new function and then updated those packages that had their own copy to use the central one.
=> Centralise Python site-packages->vendor->packages code

build/dtrace-toolkit/build.sh, build/dtrace-toolkit/local.mog, build/dtrace-toolkit/patches/README, build/dtrace-toolkit/patches/newfiles.patch, build/dtrace-toolkit/patches/series, build/dtrace-toolkit/patches/update.patch
Pulling in some updates which are currently Pull Requests against https://github.com/opendtrace/opendtrace
These fix the dtrace toolkit scripts which currently don't work and add a few more from the CDDL licensed Solaris 11 version.
Example of a script that is broken without these patches:
```
bloody# /opt/DTT/execsnoop
: probe description syscall::exec:return does not match any probes
```
=> dtrace toolkit updates

build/rsync/build.sh, lib/functions.sh
Since we originally published rsync 3.1.2, we've updated it to fix CVEs but not increased the version number. That means that users need to rely on package timestamps to see which version they have. For example on r151024:
```
% pkg list -afv rsync
FMRI                                                                         IFO
pkg://omnios/network/rsync@3.1.2-0.151024:20171207T202651Z                   i--
pkg://omnios/network/rsync@3.1.2-0.151024:20171207T194017Z                   ---
pkg://omnios/network/rsync@3.1.2-0.151024:20171030T152409Z                   ---
```
As per IPS documentation:
> The third part of the version, which if present must follow a hyphen
> (-), is the branch version. The branch version is a versioning
> component that provides vendor-specific information. The …
=> rsync: update dash-revision

build/python27/setuptools/build.sh, doc/packages.md
pkg test suite run, no regressions.
rebuilt all python modules successfully with new setuptools.
=> setuptools: update to 38.4.0

build/python27/cffi/build.sh, doc/packages.md
pkg testsuite results according to baseline
(also fixed mpc download url)
=>  cffi: update to 1.11.3 

build/gcc5/build.sh, build/gcc6/build.sh, build/gcc7/build.sh
This further speeds up the build of the gcc packages.
=> gcc: skip bootstrap when rebuilding the same compiler

build/python27/cffi/build.sh, doc/packages.md
Built new module then rebuilt all python modules, installed them, and then ran the pkg test suite with no regressions.
=> cffi: update to 1.11.4

build/bind/build.sh, build/bind/local.mog, build/bind/testsuite.log, doc/packages.md
fixes a CVE in the daemon component, which we don't ship.
will backport anyway but it can wait until next week's release.
Tidied up the mog file - including fixes to handle the arbitrary selection of which is the file when a hardlink is encountered.
=> bind: update to 9.10.6-P1

build/cpuid/build.sh, doc/packages.md
This new version includes detection of the new CPU instructions added via microcode in response to the recent Spectre attach, and also provides more details on things like TLB architecture.
I'm going to backport this to r22&r24 too.
```
reaper# ucodeadm -v | head -2
CPU     Microcode Version
0       0x2d
reaper# cpuid | egrep 'IBRS|STI'
reaper# ucodeadm -u intel-ucode-201808.txt
reaper# ucodeadm -v | head -2
CPU     Microcode Version
0       0x3b
reaper# cpuid | egrep 'IBRS|STI'
Speculation Control (IBRS and IBPB)
Single Thread Indirect Branch Predictors (STIBP)
```
=> cpuid: update to 1.6.1

build/bash/patches/memalloc.patch, build/bash/patches/series, build/openssl/patches-1.0/opensslconf.patch, build/openssl/patches-1.0/series
By default, GCC considers certain identifiers in include files to be "forbidden" and will then include private modified copies of these files in its own library to override the copies in system include directories.
For userland software this is generally undesirable since GCC will continue using its private copy even when the corresponding package is updated.
In particular for openssl, this breaks the version mediation in OmniOS since gcc will continue using the openssl 1.0 header even when openssl 1.1 is selected.
=> Prevent GCC from bundling own copy of userland include files.

build/ca-bundle/build.sh
We need to bring the CA certificate bundle up-to-date.
=> ca-bundle: update to nss 3.35 (r151024)

build/bash/build.sh, build/bash/patches/bash-4.4-patches/bash44-013, build/bash/patches/bash-4.4-patches/bash44-014, build/bash/patches/bash-4.4-patches/bash44-015, build/bash/patches/bash-4.4-patches/bash44-016, build/bash/patches/bash-4.4-patches/bash44-017, build/bash/patches/bash-4.4-patches/bash44-018, build/bash/patches/series, doc/packages.md
```
hadfl@bloody-build:~$ bash --version
GNU bash, version 4.4.18(1)-release (i386-pc-solaris2.11)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
=> bash: update to 4.4.18

lib/functions.sh
The path is currently being set too late to reliably find things like `readlink`.
=> Set base path early

build/mercurial/build.sh, build/mercurial/local.mog, doc/packages.md
also dropping compiled .pyc files.
```
hadfl@mars:~$ hg --version
Mercurial Distributed SCM (version 4.5)
Copyright (C) 2005-2018 Matt Mackall and others
```
=> hg: update to 4.5

build/isc-dhcp/build.sh, build/isc-dhcp/local.mog, build/jeos/omnios-userland.pkg, doc/ReleaseNotes.md, doc/packages.md
Upgraded, tidied up, moved to 64-bit with stack guard & ASLR; and fixed a couple of packaging errors:
Pkg contents diff:
```diff
-set name=pkg.descr value="ISC DHCP 4.3.6"
+set name=pkg.descr value="ISC DHCP 4.4.0"
-file path=usr/bin/omshell owner=root group=bin mode=0755 elfarch=i386 elfbits=32
+file path=usr/bin/omshell owner=root group=bin mode=0755 elfarch=i386 elfbits=64
-    elfbits=32 restart_fmri=svc:/network/service/dhcp:ipv4 \
+    elfbits=64 restart_fmri=svc:/network/service/dhcp:ipv4 \
-    elfbits=32 restart_fmri=svc:/network/service/dhcrelay:ipv4 \
+    elfbits=64 restart_fmri=svc:/network/service/dhcrelay:ipv4 \
-file path=var/db/dhcpd.leases owner=root group=bin mode=0644
-file path=var/db/dhcpd6.leases owner=root group=bin mode=0644
-license …
```
=> ISC dhcp: update to 4.4.0

lib/functions.sh
The poor choice of wording was commented on by two different people at FOSDEM @allanjude @sjorge
=> Replace "cannot" with "should not" in places where override is offered

build/p7zip/patches/CVE-2017-17969.patch, build/p7zip/patches/series
See https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-17969
=> p7zip: Fix for CVE-2017-17969

build/coreutils/build.sh, build/coreutils/local.mog
We should provide `guname` along with other g-prefixed utilities.
looks like we forgot to do this when re-adding GNU uname to coreutils.
=> Ship /usr/bin/guname too

build/illumos-kvm/build.sh
The repository recently received a fix to handle %cr3 changing between kernel and user-space.
We don't need this for r24 so stay with the revision we have already published.
=> Stick KVM revision for r151024

build/trousers/local.mog
Without, it fails to start:
```
TCSD ERROR: mkdir(/var/tpm/system) failed: No such file or directory. If you'd like to use /var/tpm/system to store your system persistent data, please create it. Otherwise, change the location in your tcsd config file.
zsh: exit 4     /usr/sbin/amd64/tcsd -f
```
=> Trousers daemon needs /var/tpm

build/isc-dhcp/build.sh
CVE fix but only in the client part.
Bloody already has version 4.4.1
=> dhcp: update to 4.3.6-P1 (r151024)

build/pkg/build.sh, doc/ReleaseNotes.md
`vm` is a further cut-down version of the sparse `brand` that was experimented with early in this bloody cycle. It is now not going to be used.
=> Remove "vm" brand

build/mercurial/build.sh, doc/packages.md
Confirmed that the new version is fine for building openjdk.
=> mercurial: update to 4.5.2

build/ntpsec/build.sh, build/ntpsec/local.mog, lib/functions.sh, lib/global-transforms.mog
When we inherited OmniOS, most python packages shipped a few compiled python files (.pyc or .pyo extension) but this was inconsistent and could even change between package builds. 
We changed this so that no compiled files are shipped at all but that presents a problem as they are generally installed in system directories to which normal users have no write permission. This means that the bytecode compiled modules are not produced until a root user uses them; until that point no speed benefit is realised (for pkg, root will always sooner-or-later use the modules so it's less of a problem there, however...)
So, changing tack again, let's pre-compile everything during package build and include the bytecode versions too. I'm not generating the optimised (.pyo) versions since they are not …
=> Ship compiled python modules with packages

build/cpuid/build.sh, build/cpuid/patches/bhyve.patch, build/cpuid/patches/series
I've worked with the upstream maintainer to get this into cpuid trunk so we can drop the patch once a new version of cpuid is available:
Testing in OmniOS running under bhyve:
```
root@omniosce:~# cpuid | grep -i hyp
RAZ (hypervisor)
Maximum hypervisor CPUID leaf: 0x40000000
Hypervisor vendor string: 'bhyve bhyve '
BHYVE hypervisor detected
```
=> cpuid: Add detection for BHYVE hypervisor

build/xz/build.sh, build/xz/local.mog, build/xz/patches/pthread.diff, build/xz/testsuite.log, lib/functions.sh
since it was built with autoconf 1.15 and we now have 1.16, build fails with:
`/data/omnios-build/omniosorg/bloody/_build/xz-5.2.3/build-aux/missing[81]: aclocal-1.15: not found [No such file or directory]`
the solution is to run `autoreconf` instead of `autoconf`.
Also took the opportunity to tidy up the build script, add test suite and remove documentation from the final package.
=> xz needs to run full autoreconf

build/openjdk/build.sh, doc/packages.md
```
% java -version
openjdk version "1.7.0_171"
OpenJDK Runtime Environment (build 1.7.0_171-b02)
OpenJDK Server VM (build 24.171-b02, mixed mode)
```
=> openjdk: update to 1.7.0_171-b02

build/python27/cherrypy/build.sh, doc/packages.md
Only a windows-build related fix but bumping so we have the latest version.
=> cherrypy: update to 14.0.1

build/openssl/build.sh, build/openssl/patches/libs.patch, build/openssl/testsuite.log, doc/packages.md
- fixing [CVE-2018-0739](https://www.openssl.org/news/vulnerabilities.html#2018-0739)
=> openssl: update to 1.1.0h/1.0.2o

build/bhyve-fw/build.sh
The debug level is actually controlled by the -DDEBUG flag, modifying  DebugLevel just makes the non-debug build too chatty.
=> Stop modifying debug level for different builds

build/python27/cryptography/build.sh, doc/packages.md
Like last time, the changes between 2.2.1 and this are for other platforms but we need to be on the latest version ready for branching r26.
=> cryptography: update to 2.2.2

build/mercurial/build.sh, doc/packages.md
```
Mercurial Distributed SCM (version 4.5.3)
Copyright (C) 2005-2018 Matt Mackall and others
```
- additional testing: checked out openjdk source successfully
=> hg: update to 4.5.3

build/illumos-kvm/kvm.mog
Rather than making the `system/virtualisation/kvm` package a global-zone only package, revert it to both GZ & NGZ but make all of the actions GZ only.
Tested with this change and upgrade from r24 -> r26 with linked image zones now works.
=> Fix KVM variants to allow r24->r26 upgrade

build/sqlite3/build.sh, doc/packages.md
Requires back-port to r151026 as it fixes some bugs introduced in 3.23.0
=> sqlite3: update to 3.23.1

build/nghttp2/build.sh, build/nghttp2/testsuite.log, doc/packages.md
CVE-2018-1000168: Denial of service due to NULL pointer dereference.
=> nghttp2: update to 1.31.1

build/perl/patches/CVE-2018-6797.patch, build/perl/patches/CVE-2018-6798a.patch, build/perl/patches/CVE-2018-6798b.patch, build/perl/patches/CVE-2018-6798c.patch, build/perl/patches/CVE-2018-6913.patch, build/perl/patches/series, doc/ReleaseNotes.md
As per #696 I've included the necessary release notes update for tomorrow due to the draft release notes having been merged in error.
=> perl: fixes for CVE-2018-6797,6798,6913 (r51022)

build/perl/build.sh, doc/ReleaseNotes.md, lib/config.sh
I've included the release notes update here since the draft release notes for tomorrow's r151024x have already been merged in error.
=> perl: update to 5.24.4 (r151024)

build/zsh/build.sh, build/zsh/testsuite.log, doc/packages.md
Although there are only minor changes from 5.5, we should backport this to r26.
> Apart from a fix for a configuration problem finding singal names from
> some) recent versions of glibc, there are only minor changes.
=> zsh: update to 5.5.1

build/openssh/files/ssh.xml, build/openssh/files/sshd
Our SSH SMF files are out of sync with the SMF ipfilter framework changes from  https://github.com/illumos/illumos-gate/commit/7ddce99911fbb5e44b38ac65e991a22e42267ee9
=> SMF ipfilter does not work with ssh

build/ncurses/build.sh, doc/packages.md
This is a fix for CVE-2018-10754 In ncurses before 6.1.20180414, there is a NULL Pointer Dereference...
=> ncurses: update to 6.1.20180428

build/mercurial/build.sh, doc/packages.md
Tested by running openjdk build with this new version.
=> mercurial: update to 4.6

build/mozilla-nss-nspr/build.sh, doc/packages.md
In terms of certificates, this update removes four old CAs and adds no new ones therefore I'm not flagging this for back-port.
=> nss: update to 3.37

build/cdrtools/build.sh
Since there is no `configure` for cdrtools, we need to export CC to ensure that our preference is picked up by the static Makefile. This makes the build more predictable regardless of software installed on the server.
=> cdrtools: Export CC for make

build/gnu-make/build.sh, build/gnu-make/patches/gcc.patch, build/gnu-make/patches/series, build/gnu-make/patches/testsuite.patch, build/gnu-make/testsuite.log
Since gcc is the native compiler on OmniOS, make utilities should default to it in the absence of a CC environment variable.
Before:
```
build% gmake c
cc     c.c   -o c
gmake: cc: Command not found
```
After:
```
bloody% gmake c
gcc     c.c   -o c
```
While there, switch this to 64-bit and remove the run-dependant parts of the test-suite output.
=> GNU make - 64-bit, default to CC=gcc, clean testsuite output

build/cdrtools/build.sh, lib/functions.sh
This change creates a tools/ area which is placed early in the path in our build environment (just after the specific GCC compiler version).
This area contains binaries called `cc` and `CC` which link to `/bin/false`, preventing configuration scripts from detecting a studio compiler even if there is a `/usr/bin/cc` on the system (for example).
Further links can be added to this in the future to ensure a consistent build environment across systems.
```
% ls -l ../_build/tools
total 4
lrwxrwxrwx   1 af       other         10 May 15 09:55 CC -> /bin/false*
lrwxrwxrwx   1 af       other         10 May 15 09:55 cc -> /bin/false*
lrwxrwxrwx   1 af       other         18 May 15 10:03 g++ -> /opt/gcc-7/bin/g++*
lrwxrwxrwx   1 af       other         18 May 15 10:03 gcc -> /opt/gcc-7/bin/gcc*
```
=> Provide tools area for consistent build environment.

build/mozilla-nss-nspr/build.sh, lib/functions.sh
Export CC so that mozilla-nss uses the right compiler
=> Export CC so that mozilla-nss uses the right compiler

build/sigcpp/build.sh, build/sigcpp/testsuite.log, doc/packages.md
Now that illumos 9527 has been merged into bloody, we can update this package.
=> libsigc++: update to 2.99.11

lib/functions.sh
Some software packages are only supported/tested with builds that are done out of the source tree. Gcc is an example of this, from the installation instructions:
>First, we **highly** recommend that GCC be built into a
> separate directory from the sources which does **not** reside
> within the source tree.  This is how we generally build GCC; building
> where `srcdir` == `objdir` should still work, but doesn't
> get extensive testing; building where `objdir` is a subdirectory
> of `srcdir` is unsupported.
This PR adds support for building in this way by setting the new `OUT_OF_TREE_BUILD` variable in the build script.
=> Add out-of-tree build support

build/as/build.sh, build/entire/build-entire.sh, build/gcc5/build.sh, build/jeos/build-gate.sh, build/jeos/build-userland.sh, build/kayak-kernel/build.sh, build/openjdk/build.sh, build/sccs/build.sh, build/tmux/build.sh, lib/config.sh, lib/functions.sh
Aside from tidying up the temporary area by keeping related files together, this also fixes a problem with packages where the download archive is just a plain version number (1.2.3.tar.gz) - common with releases posted on github. If two packages like this have the same version number and are built in parallel, chaos ensues.
I've done a full userland build with this change and tweaked a few other packages along the way.
Mainly this was to add missing PROG= lines or change ones that had the wrong value, fix packages that didn't fully use the build framework (taking care of their own DESTDIR instead of using `init` & `prep_build` for example)
The sccs package was one of those but was also broken as the symlinks delivered into /usr/ccs/bin pointed nowhere.
=> Build each package in a sub-directory of the temporary area.

build/acpica/build.sh
=> acpica build requires GNU m4

build/mercurial/build.sh, doc/packages.md
mercurial: update to 4.6.1
Did test openjdk build which was successful.
=> mercurial: update to 4.6.1

build/ca-bundle/build.sh, build/mozilla-nss-nspr/build.sh, doc/packages.md, lib/functions.sh
I've also made change to ca-bundle so that it extracts certificates from the same archive file used to build nss/nspr packages, rather than us having to put and maintain both the combined and nss-only files on the mirror.l
Additionally, since ca-bundle only needs two files from the archive, I've extended extract_archive to take additional arguments so that we only need to extract the required files. This may be generally useful elsewhere too since it allows passing arbitrary arguments into $TAR for example.
=> nss: upgrade to 3.37.3

build/illumos-kvm/build.sh
Required to support Eager FPU - see https://github.com/omniosorg/illumos-omnios/pull/228
=> Update KVM version to latest Joyent HEAD (r151026)

build/bhyve-fw/build.sh
nasm is no-longer in /usr/bin/i386/
=> nasm is no-longer in /usr/bin/i386/

build/gcc-runtime/build-runtime++.sh, build/gcc-runtime/build-runtime.sh, build/gcc-runtime/build-runtimef.sh, build/gcc-runtime/runtime++.mog, build/gcc-runtime/runtime.mog, build/gcc-runtime/runtimef.mog, build/gcc-runtime/runtimef_post.mog, build/gcc5/patches/ld-flags.patch, build/gcc5/patches/series, build/gcc7/patches/1000-ld-flags.patch, build/gcc7/patches/series, build/gcc8/patches/1000-ld-flags.patch, build/gcc8/patches/series, lib/functions.sh
I've placed the version-specific libraries in /usr/gcc/<ver> to mirror what OpenIndiana already do, and what Joyent are in the process of doing for SmartOS (https://smartos.org/bugview/OS-7042) - at least in terms of the extra runpath that gcc adds to binaries.
I've also added a generic dangling symlink checker as I created a few danglers during development.. this would also have spotted the one that was in the sccs package for a long time - I'll look at enabling this by default as part of the pre-packaging checks in another PR.
Please review the resulting symlink structure (below) before approving as I had to make some choices along the way. The main system GCC version is still 7 and so this is the version to which the unversioned links in /usr/lib point. This will fix the compatibility …
=> Split off gcc runtime libraries into per-version directories

build/python27/local.mog, build/python35/local.mog
```
% python
Python 2.7.15 (default, Jul  9 2018, 19:40:41)
[GCC 7.3.0] on sunos5
Type "help", "copyright", "credits" or "license" for more information.
>>>
% pfexec pkg set-mediator -V 3 python
Packages to change:  1
Mediators to change:  1
Create boot environment: No
Create backup boot environment: No
PHASE                                          ITEMS
Updating modified actions                        1/1
Updating package state database                 Done
Updating package cache                           0/0
Updating image state                            Done
Creating fast lookup database                   Done
% python
Python 3.5.5 (default, Jul  9 2018, 19:47:08)
[GCC 7.3.0] on sunos5
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
=> Make /usr/bin/python a mediated link

build/gcc7/build.sh, build/gcc8/build.sh, build/gcc8/patches/0003-gcc-enable-the-.eh_frame-based-unwinder.patch
Without this, it does not find the linker version and therefore does not detect that it has support for eh_frame headers. Without this linker support, gcc adds additional function calls to `crtbegin.o` which use functions in `libgcc_so.1` and cause all compiled programs to gain an unnecessary dependency.
```
bloody% cat c.c
#include <stdio.h>
int
main()
{
printf("Hello\n");
return 0;
}
bloody% /opt/gcc-8/bin/gcc -o c c.c
bloody% ldd c
libgcc_s.so.1 =>         /usr/gcc/8/lib/libgcc_s.so.1
libc.so.1 =>     /lib/libc.so.1
libm.so.2 =>     /lib/libm.so.2
bloody% nm -gp /opt/gcc-8/lib/gcc/i386-pc-solaris2.11/8.1.0/crtbegin.o
0000000000 U _GLOBAL_OFFSET_TABLE_
0000000000 U _ITM_deregisterTMCloneTable
0000000000 U _ITM_registerTMCloneTable
0000000000 U __TMC_END__
0000000000 U …
```
=> Gcc8 configure needs "gsed" to find linker version

build/release/local.mog
This is to support automatic BE naming in pkg5. At present, the property names are too generic so adding an `ooce.` prefix so that they can be distinguished from any other packages that might use a property called `release`.
=> Add ooce prefix to release/name properties

build/ca-bundle/build.sh
`/etc/ssl/cacert.pem` is much larger than necessary as it contains the text form for all certificates within.
=> Remove text representations from cacert.pem

build/mercurial/build.sh, doc/packages.md, lib/config.sh, lib/functions.sh
Looked at switching this to python3 but Mercurial currently only supports 2.7
```
bloody:omnios.bloody:hg% hg version
Mercurial Distributed SCM (version 4.7)
Copyright (C) 2005-2018 Matt Mackall and others
```
openjdk build succeeded with this new version.
=> mercurial: update to 4.7

build/cpuid/patches/l1df.patch, build/cpuid/patches/series
```
bloody# cpuid
...
Structured extended feature flags (ecx=0), edx:
Speculation Control (IBRS and IBPB)
Single Thread Indirect Branch Predictors (STIBP)
L1 Data Cache (L1D) Flush
Speculative Store Bypass Disable (SSBD)
```
=> cpuid: add support for L1D flush command

build/ntp/files/ntp.xml, build/ntpsec/build.sh, build/ntpsec/files/ntpsec.xml, build/ntpsec/testsuite.log, build/open-vm-tools/files/open-vm-tools.xml, doc/packages.md
The second commit addresses https://github.com/omniti-labs/omnios-build/issues/94 by not allowing `open-vm-tools` and either `ntpd` to run concurrently.
=> ntpsec: update to 1.1.2 & add smf exclusions

build/isc-dhcp/build.sh
=> isc-dhcp still requires -lnsl

.gitignore, lib/functions.sh
For example:
```
% pwd
/data/omnios-build/omniosorg/bloody/omnios/build/nghttp2
% ls
build.sh*   local.mog
% ./build.sh
...
% ls tmp
library_nghttp2_pkg/           nghttp2-1.32.1.tar.xz
nghttp2-1.32.1/                nghttp2-1.32.1.tar.xz.sha256
% ls -l
total 55
-rw-r--r--   1 af       other       116K Sep  2 10:07 build.log
-rwxr-xr-x   1 af       other      1.57K Sep  2 09:59 build.sh*
-rw-r--r--   1 af       other        363 Jul 11 13:51 local.mog
lrwxrwxrwx   1 af       other         57 Sep  2 10:06 tmp -> /data/omnios-build/omniosorg/bloody/_build/nghttp2-1.32.1/
```
=> Create link to temporary working area in build directory

build/zsh/patches/CVE-2018-0502,13259.patch, build/zsh/patches/series
zsh 5.6 is on the download site but has not yet been announced and is broken in a couple of ways.
Adding security patches for now.
=> zsh: add patches for CVE-2018-0502,13259

build/iso-codes/build.sh, doc/packages.md
From the release notes:
```
* The XML files have been re-added, because too many
other programs still rely on those files.
***********************************************************
** If you're maintaining a program which uses XML files, **
** please switch to the JSON data files.                 **
***********************************************************
```
So, I've reverted our local XML file preservation.
=> iso-codes: update to 4.1

lib/functions.sh
Utility links should move on version change; add link to source tree
=> Utility links should move on version change; add link to source tree

build/mozilla-nss-nspr/build.sh, build/mozilla-nss-nspr/nss.mog
```diff
+dir  path=usr/share/man/man1 owner=root group=bin mode=0755 facet.doc.man=true
+file path=usr/share/man/man1/certutil.1 owner=root group=bin mode=0644 \
+    facet.doc.man=true
```
=> mozilla-nss: Ship certutil man page

build/jeos/build-userland.sh, lib/config.sh, lib/functions.sh
This is extracted from the `pkg(5)` man page:
> A package version consists of four sequences of numbers, separated by punctuation.
>The first part of the version is the component version. For a component with its own development life-cycle, this sequence is a dotted release number, such as 2.4.10.
> The second part of the version, which if present must follow a comma (,), is the build version. The build version specifies what version of the operating system the contents of the package were built on.
> The third part of the version, which if present must follow a hyphen (-), is the branch version. The branch version is a versioning component that provides vendor-specific information. The branch version can be incremented when the packaging metadata is changed, independently of the …
=> Reverse components of dash-revision

build/python27/cheroot/build.sh, build/python27/cherrypy/build.sh, build/python35/cheroot/build.sh, build/python35/cherrypy/build.sh, doc/packages.md, tools/test
Note that cherrypy >= 18 only supports python3 so the python2 module version remains at 17.
=> Python module updates.

build/cpp/build.sh, build/cpp/local.mog
cpp: clean up build script, stop requiring gcc 4
=> cpp: clean up build script, stop requiring gcc 4

build/python35/build.sh
Python3 dtrace tests leave root owned files in tmp area
=> Python3 dtrace tests leave root owned files in tmp area

lib/functions.sh
Fix problem with some packages appearing to fail during a parallel build, despite actually building and publishing correctly. This is caused by the overall build script exiting with a non-zero code. It seems to be a problem in bash where exit codes are not consistently passed up from subroutines. I tested in other shells and the results were always consistent but in bash I got about an 80/20% split in behaviour.
Regardless, explicitly returning 0 on successful completion of the package build and cleanup functions resolves the problem as far as my testing shows.
=> Return explicit success status

build/illumos-kvm/build.sh, build/openjdk/build.sh
Extended clean_up functions should always return 0
=> Extended clean_up functions should always return 0

build/release/build.sh
This will result in versions for release/name of the form
```
pkg://omnios/release/name@0.5.11-151028.28:20180905T084129Z
```
which would correspond to `r151028ab`
=> Set dashrev for release/name

build/libidn/build.sh, build/net-snmp/build.sh
r151028 testing showed up this problem. A couple of packages have changed the major version of their libraries between r26 and now. We need to continue shipping the previous versions to support any software linked against them. I've also added a test for this to the pre-release testing sheet.
Two different approaches here - libidn is fairly simple so I'm building both old and new versions. Building an older version of libnetsnmp is harder (partly because it does not build with openssl 1.1 and partly because of the amount of patches we apply) so I'm copying the libraries from the live system.
```diff
--- Published library/libidn@1.35,5.11-151027.0
+link path=usr/lib/amd64/libidn.so.11 target=libidn.so.11.6.18
+file path=usr/lib/amd64/libidn.so.11.6.18 …
```
=> Restore legacy libraries

build/glib/patches/series, build/glib/patches/setname.patch
Temporarily disable the detection of pthread_setname_np() and
pthread_getname_np(). These are present in OmniOS as of r151028 but if
glib2 uses those symbols then it becomes impossible to build stock
illumos-gate on OmniOS. Once illumos 8158 is integrated, this patch
can be removed.
=> glib2: temporarily disable pthread_setname_np()

build/glib/patches/series, build/glib/patches/setname.patch
=> glib2: temporarily disable pthread_setname_np() (r151028)

build/meta/illumos-tools.p5m, build/meta/omnios-build-tools.p5m
illumos builds now require python-35
=> illumos builds now require python-35

lib/functions.sh
This gets rid of the spurious warnings that always appear such as
```
WARNING pkglint.action005.1       obsolete dependency check skipped: unable to find dependency pkg:/system/library@0.5.11-151028.0 for pkg:/developer/as@0.5.11,5.11-151027.0
```
by providing pkglint with a complete list of packages. With this in place, all warnings from `pkglint` are real and should be resolved.
=> Use custom pkglint configuration file

build/meta/illumos-tools.p5m
gcc7 is now required for illumos builds
=> gcc7 is now required for illumos builds

build/acpica/build.sh, build/gcc-runtime/build-runtime++.sh, build/gcc-runtime/build-runtime.sh, build/gcc-runtime/build-runtimef.sh, build/gcc-runtime/common.sh, build/nasm/build.sh, build/openssh/build.sh, lib/config.sh
Two packages fail to build with gcc8 and so have been left on gcc7:
`acpica` - which will be removed soon anyway once illumos-gate has the new ACPI support integrated;
`nasm` - needs further investigation.
=> Change default gcc version to 8

build/entire/entire.pkg
Although it can be subsequently removed, we ship `ntp` in our default installation images. This should be replaced by the newer and better maintained `ntpsec`.
=> Replace ntp with ntpsec in default image

lib/functions.sh
Remove SHA2 hashes from manifests when comparing
=> Remove SHA2 hashes from manifests when comparing

build/jeos/build-userland.sh, build/jeos/omnios-userland.pkg
The `release/name` package has a dash-revision which reflects the release suffix. `omnios-userland` needs to allow any dash revision rather than just 0
=> Skip dashrev lock for release/name

build/gcc8/patches/0006-allow-the-global-disabling-of-function-cloning.patch
gcc8 - use newer no-clone-functions patch
=> gcc8 - use newer no-clone-functions patch

build/gcc8/patches/0006-allow-the-global-disabling-of-function-cloning.patch
gcc8 - use newer no-clone-functions patch (r151028)
=> gcc8 - use newer no-clone-functions patch (r151028)

build/bind/build.sh
The first commit in the build.sh history is this:
```
commit 3b48761d8f2ee0331b0acae003baf11af93f7b30
Author: Eric Sproul <esproul@omniti.com>
Date:   Mon Mar 12 17:34:40 2012 +0000
tid18365 network/dns/bind (BIND utilities). 
Since the shared libs are not the exported versions and are used only in
support of the client binaries, we just build 32-bit.
```
I've added an explanatory comment to the build.sh about this and moved to 64-bit. We have never shipped the include files so the libraries - in their private location - should not be depended on by anything.
Also, since everything apart from the client utilities is private here, dropped the python modules entirely.
=> Move bind to 64-bit, add comment clarifying library status, drop python modules.

build/screen/build.sh, build/screen/local.mog, build/screen/patches/Makefile.in.patch, build/screen/patches/ncurses.patch, build/screen/patches/series, build/screen/patches/xnet-hack.patch
We changed screen to use ncurses in October 2017 but did not backport it to r151022.
Now an r151022 user has reported that screen is not working with xterm256-color
=> screen: use ncurses (r151022)

build/pkg/build.sh, lib/functions.sh
At present, pkg5 is partially built with gcc4 and partially with gcc8. Change the build script to explicitly pass the desired compiler version.
NB: The test suite currently needs to be run with gcc4 due to tests that do not expect the compiler to create binaries with a runpath including /usr/lib/gcc/8 - this still needs resolving.
=>  Explicitly specify compiler for pkg5 build

lib/config.sh, lib/functions.sh
As per OpenIndiana and Solaris, and to help with satisfying GPL by including a source download link with each published package.
Example, with gzip
```diff
--- Published compress/gzip@1.9,5.11-151029.0
+set name=info.source-url value=https://mirrors.omniosce.org/gzip/gzip-1.9.tar.xz
```
=> Include info.source-url in package meta information

build/meta/illumos-tools.p5m, build/meta/omnios-build-tools.p5m
with 9997, illumos builds now require idnkit (r151028)
=> with 9997, illumos builds now require idnkit (r151028)

build/meta/illumos-tools.p5m, build/meta/omnios-build-tools.p5m
with 9997, illumos builds now require idnkit
=> with 9997, illumos builds now require idnkit

build/libxml2/build.sh, build/openssl/build.sh, build/openssl/local.mog, build/trousers/build.sh, build/zlib/build.sh, lib/functions.sh
https://illumos.org/issues/9978 removed the requirement to run lint against illumos-gate, and we mirrored the same change to illumos-omnios builds.
See also https://illumos.org/issues/10011
=> Following 9978, remove lint libraries

build/meta/illumos-tools.p5m, build/meta/omnios-build-tools.p5m
sunstudio no longer required to build any part of omnios
=> sunstudio no longer required to build any part of omnios

build/jeos/omnios-userland.pkg, build/sccs/build.sh, build/sccs/local.mog, build/sccs/patches/03.Defaults.sunos5.patch, build/sccs/patches/04.remove_ccs.patch, build/sccs/patches/series, doc/packages.md, tools/test
Move from the legacy devpro sccs to Schily sccs.
The main motivation is to drop the last dependency on sunstudio for building OmniOS.
=> sccs: update to 5.08

build/meta/illumos-tools.p5m
Studio is still required to build gate lint libraries
=> Studio is still required to build gate lint libraries

lib/functions.sh
When preparing for r151028, we noticed in testing that some libraries had undergone an ABI change and so software built under the previous OmniOS release may not run have run on the new if there was a dependency on the library with the old ABI.
This change adds an automated check to alert package builders when this occurs.
For example, if an old ABI library is no longer present, the build will now fail:
```
-- Checking for library ABI changes
--- Found libraries, fetching previous package contents
--- libreadline ABI change, 6 7  -> 7 8
--- libreadline.so.6 missing from new package
An Error occured in the build. Do you wish to continue anyway? (y/n)
```
when a new version is added, there's just a note
```
-- Checking for library ABI changes
--- Found libraries, fetching previous package …
```
=> Add automatic library ABI check when packaging

build/gcc8/patches/series, build/gcc8/patches/standards.patch
We originally dropped the startfile arch patch in gcc8 (https://github.com/illumos/gcc/commit/d5e28d05a9f21a927da854f112928fe6ee88cd60 ) as the problem has been fixed upstream for gcc8.
However, without this patch we are seeing some pty-related test failures in packages such as `zsh`  - possibly because the upstream fix only links _values-xpg6.o_ into executable programs - see https://github.com/gcc-mirror/gcc/blob/master/gcc/config/sol2.h#L199
With this additional patch applied to the compiler, the `zsh` test suite passes.
=> Change the gcc startfile spec to match what we had in gcc7

build/jeos/omnios-userland.pkg, build/mercurial/build.sh, build/mercurial/patches/series, build/mercurial/patches/subrepo.6c10eba6b9cd.patch, build/mercurial/patches/subrepo.83377b4b4ae0.patch
mercurial: backport security patches from 4.9 (r151028)
=> mercurial: backport security patches from 4.9 (r151028)

build/python27/build.sh, build/python35/build.sh
The python ctypes module expects to find `/usr/ccs/bin/dump` in order to extract information from shared libraries at runtime. One particular usage of this is in the `uuid` module which is used often for IPS package operations (where a temporary UUID is required, such as when running `pkgrepo`).
`/usr/ccs/bin/dump` is part of `developer/object-file` and without the latter package installed pkg operations requiring a uuid can hang for up to 2 minutes.
The best way to fix this seems to be adding `developer/object-file` as a dependency for python, since it is. This will effectively make the package part of the base OmniOS installation image (since python is) but it is small:
```
% pkgmgr list r151028 --dst -l object-file
PKG                                      FLAGS    FILES        SIZE …
```
=> Add developer/object-file dependency to python

build/ncurses/patches/extra-newline.patch, build/ncurses/patches/series, build/ncurses/patches/sun-color.patch, build/ncurses/patches/xterm-no-rep.patch
Replicating a terminfo change from upstream gate.
Since sun-color is not just illumos, this is not going to be upstreamed, and it only applies to illumos after the support was integrated so is not eligible for backport.
=> ncurses: add underline for sun-color

lib/functions.sh
This allows multiple illumos packages to be built at once via, for instance:
```
cd build/illumos
./build.sh -f "SUNWcs system/kernel/platform"
```
=> Allow $FLAVOR to contain spaces

build/meta/illumos-tools.p5m
Add missing pkg-35 dependency to illumos-tools (r151028)
=> Add missing pkg-35 dependency to illumos-tools (r151028)

build/gcc7/patches/no-lpthread.patch, build/gcc7/patches/series, build/gcc8/patches/no-lpthread.patch, build/gcc8/patches/series
Prevent gcc from linking with libpthread if -pthread[s] is passed as an option.
libpthread is a filter in illumos; all functionality has been migrated to libc.
Some build systems such as meson/ninja pass this option; glib2 now requires
meson/ninja to build. Since glib2 is linked with hald in gate, the spurious
libpthread causes build warnings.
```
bloody% gcc -pthread -o test test.c
bloody% ldd test
libpthread.so.1 =>       /lib/libpthread.so.1
libc.so.1 =>     /lib/libc.so.1
libm.so.2 =>     /lib/libm.so.2
bloody% gcc -dumpspecs
*lib:
%{!symbolic:     %{pthreads|pthread:-lpthread}      %{p|pg:-ldl} -lc}
bloody% pfexec pkg update gcc7
bloody% gcc -pthread -o test test.c
bloody% ldd test
libc.so.1 =>     /lib/libc.so.1
libm.so.2 =>     /lib/libm.so.2
bloody% gcc -dumpspecs
*lib: …
```
=> Stop gcc linking with -lpthread

build/entire/entire.pkg
hyperv should not be installed in any NGZ
=> hyperv should not be installed in any NGZ

build/entire/build-entire.sh
This changes lines in entire from:
```diff
-depend fmri=pkg://omnios/text/gnu-patch@2.7,5.11-151029.0 type=require
+depend fmri=pkg://omnios/text/gnu-patch@2.7,5.11-151029 type=require
```
before this change, all lines in entire had a dashrev of 0, implying a minimum version. Removing the dashrev entirely achieves the same result and is better for some of the other processes such as optional package install during zone creation.
```
bloody% pkg contents -m entire | grep gnu-patch
depend fmri=pkg://omnios/text/gnu-patch@2.7,5.11-151029 type=require
bloody% pfexec pkg uninstall gnu-patch
Creating Plan (Solver setup): /
pkg uninstall: Unable to remove 'text/gnu-patch@2.7.6-151029.0' due to the following packages that depend on it:
entire@11-151029.0
```
=> Entire should not include dashrevs

build/meta/omnios-build-tools.p5m
`library/iconv/unicode` is required to build current `vim`
=> add missing omnios-build tool

build/gfx-drm/build.sh, build/jeos/illumos-gate.exclude, doc/baseline
Now that gfx-drm has been removed from gate, the `system/header/header-agp` package should be shipped from the gfx-drm gate. There is also `system/header/header-drm` which was not previously shipped but is being included for completeness and consistency with other distributions.
=> Continue to ship gfx-drm header file packages

build/azure/build.sh, build/azure/local.mog, build/jeos/omnios-userland.pkg, doc/packages.md
This adds the Azure Guest Agent (waagent) to OmniOS core.
It builds from https://github.com/omniosorg/waguestagent which will no doubt receive several more updates as testing progresses, but that should not require changes to these build scripts.
=> Add Azure Guest Agent

build/vim/patches/series, build/vim/patches/vim-sandbox.patch
vim: Disallow sourcing a file from the sandbox (r151022)
=> vim: Disallow sourcing a file from the sandbox (r151022)

lib/functions.sh
This cleans up manifests by removing unnecessary action attributes. Here's an example for the `git` package. This is an example where only a couple of lines change, for others it is more significant. For `pkg` itself this shrunk the manifest by around 7%.
Depends on https://github.com/omniosorg/pkg5/pull/151/
```diff
--- Published developer/versioning/git@2.22.0,5.11-151031.0
-set name=pkg.debug.depend.bypassed value=usr/libexec/git-core/git-p4:.*
-file path=usr/libexec/amd64/git-core/git-p4 owner=root group=bin mode=0755 \
-    pkg.depend.bypass-generate=.*
+file path=usr/libexec/amd64/git-core/git-p4 owner=root group=bin mode=0755
-file path=usr/libexec/git-core/git-p4 owner=root group=bin mode=0755 \
-    pkg.depend.bypass-generate=.*
+file …
```
=> Automatically format and strip manifests before publishing

build/python35/build.sh, build/python35/patches/no-zip-in-sys-path.patch, build/python35/patches/series
```
bloody:omnios.bloody:pyzip% python3
Python 3.5.7 (default, Jun 17 2019, 17:52:08)
[GCC 8.3.0] on sunos5
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; sys.path
['', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-sunos5', '/usr/lib/python3.5/lib-dynload', '/data/omnios-build/.local/lib/python3.5/site-packages', '/usr/lib/python3.5/site-packages', '/usr/lib/python3.5/vendor-packages']
>>>
bloody:omnios.bloody:pyzip% pfexec pkg update python-35
Packages to update:  1
bloody:omnios.bloody:pyzip% python3
Python 3.5.7 (default, Jun 25 2019, 09:59:58)
[GCC 8.3.0] on sunos5
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; sys.path
['', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-sunos5', …
```
=> Remove /usr/lib/python35.zip from python path

build/binutils/build.sh
I ran a full `build_world` with a 64-bit binutils package installed and it was successful.
Also did an `onu` to the new build which worked fine. There may be regressions but getting this into bloody will help shake them out.
Related to #1487
=> binutils: switch to 64-bit

build/meta/illumos-tools.p5m
Whilst not strictly required, this can help bldenv set VERSION properly so that incremental builds can be performed.
=> Require ctf tools for illumos builds

build/gcc7/patches/0002-compare_tests-Use-nawk-1-on-illumos-since-awk-1-is-o.patch, build/gcc7/patches/0003-gcc-enable-the-.eh_frame-based-unwinder.patch, build/gcc7/patches/0004-intl-Don-t-use-UTF-8-quotes.-Ever.patch, build/gcc7/patches/0005-Implement-fstrict-calling-conventions.patch, build/gcc7/patches/0006-allow-the-global-disabling-of-function-cloning.patch, build/gcc7/patches/0007-strict-cc2-check-that-disabling-function-cloning-pre.patch, build/gcc7/patches/0008-sol2-enable-full-__cxa_atexit-support.patch, build/gcc7/patches/0009-sol2-Use-appropriate-values-objects-for-the-various-.patch, build/gcc7/patches/0010-i386-Save-integer-passed-arguments-to-the-stack-to-a.patch, build/gcc7/patches/0011-16-update-cmn_err-format-specifier.patch, build/gcc7/patches/0012-19-cmn_err-b-conversion-should-accept-0-flag.patch, build/gcc7/patches/0013-We-never-want-to-omit-the-frame-pointer-regardless-o.patch, build/gcc7/patches/0014-libstdc-v3-illumos-and-Solaris-haven-t-needed-lrt-in.patch, build/gcc7/patches/0015-libgo-libelf-on-illumos-doesn-t-support-largefile.patch, build/gcc7/patches/0016-libgcc-unwind.map-should-be-v2-style.patch, build/gcc7/patches/0017-libpthread-is-a-filter-in-illumos-all-functionality-.patch, build/gcc7/patches/0018-i386-Fix-grammar-of-msave-args-usage-message.patch, build/gcc7/patches/0019-OOCE-Adjust-default-library-paths-for-OmniOS.patch, build/gcc7/patches/0020-tests-x86_64-pro_and_epilogue-RTL-can-t-work-with-ms.patch, build/gcc7/patches/0021-i386-don-t-assert-the-FP-is-valid-during-epilogue-ad.patch, build/gcc7/patches/0022-gcc.target-i386-retarg-skip-if-msave-args.patch, build/gcc7/patches/0023-i386-use-correct-error-message-about-msave-args-and-.patch, build/gcc7/patches/0024-gcc.target-i386-skip-16bit-tests-when-msave-args.patch, build/gcc7/patches/0025-i386-use-the-new-style-retpoline-thunk-names-for-ext.patch, build/gcc7/patches/0026-Use-GNU-backends-for-gcc-ar-nm-ranlib.patch, build/gcc7/patches/series
gcc7: use the new-style retpoline thunk names for external thunks
Also fixes #1487
=> gcc7: use the new-style retpoline thunk names for external thunks

build/gcc7/patches/0002-compare_tests-Use-nawk-1-on-illumos-since-awk-1-is-o.patch, build/gcc7/patches/0003-gcc-enable-the-.eh_frame-based-unwinder.patch, build/gcc7/patches/0004-intl-Don-t-use-UTF-8-quotes.-Ever.patch, build/gcc7/patches/0005-Implement-fstrict-calling-conventions.patch, build/gcc7/patches/0006-allow-the-global-disabling-of-function-cloning.patch, build/gcc7/patches/0007-strict-cc2-check-that-disabling-function-cloning-pre.patch, build/gcc7/patches/0008-sol2-enable-full-__cxa_atexit-support.patch, build/gcc7/patches/0009-sol2-Use-appropriate-values-objects-for-the-various-.patch, build/gcc7/patches/0010-i386-Save-integer-passed-arguments-to-the-stack-to-a.patch, build/gcc7/patches/0011-16-update-cmn_err-format-specifier.patch, build/gcc7/patches/0012-19-cmn_err-b-conversion-should-accept-0-flag.patch, build/gcc7/patches/0013-We-never-want-to-omit-the-frame-pointer-regardless-o.patch, build/gcc7/patches/0014-libstdc-v3-illumos-and-Solaris-haven-t-needed-lrt-in.patch, build/gcc7/patches/0015-libgo-libelf-on-illumos-doesn-t-support-largefile.patch, build/gcc7/patches/0016-libgcc-unwind.map-should-be-v2-style.patch, build/gcc7/patches/0017-libpthread-is-a-filter-in-illumos-all-functionality-.patch, build/gcc7/patches/0018-i386-Fix-grammar-of-msave-args-usage-message.patch, build/gcc7/patches/0019-OOCE-Adjust-default-library-paths-for-OmniOS.patch, build/gcc7/patches/0020-tests-x86_64-pro_and_epilogue-RTL-can-t-work-with-ms.patch, build/gcc7/patches/0021-i386-don-t-assert-the-FP-is-valid-during-epilogue-ad.patch, build/gcc7/patches/0022-gcc.target-i386-retarg-skip-if-msave-args.patch, build/gcc7/patches/0023-i386-use-correct-error-message-about-msave-args-and-.patch, build/gcc7/patches/0024-gcc.target-i386-skip-16bit-tests-when-msave-args.patch, build/gcc7/patches/0025-i386-use-the-new-style-retpoline-thunk-names-for-ext.patch, build/gcc7/patches/0026-Use-GNU-backends-for-gcc-ar-nm-ranlib.patch, build/gcc7/patches/series
gcc7: use the new-style retpoline thunk names for external thunks (r151030)
=> gcc7: use the new-style retpoline thunk names for external thunks (r151030)

build/coreutils/build.sh, build/coreutils/local.mog, build/coreutils/patches/ln-port-to-platforms-lacking-O_DIRECTORY.patch, build/coreutils/patches/ln-s-catch-EINVAL.patch, build/coreutils/patches/series, build/coreutils/patches/set-permission.c.patch, build/coreutils/patches/stdbuf.c.patch, build/coreutils/patches/tests_df_no-mtab-status.sh.patch, build/coreutils/testsuite.log, lib/functions.sh
and switch to 64-bit binaries.
stdbuf works with both 32-bit and 64-bit targets:
```
% stdbuf -oL /usr/bin/amd64/ls
build.log      build.sh       patches        tmp
build.log.1    local.mog      testsuite.log
```
```
% stdbuf -oL /usr/bin/ls
build.log      build.sh       patches        tmp
build.log.1    local.mog      testsuite.log
```
=> coreutils: fix bugs in GNU ln

build/libgmp/build.sh, build/libgmp/testsuite.log
gmp: Do not rely on modern CPU features Enable testsuite
=> gmp: Do not rely on modern CPU features; enable testsuite

build/bind/build.sh
When pkgsrc is installed in `/opt/local`, even if not present in `PATH` some include files are found within that tree by the OmniOS build.
Using the wrong headers and libraries is not correct in general, but in this case I noticed because the `network/dns/bind` package was failing to build with errors like:
```
libtool: compile:  gcc -I/ws/stock/tmp/bind-9.11.9/bind-9.11.9 -I../.. -I. -I../../lib/dns -Iinclude -I/ws/stock/tmp/bind-9.11.9/bind-9.11.9/lib/dns/include -I../../lib/dns/include -I/ws/stock/tmp/bind-9.11.9/bind-9.11.9/lib/isc/include -I../../lib/isc -I../../lib/isc/include -I../../lib/isc/unix/include -I../../lib/isc/pthreads/include -I../../lib/isc/x86_32/include -I/usr/include -D_REENTRANT -DUSE_MD5 -DOPENSSL -DGSSAPI -DUSE_ISC_SPNEGO -D_XPG4_2 -D__EXTENSIONS__ -O2 …
```
=> try to avoid configure reaching into /opt/local if pkgsrc is installed

build/gfx-drm/build.sh, build/illumos-kvm/build.sh, lib/config.sh
gfx-drm: switch to using the same gcc version as illumos-omnios (gcc7)
=> kvm/gfx-drm: switch to using the same gcc version as illumos-omnios (gcc7)

build/bhyve-fw/build.sh, lib/functions.sh
This adds the new 2019 firmware images as part of the bhyve/firmware package but tagged as beta until more testing is performed.
```
% pkg contents -g ../_repo system/bhyve/firmware
PATH
usr/share/bhyve
usr/share/bhyve/firmware
usr/share/bhyve/firmware/BHYVE.fd
usr/share/bhyve/firmware/BHYVE_CSM.fd
usr/share/bhyve/firmware/BHYVE_DEBUG-beta.fd
usr/share/bhyve/firmware/BHYVE_DEBUG.fd
usr/share/bhyve/firmware/BHYVE_DEBUG_CSM-beta.fd
usr/share/bhyve/firmware/BHYVE_DEBUG_CSM.fd
usr/share/bhyve/firmware/BHYVE_RELEASE-beta.fd
usr/share/bhyve/firmware/BHYVE_RELEASE.fd
usr/share/bhyve/firmware/BHYVE_RELEASE_CSM-beta.fd
usr/share/bhyve/firmware/BHYVE_RELEASE_CSM.fd
```
=> Add beta bhyve firmware

build/urxvt/build.sh
This is currently going through review to be added to illumos-gate for the system libcurses but that won't be backported to r151030. For this release, deliver both files from this package.
=> Also ship rxvt-unicode terminfo for libcurses (r151030)

build/dma/build.sh
(after 11680 is integrated, which should be today (2019/09/16)
=> OmniOS now has reallocf(3C)

build/dbus/build.sh
Otherwise the dbus and hal services fail if you `onu` from an OmniOS installation to illumos-gate.
Once @andy-js integrates the change to build 64-bit perl modules in gate, the onu-from-omnios experience should be much better.
=> Do not enable inotify support in dbus

build/urxvt/build.sh
If `11669 terminfo could know aobut rxvt-unicode` ever lands, we will have to revert this but let's get it in ready for r151032.
=> Also ship unicode-rxvt for curses

build/urxvt/build.sh
No longer ship rxvt-unicode for illumos curses (r151030)
=> No longer ship rxvt-unicode for illumos curses (r151030)

build/python35/local.mog, build/python37/local.mog
Problem reported by @ptribble
Fix confirmed in updated package:
```
r151032% pkg mediator -a python
MEDIATOR VER. SRC. VERSION IMPL. SRC. IMPLEMENTATION
python   vendor    2       vendor
r151032% pfexec pkg update python-35
r151032% pkg mediator -a python
MEDIATOR VER. SRC. VERSION IMPL. SRC. IMPLEMENTATION
python   vendor    2       vendor
python   system    3       system
r151032% readlink /usr/bin/python
python2
r151032% pfexec pkg set-mediator -V 3 python
r151032% readlink /usr/bin/python
python3
```
=> Fix missing mediated link for /usr/bin/python -> python3

build/gcc44/build.sh, build/gcc7/build.sh, build/gcc8/build.sh, build/gcc9/build.sh
This problem was introduced during the recent work to move userland up to
gcc 9 which produces 64-bit binaries by default. As part of that, an explicit
"-m32" was added to the 32-bit CFLAGS and other environment variables since
the old configuration where this was just omitted for the 32-bit case now
resulted in 64-bit binaries being created.
gcc is built in a single configure/make pass and it generates both 32 and
64-bit components along the way. To make this work properly we need to
make sure that none of -m32 or -m64 are passed into environment variables
used by configure.
Unsetting CFLAGS had the unforseen effect of causing the compilers to be
build without optimisation, resulting in a significant performance penalty
when compiling code. For example, the illumos-omnios build time …
=> gcc compilers are not being built with optimisation

build/gcc44/patches/64bit.patch, build/gcc44/patches/series
Now that GNU binutils targets 64-bit by default, gcc needs to explicitly pass --32 to the assembler.
=> Now that GNU binutils targets 64-bit by default, gcc needs to explicitly pass --32 to the assembler.

build/open-vm-tools/patches/gnu-ld.patch, build/open-vm-tools/patches/nicInfo.patch, build/open-vm-tools/patches/plugindir.patch, build/open-vm-tools/patches/series
=> open-vm-tools wrongly looks for plugins in amd64/ subdirectory

build/gcc7/build.sh, build/gcc7/patches/0002-compare_tests-Use-nawk-1-on-illumos-since-awk-1-is-o.patch, build/gcc7/patches/0003-gcc-enable-the-.eh_frame-based-unwinder.patch, build/gcc7/patches/0004-intl-Don-t-use-UTF-8-quotes.-Ever.patch, build/gcc7/patches/0005-Implement-fstrict-calling-conventions.patch, build/gcc7/patches/0006-allow-the-global-disabling-of-function-cloning.patch, build/gcc7/patches/0007-strict-cc2-check-that-disabling-function-cloning-pre.patch, build/gcc7/patches/0008-sol2-enable-full-__cxa_atexit-support.patch, build/gcc7/patches/0009-sol2-Use-appropriate-values-objects-for-the-various-.patch, build/gcc7/patches/0010-i386-Save-integer-passed-arguments-to-the-stack-to-a.patch, build/gcc7/patches/0011-16-update-cmn_err-format-specifier.patch, build/gcc7/patches/0012-19-cmn_err-b-conversion-should-accept-0-flag.patch, build/gcc7/patches/0013-We-never-want-to-omit-the-frame-pointer-regardless-o.patch, build/gcc7/patches/0014-libstdc-v3-illumos-and-Solaris-haven-t-needed-lrt-in.patch, build/gcc7/patches/0015-libgo-libelf-on-illumos-doesn-t-support-largefile.patch, build/gcc7/patches/0016-libgcc-unwind.map-should-be-v2-style.patch, build/gcc7/patches/0017-libpthread-is-a-filter-in-illumos-all-functionality-.patch, build/gcc7/patches/0018-i386-Fix-grammar-of-msave-args-usage-message.patch, build/gcc7/patches/0019-OOCE-Adjust-default-library-paths-for-OmniOS.patch, build/gcc7/patches/0020-tests-x86_64-pro_and_epilogue-RTL-can-t-work-with-ms.patch, build/gcc7/patches/0021-i386-don-t-assert-the-FP-is-valid-during-epilogue-ad.patch, build/gcc7/patches/0022-gcc.target-i386-retarg-skip-if-msave-args.patch, build/gcc7/patches/0023-i386-use-correct-error-message-about-msave-args-and-.patch, build/gcc7/patches/0024-gcc.target-i386-skip-16bit-tests-when-msave-args.patch, build/gcc7/patches/0025-i386-use-the-new-style-retpoline-thunk-names-for-ext.patch, build/gcc7/patches/0026-Use-GNU-backends-for-gcc-ar-nm-ranlib.patch, build/gcc7/patches/0027-gcc-configure-must-call-gas-with-32-for-32-bit.patch, build/gcc7/testsuite.log, doc/packages.md
In addition to comparing the testsuite results with the previous version, I have also done an illumos build with this new version, onu'd and compared CTF data with one built with 7.4.
=> gcc7: update to 7.5.0

lib/functions.sh
It could be that some of the hardlinks are dropped during manifest processing so we are currently testing too early.
=> Check hardlinks based on final manifest

build/obsolete/library-sunpro.p5m, build/sunpro/build.sh, build/sunpro/local.mog, doc/baseline
In order to support any binaries which were built in the past with studio; they may still have dependencies on these.
=> Re-introduce sunpro package

build/buildctl, lib/functions.sh
This would have prevented the recent problem with sunpro...
```
% ./buildctl build sunpro
===== Build started at Thu Jan 30 11:38:32 UTC 2020 =====
***
*** Building sunpro
***
--- sunpro -> system/library/c++/sunpro
Found a manifest file. Preparing it for publishing.
File archive found. Extracting...
Lint engine setup...
Starting lint run...
WARNING pkglint.manifest009.2     pkg.description matches pkg.summary in pkg:/system/library/c++/sunpro@0.5.11,5.11-151033.0
ERROR pkglint.action007           license action in pkg:/system/library/c++/sunpro@0.5.11,5.11-151033.0 has a path attribute, ../SUNWlibC.copyright
----- pkglint failed
An Error occured in the build. Do you wish to continue anyway? (y/n)
```
=> Enforce linting of manifest-style packages

build/libxslt/build.sh, lib/functions.sh
I came across a build problem that caused the resulting `python` package to be missing the shared library that provides the `select` extension, breaking pkg:
```
r151034% pkg list -u
Traceback (most recent call last):
File "/usr/bin/pkg", line 75, in <module>
import socket
File "/usr/lib/python3.7/socket.py", line 52, in <module>
import os, sys, io, selectors
File "/usr/lib/python3.7/selectors.py", line 12, in <module>
import select
ModuleNotFoundError: No module named 'select'
```
`select` failed to build for some reason, most likely a race. I've never seen this before in any build of the python package.
```
building 'select' extension
gcc -m64 -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -O3 -Wall -O2 -fno-aggressive-loop-optimizations -m64 -D_REENTRANT -std=c99 -Wextra …
```
=> Add explicit checks for errors during build

lib/functions.sh
Occasionally, one sees:
ln: cannot create .../_build/tools/gcc: File exists
[3] gcc link
[3] Unable to run build.sh
This is caused by a race between different parallel build threads attempting
to link the appropriate version of gcc into $TMPDIR/tools/
This isn't actually necessary because the path to the correct gcc is already
prepended to PATH in set_gccver.
=> linking gcc to tools/ is racy

build/openjdk8/patches/ldflags-pie.patch, build/openjdk8/patches/series
Unfortunately the previous openjdk update was incomplete and the build fails due to the attempted use of `-pie` with illumos gcc.
```
% java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-omnios-151033-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```
=> openjdk8: Fix build

build/curl/build.sh, build/curl/local.mog, build/git/build.sh
In the past, curl used to ship architecture-dependent header files so omnios
delivered two sets, `/usr/include/curl/` and `/usr/include/amd64/curl/`
In 2017, curl switched to using a single set of header files; the second
set is now redundant.
Fixes #1845, reported by @v-a-b
=> Drop duplicate curl header files

build/gcc-runtime/build-runtime++.sh, build/gcc-runtime/build-runtime.sh
Reported by @alarcher
After this change, I rebuilt openssh and saw that the dependency changed as expected:
```diff
-depend type=require fmri=pkg:/system/library/g++-runtime
+depend type=require fmri=pkg:/system/library/gcc-runtime
```
=> libssp is in the wrong runtime package

build/bhyve-fw/build.sh, build/bhyve-fw/local.mog, doc/licences, tools/licence
This updates the UEFI bhyve firmware to the latest freebsd 202005 branch but also switches to using the uefi-edk2 releases from https://github.com/omniosorg/uefi-edk2, and the common build script which is held there. This simplifies the firmware build script significantly.
I also changed the build so that two branches are built in parallel, speeding up the package build.
=> Update bhyve firmware

build/release/notices.mog
A lot of files that we ship with OmniOS include a header that directs a user at `/usr/src/OPENSOLARIS.LICENSE`, for example the default crontab:
```
bloody% pfexec crontab -l
#ident  "%Z%%M% %I%     %E% SMI"
#
#
#
#
...
```
We should put a copy of the CDDL at that location.
=> Ship CDDL as /usr/src/OPENSOLARIS.LICENSE [sic]

build/readline/build.sh, build/readline/patches-6/link-ltermcap.patch, build/readline/patches-6/series, build/readline/patches-7/link-ltermcap.patch, build/readline/patches-7/series, build/readline/patches/README, build/readline/patches/link-ltermcap.patch, build/readline/patches/readline80-001, build/readline/patches/readline80-002, build/readline/patches/readline80-003, build/readline/patches/readline80-004, build/readline/patches/series
Reported by @ptrrkssn
This is a similar fix to the one in OpenIndiana, except they unnecessarily link libtermcap against libhistory too.
I installed this update and tested the core utilities that use libreadlin such as bash, gawk, sqlite3.
=> readline: add patches + fix linkage

build/illumos/build.sh
`illumos/build.sh -f ctf` is failing with:
```
pkgmerge: The following pattern(s) did not match any packages in any of the specified repositories for publisher omnios:
driver/graphics/agpgart
driver/graphics/drm
```
=> illumos build.cf must skip gfx-drm too

build/libxslt/build.sh, build/mozilla-nss-nspr/files/nspr.pc, build/openssl/build.sh, build/openssl/patches/libs.patch, build/openssl/testsuite.log, build/xz/patches/pthread.diff, lib/config.sh, lib/functions.sh
The OmniOS gcc these days does not automatically add `-lpthread` for threaded applications.
These patches can be simplified.
=> Adjust pthread library patches for newer gcc behaviour

build/entire/entire.pkg, build/jeos/omnios-userland.pkg, build/words/build.sh, build/words/local.mog, doc/baseline
The current version from illumos-gate has not been updated much over the years. This replaces it with a more complete list built from the GNU aspell dictionaries. An small set of initial languages is included and `/usr/share/lib/dict/words` is a mediated link which defaults to american-english.
=> Deliver more complete /usr/dict/words

build/system/files/system
Fixes #1990 - see that issue for analysis and details of why this is no longer required. Thanks @Leftwing
=> Remove APIC Timer Preferred Mode workaround

build/entire/entire.pkg, build/glib/build.sh, build/glib/patches/libsocket.patch, build/glib/patches/no_inotify.patch, build/glib/testsuite.log, build/jeos/omnios-userland.pkg, doc/packages.md
I tested that an illumos-omnios build was clean with this upgraded glib.
=> glib2: update to 2.66.0

build/openjdk8/jrefinal.mog, build/openjdk8/local.mog, doc/packages.md
stop using `openjdk8` as default if `openjdk11` is installed
=> openjdk8: drop mediator-priority set to vendor

build/gcc10/patches/bug_95189_builtin_memcmp.patch, build/gcc10/patches/series
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95189
Fixes a regression in gcc10
Test program:
```C
#include <string.h>
#include <stdio.h>
static const float z[1] = {0};
int f(float x) { return memcmp(&x, z, sizeof(x)); }
int
main() {
printf("f = %d\n", f(1));
}
```
Before:
```
bloody% gcc -O1 -o a a.c
bloody% ./a
f = 128
bloody% gcc -O2 -o a a.c
bloody% ./a
f = 0
```
After:
```
bloody% gcc -O1 -o a a.c
bloody% ./a
f = 128
bloody% gcc -O2 -o a a.c
bloody% ./a
f = 128
```
=> gcc10: Fix problem with builtin memcmp()

build/rsyslog/build.sh
These are compatibility functions provided for lx but not perfect emulation and rsyslog can use native features instead.
Also do not ship the klog module, it is not useful on OmniOS.
=> rsyslog should not use epoll() or inotify()

build/zstd/build.sh, doc/packages.md
Due to hotfix for fixing 'wrong alignment of an internal buffer'
=> zstd: update to 1.4.8

build/openssh/README, build/python39/patches/gid-convert.patch, build/python39/patches/series, build/release/files/COPYRIGHT, build/release/release.mog
See https://github.com/python/cpython/pull/23762
It is in the process of being back-ported to python 3.9 so we should be able to drop this patch in the next update.
=> Python 3.9 - use correct type for gid

build/openjdk11/build.sh, build/openjdk11/local.mog, build/openjdk11/patches/fontpath.patch, build/openjdk11/patches/series, build/openjdk11/test/Fonts.java
OpenJDK11 needs to bundle core fonts (r151036)
=> OpenJDK11 needs to bundle core fonts (r151036)

build/autoconf/build.sh, build/autoconf/testsuite.log, build/entire/entire.pkg, build/glib/build.sh, build/jeos/omnios-userland.pkg, build/meta/omnios-build-tools.p5m, build/python39/README, build/python39/cffi/build.sh, build/python39/cryptography/build.sh, build/python39/jaraco/build.sh, build/python39/more-itertools/build.sh, build/python39/orjson/build.sh, build/python39/pip/build.sh, build/python39/pytz/build.sh, build/python39/semantic-version/build.sh, build/python39/semantic-version/local.mog, build/python39/setuptools-rust/build.sh, build/python39/setuptools-rust/local.mog, build/python39/setuptools/build.sh, doc/baseline, doc/licences, doc/packages.md
The new `cryptography` module includes rust components, so brings in a requirement for `setuptools-rust`
=> Core package updates

build/python35/patches/CVE-2021-3177.patch
Python 3.5 _ctype module broken (r151030)
=> Python 3.5 _ctypes module broken (r151030)

build/bhyve-fw/build.sh
Update bhyve firmware to the new upstream stable202102 tag
=> Update bhyve firmware to the new upstream stable202102 tag

build/openssh/patches/CVE-2021-28041.patch, build/openssh/patches/series
openssh: fix for CVE-2021-28041 (r151034)
=> openssh: fix for CVE-2021-28041 (r151034)

build/openssh/patches/CVE-2021-28041.patch, build/openssh/patches/series
openssh: fix for CVE-2021-28041 (r151036)
=> openssh: fix for CVE-2021-28041 (r151036)

build/gcc44/patches/pch1.patch, build/gcc44/patches/pch2.patch, build/gcc44/patches/series
This manifests occasionally in a full userland build as something like this
in the build log. With these patches from upstream I have not been able to replicate it.
```
xgcc: Internal error: Segmentation Fault (program cc1plus)
Please submit a full bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
gmake[2]: *** [Makefile:1513: i386-pc-solaris2.11/bits/stdtr1c++.h.gch/O2g.gch] Error 1
```
```
Loading modules: [ libc.so.1 ld.so.1 ]
> ::status
debugging core file of cc1plus (32-bit) from bloody
file: /data/omnios-build/omniosorg/bloody/_build/gcc-4.4.4/gcc-gcc-4.4.4-il-4/host-i386-pc-solaris2.11/gcc/cc1plus
initial argv: /data/omnios-build/omniosorg/bloody/_build/gcc-4.4.4/gcc-gcc-4.4.4-il-4/host-i3
threading model: native threads
status: process terminated by SIGSEGV …
```
=> gcc4 PCH generation sporadically crashes

build/ntpsec/build.sh
Fixes https://github.com/omniosorg/omnios-build/issues/2411
Became broken in version 1.2.1 after upstream change: https://github.com/ntpsec/ntpsec/commit/2c81d1cba0ccf59593d2c154a099fa1e766838ac
=> ntpsec python libraries installed in wrong place

build/bhyve-fw/local.mog
With two licences in this package with the same name but different content, `pkg verify` persistently shows:
```
bloody% pkg verify bhyve/firmware
PACKAGE                                                                 STATUS
pkg://omnios/system/bhyve/firmware                                       ERROR
license: BSD-2-Clause-Patent
ERROR: Hash: 'a5b1a4b5fa7e60af4de6df861c0b631058f418d6fdb189fed6dae59e7380484e' should be 'b3b3c895f7bb88d94a8cf991f70e12c1e17d8c801a2b8e5c304b7375ce2bcd4c'
```
=> bhyve-fw: resolve licence checksum conflict

build/mozilla-nss-nspr/build.sh, build/mozilla-nss-nspr/patches/nss-modernize.patch, build/mozilla-nss-nspr/patches/pkcs11v3.patch, build/mozilla-nss-nspr/patches/shadowing.patch, doc/packages.md
Updating these packages causes the illumos build to fail. 
https://www.illumos.org/issues/13930
Once this is integrated to gate and illumos-omnios, this can be re-tested and merged.
=> nss/nspr - update to 3.68/4.32

build/p7zip/patches/gcc11.patch, build/p7zip/patches/getpassphrase.patch, build/p7zip/patches/series, build/p7zip/testsuite.log
fixes: https://github.com/omniosorg/omnios-build/issues/2457
=> fix p7zip truncates password to 8 chars

build/chrony/local.mog, build/entire/entire.pkg
This affects fresh installations only. Anyone upgrading keeps `ntpsec`.
=> Switch default time sync service to chrony

build/openssh/patches/CVE-2021-41617.patch, build/openssh/patches/series
OpenSSH: patch CVE-2021-41617.patch (r151038)
=> OpenSSH: patch CVE-2021-41617.patch (r151038)

build/openssh/patches/CVE-2021-41617.patch, build/openssh/patches/series
OpenSSH: patch CVE-2021-41617.patch (r151036)
=> OpenSSH: patch CVE-2021-41617.patch (r151036)

build/openssh/patches/CVE-2021-41617.patch, build/openssh/patches/series
OpenSSH: patch CVE-2021-41617.patch (r151030)
=> OpenSSH: patch CVE-2021-41617.patch (r151030)

build/vim/build.sh, build/vim/files/ftdetect/p5m.vim, build/vim/files/ftplugin/p5m.vim, build/vim/files/syntax/p5m.vim, build/vim/local.mog
Here's an example - it obviously depends on your chosen colour scheme and terminal; this is mine.
=> Add new vim syntax plugin for pkg(5) manifest files

lib/functions.sh
and provide option to skip it for testing purposes
(e.g. to keep DWARF alongside CTF)
=> Centralise file stripping

build/buildctl, lib/build.sh, lib/functions.sh
`LIBDIR` is too generic a name to reserve in the build framework. Historically, several package build scripts have used this name and there was a conflict in omnios-extra. This re-syncs core with extra in this regard.
=> Use BLIBDIR for the build's lib/ (like omnios-extra)

build/python39/build.sh
python39 - update from 3.9.8 to 3.9.9 (r151040)
=> python39 - update from 3.9.8 to 3.9.9 (r151040)

build/python39/build.sh
python39 - update from 3.9.8 to 3.9.9 (r151038)
=> python39 - update from 3.9.8 to 3.9.9 (r151038)

build/bhyve-fw/build.sh
This is following the same change in FreeBSD, updating the UEFI ROM from stable202102 to stable202111.
=> bhyve-fw: update to upstream edk2-stable202111

build/python310/setuptools/build.sh, doc/packages.md, lib/functions.sh
With the latest version of setuptools, some legacy builds ends up with modules thinking they have a version number of 0.0.0.
When projects ship both, prefer the newer build system.
=> Prefer PEP518 python builds

build/curl/patches/openssl-cn-bug.patch, build/curl/patches/series
Fix a regression in curl 7.82.0 which causes pkg test suite failures, see
https://github.com/curl/curl/issues/8559
https://github.com/curl/curl/issues/8582
=> curl: Fix regression in 7.82.0

build/python39/build.sh
python39 - update from 3.9.11 to 3.9.12 (r151038)
=> python39 - update from 3.9.11 to 3.9.12 (r151038)

build/python39/build.sh
python39 - update from 3.9.11 to 3.9.12 (r151040)
=> python39 - update from 3.9.11 to 3.9.12 (r151040)

build/openjdk11/build.sh, build/openjdk17/build.sh, doc/packages.md
deferring `openjdk8` update since `-ga` tag is not there, yet.
=> openjdk updates

build/python39/build.sh, build/python39/patches/enable-ossaudiodev.patch, build/python39/patches/mod-posix-sched_priority.patch, build/python39/patches/revert-makedirs.patch
python39 - update from 3.9.12 to 3.9.13 (r151040)
=> python39 - update from 3.9.12 to 3.9.13 (r151040)

build/python39/build.sh, build/python39/patches/enable-ossaudiodev.patch, build/python39/patches/mod-posix-sched_priority.patch, build/python39/patches/revert-makedirs.patch
python39 - update from 3.9.12 to 3.9.13 (r151038)
=> python39 - update from 3.9.12 to 3.9.13 (r151038)

build/python310/build.sh, build/python310/patches/enable-ossaudiodev.patch, build/python310/patches/mod-socket-xpg6.patch, build/python310/patches/module-dlpi.patch, build/python310/patches/module-priv-rbac.patch, build/python310/patches/module-ucred.patch, build/python310/patches/setup.patch, build/python310/patches/test-shutil.patch, doc/packages.md
Python testsuite output is unchanged, IPS tests all match baseline.
```
======================================================================
BASELINE MATCH
======================================================================
```
=> python310 - update from 3.10.5 to 3.10.6

build/obsolete/runtime-java-runtime64.p5m, build/obsolete/runtime-java.p5m, doc/baseline
The illumos-gate dtrace test package has a dependency on `runtime/java/runtime64` - to make it easier for people running gate pieces to install or update the dtrace tests, add a renamed package entry for this to OmniOS.
=> Add runtime/java/runtime64 package

build/zlib/patches/CVE-2022-37434-1.patch, build/zlib/patches/CVE-2022-37434-2.patch, build/zlib/patches/series
=> zlib: fix for CVE-2022-37434

build/python39/build.sh, build/python39/patches/module-py_db.patch
python39 - update from 3.9.13 to 3.9.14 (r151040)
=> python39 - update from 3.9.13 to 3.9.14 (r151040)

build/python39/build.sh, build/python39/patches/mod-posix-sched_priority.patch, build/python39/patches/module-py_db.patch
python39 - update from 3.9.14 to 3.9.15 (r151038)
=> python39 - update from 3.9.14 to 3.9.15 (r151038)

build/gcc12/patches/0036-Add-fforce-omit-frame-pointer.patch, build/gcc12/patches/0037-OOCE-Adjust-default-library-paths-for-OmniOS.patch, build/gcc12/patches/series
```
bloody% gcc -o c c.c -fno-omit-frame-pointer
bloody% dis -F test c | sed -n 3,5p
test()
test:      55                 pushq  %rbp
test+0x1:  48 89 e5           movq   %rsp,%rbp
bloody% gcc -o c c.c -fomit-frame-pointer
bloody% dis -F test c | sed -n 3,5p
test()
test:      55                 pushq  %rbp
test+0x1:  48 89 e5           movq   %rsp,%rbp
bloody% gcc -o c c.c -fomit-frame-pointer -fforce-omit-frame-pointer
bloody% dis -F test c | sed -n 3,5p
test()
test:      48 83 ec 08        subq   $0x8,%rsp
test+0x4:  be 02 00 00 00     movl   $0x2,%esi
```
=> gcc12: Add -fforce-omit-frame-pointer

build/socat/patches/fix-socat-tcsetattr.patch, build/socat/patches/series
=> socat fails to restore tty mode on exit

build/gcc7/build.sh
The upstream https://github.com/illumos/gcc/releases/tag/gcc-7.5.0-il-2
tag has just been created. OmniOS already has the patches that are in
the new tag so this just bumps the reported illumos tag version.
=> Update gcc7 illumos version tag

build/gcc10/patches/0038-OOCE-Adjust-default-library-paths-for-OmniOS.patch, build/gcc11/patches/0036-OOCE-Adjust-default-library-paths-for-OmniOS.patch, build/gcc12/patches/0038-OOCE-Adjust-default-library-paths-for-OmniOS.patch, build/gcc7/patches/0033-OOCE-Adjust-default-library-paths-for-OmniOS.patch
The modifications that have been traditionally made to the compiler link
specs are more complicated than they need to be, duplicating flags for the
profiling and non-profiling cases, and passing a redundant -L alongside
a perfectly good -Y P,
=> Simplify compiler link specs.

lib/functions.sh
The `clear_archflags` function is removing the non-arch flags too, resulting
specifically in the gcc compilers being built without the usual flags,
including optimisation.
=> clear_archflags is a little over-zealous

build/perl/build.sh
required for cross building perl 5.36.1
=> aarch64: bump perl-cross version to 1.4.1

build/groff/build.sh, doc/packages.md
Some binaries are missing in new version, but they never worked previously. The updated configure is just now checking for the ghostscript dependency.
```diff
-set name=info.source-url value=https://mirrors.omnios.org/groff/groff-1.22.4.tar.gz
+set name=info.source-url value=https://mirrors.omnios.org/groff/groff-1.23.0.tar.gz
-file path=usr/bin/groffer owner=root group=bin mode=0755
-file path=usr/bin/roff2dvi owner=root group=bin mode=0755
-file path=usr/bin/roff2html owner=root group=bin mode=0755
-file path=usr/bin/roff2pdf owner=root group=bin mode=0755
-file path=usr/bin/roff2ps owner=root group=bin mode=0755
-file path=usr/bin/roff2text owner=root group=bin mode=0755
-file path=usr/bin/roff2x owner=root group=bin mode=0755
...
```
=> groff - update from 1.22.4 to 1.23.0

build/chrony/build.sh
chrony: bump bundled nettle to 3.9.1 (r151044)
=> chrony: bump bundled nettle to 3.9.1 (r151044)

build/chrony/build.sh
chrony: bump bundled nettle to 3.9.1 (r151046)
=> chrony: bump bundled nettle to 3.9.1 (r151046)

build/python39/build.sh
python39 - update from 3.9.17 to 3.9.18 (r151038)
=> python39 - update from 3.9.17 to 3.9.18 (r151038)

build/pkg/build-arch-aarch64.sh
The build side of https://github.com/omniosorg/pkg5/pull/446
=> Use separate python module requirements for aarch64

build/binutils/build-arch-aarch64.sh, build/binutils/local.mog
This depends on https://github.com/richlowe/illumos-gate/pull/41 to
build correctly.
=> aarch64: build gdb as part of binutils

build/curl/build.sh, build/curl/patches/tests.patch, build/curl/testsuite.log
curl - update from 8.3.0 to 8.4.0 (r151038)
=> curl - update from 8.3.0 to 8.4.0 (r151038)

build/openssl/build-3.sh, build/openssl/patches-3/cross-aarch64.patch, build/openssl/patches-3/libs.patch, build/openssl/testsuite-3.log
openssl - update from 3.0.11 to 3.0.12 (r151046)
=> openssl - update from 3.0.11 to 3.0.12 (r151046)

build/openssl/build-3.sh, build/openssl/patches-3/libs.patch
openssl - update from 3.0.11 to 3.0.12 (r151044)
=> openssl - update from 3.0.11 to 3.0.12 (r151044)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046ag (r151046)

build/python311/build.sh, lib/functions.sh
=> When compiling python modules, always force rebuild and timestamp mode

build/python311/build.sh, lib/functions.sh
When compiling python modules, always force rebuild and timestamp mode (r151048)
=> When compiling python modules, always force rebuild and timestamp mode (r151048)

build/python311/build.sh, lib/functions.sh
When compiling python modules, always force rebuild and timestamp mode (r151046)
=> When compiling python modules, always force rebuild and timestamp mode (r151046)

build/python311/local.mog, build/python312/build.sh, build/python312/common.sh, build/python312/local.mog, build/python312/patches/illumos.patch, build/python312/patches/posix_spawn-close_fds-support.patch, build/python312/patches/series
This mostly the updated `illumos.patch` file, but I also fixed some mog entries related to assumptions about where the libraries live, which can be just `usr/lib/` for cross builds.
=> Python 3.12 is incorrectly detecting platform triple

.gitignore, build/buildctl
This allows CI to upload the failure log as part of the results, for easier inspection
=> Store the log from the last failure

build/python312/build.sh, build/python312/patches/series, build/python312/patches/ustack.patch
This is limited due to the changes in python around function stack management, which means that we no longer get a call frame for each python function call. It means that we can only report some of the python stack, but that's still better than none. I might come back to this in the future and improve things.
=> Add limited ustack helper to python 3.12

build/xz/build.sh
Rather than use the release tarball for 5.6.1, switch to the
github-generated one which does not include the autoconf files
and allow the build framework to generate them for us.
=> xz: improve reproducibility by running autogen.sh ourselves

build/readline/patches/README, build/readline/patches/readline82-001, build/readline/patches/readline82-002, build/readline/patches/readline82-003, build/readline/patches/readline82-004, build/readline/patches/readline82-005, build/readline/patches/readline82-006, build/readline/patches/readline82-007, build/readline/patches/readline82-008, build/readline/patches/readline82-009, build/readline/patches/readline82-010, build/readline/patches/series
readline explodes on contact with invalid LC_CTYPE in environment (r151050)
=> Pull in readline 8.2 patches (r151050)

build/readline/build.sh, build/readline/patches/README, build/readline/patches/readline82-001, build/readline/patches/readline82-002, build/readline/patches/readline82-003, build/readline/patches/readline82-004, build/readline/patches/readline82-005, build/readline/patches/readline82-006, build/readline/patches/readline82-007, build/readline/patches/readline82-008, build/readline/patches/readline82-009, build/readline/patches/readline82-010, build/readline/patches/series
readline explodes on contact with invalid LC_CTYPE in environment (r151048)
=> Pull in readline 8.2 patches (r151048)

build/readline/build.sh, build/readline/patches/README, build/readline/patches/readline82-001, build/readline/patches/readline82-002, build/readline/patches/readline82-003, build/readline/patches/readline82-004, build/readline/patches/readline82-005, build/readline/patches/readline82-006, build/readline/patches/readline82-007, build/readline/patches/readline82-008, build/readline/patches/readline82-009, build/readline/patches/readline82-010, build/readline/patches/series
readline explodes on contact with invalid LC_CTYPE in environment (r151046)
=> Pull in readline 8.2 patches (r151046)

build/chrony/files/chrony.xml
This was likely copied from ntpsec which does a one-off time
step before starting the daemon and therefore needs more
time. Chrony should never take this long to start.
=> Chrony startup timeout is excessive

doc/packages.md
Both r46 and r48 have 3.11, r50 has 3.12 so we can drop the old versions and update 3.11 to the version that was recently part of a weekly release.
=> Update python versions

build/coreutils/build.sh, build/coreutils/patches/set-permission.c.patch, build/coreutils/patches/who.c.patch, build/coreutils/testsuite.log, doc/packages.md
The biggest difference in the testsuite is that the gnulib tests are no longer run, which seems fine.
There is also a failing `numfmt` test which is that padding is lost when presenting a padded, delimited, number in the French locale. This seems to be a result of our `mbrtoc32()` function not recognising the delimiter being used.
Padding works fine in the C, and various other locales, and always works without delimiters so I think this is ok, unless we get any problem reports.
=> coreutils - update from 9.4 to 9.5

build/pcre2/build.sh
Retaining 10.39 was unnecessarily cautious since the interface did not change
=> Stop shipping pcre2 10.39 libraries

build/openssh/build.sh, build/openssh/patches/series, build/openssh/patches/sshsigdie-async-signal-unsafe.patch
openssh: Disable async-signal-unsafe code (r151048)
=> openssh: Disable async-signal-unsafe code (r151048)

build/openssh/build.sh, build/openssh/patches/series, build/openssh/patches/sshsigdie-async-signal-unsafe.patch
openssh: Disable async-signal-unsafe code (r151050)
=> openssh: Disable async-signal-unsafe code (r151050)

build/openssh/build.sh, build/openssh/patches/series, build/openssh/patches/sshsigdie-async-signal-unsafe.patch
openssh: Disable async-signal-unsafe code (r151046)
=> openssh: Disable async-signal-unsafe code (r151046)

build/open-vm-tools/patches/nicInfo.patch
getifaddrs() on illumos does not seem to return AF_PACKET interfaces at all, so vmtoolsd does not report any ip addresses to the hypervisor. Fix this by processing AF_LINK interfaces instead.
While here, fix the build error likely coming from recent pam changes (?) by disabling the warning (will remove if deemed completely unrelated).
=> open-vm-tools: fix ip address reporting

build/epoll-tests/build.sh, build/epoll-tests/files/functional, build/epoll-tests/files/functional.run, build/epoll-tests/local.mog, doc/baseline, doc/packages.md
These don't all pass on illumos currently, but it'll be good to have them to allow for easy pre-release testing and checking for regressions.
```
bloody% /opt/epoll-tests/bin/functional
Test: /opt/epoll-tests/tests/functional/test_create (run as af) [00:00] [PASS]
Test: /opt/epoll-tests/tests/functional/test_depth1 (run as af) [00:00] [PASS]
Test: /opt/epoll-tests/tests/functional/test_depth2 (run as af) [00:00] [FAIL]
Test: /opt/epoll-tests/tests/functional/test_dir (run as af)    [00:00] [PASS]
Test: /opt/epoll-tests/tests/functional/test_errevent (run as af) [00:00] [PASS]
Test: /opt/epoll-tests/tests/functional/test_et (run as af)     [00:00] [PASS]
Test: /opt/epoll-tests/tests/functional/test_eventfd_et (run as af) [00:00] [FAIL]   https://www.illumos.org/issues/16700
Test: …
```
=> Add system/test/epolltest package

lib/functions.sh
Sometimes it's desirable to clone a full repository and this provides a way to do that.
=> Allow cloning full git repositories by specifying depth 0

build/sudo/build.sh, build/sudo/files/_omnios_corefiles, build/sudo/files/_omnios_nopty, build/sudo/local.mog, build/sudo/patches/securepath.patch, build/sudo/patches/series
We have always shipped `/etc/sudoers` this way but sudo 1.9.16 changes things on upgrade if the user has never modified the default file. This change allows us to continue shipping without this setting being enabled, for least surprise/breakage.
=> sudo: disable secure_path in /etc/sudoers by default

build/chrony/files/chrony.xml, build/dbus/files/dbus.xml, build/ipmitool/files/ipmievd.xml, build/isc-dhcp/files/isc-dhcp.xml, build/net-snmp/files/net-snmp.xml, build/ntpsec/files/ntpsec.xml, build/open-vm-tools/files/open-vm-tools.xml, build/openlldp/files/lldpd.xml, build/openssh/files/ssh.xml, build/rsyslog/files/rsyslog.xml, build/trousers/files/tcsd.xml, doc/tidy.conf, tools/tidy-manifests
Split into three commits to make it easier to review, I have updated services that were previously starting in `/root` so that they start in `/`. We also need [illumos 16806](https://www.illumos.org/issues/16806) for a complete solution.
The last commit is the result of running `tidy-manifests` on all SMF manifests (which also checks they're still valid using `svccfg validate`). That should all just be whitespace/quote style changes.
=> Services that start as root should start in /

build/python311/meson/build.sh, build/python311/meson/local.mog, build/python311/meson/patches/compiler_def_static_linker.patch
more recent `cairo` requires more recent `meson`.
=> meson-311: update to 1.5.1 (r151046)

build/openssl/build-3.sh, build/openssl/testsuite-3.log, doc/packages.md
openssl 3.4 is supported until 22nd October 2026 and has the longest support date of any openssl release; the LTS expires earlier, so 3.4 may become the next LTS, I don't know.
I updated the installed openssl-3 package on a bloody system and checked that everything appeared to work properly, then did a full omnios build with this newer version in place that was successful. I also updated to that newly rebuilt version and observed no problems. This is in line with my expectations as 3.4 is supposed to be largely compatible with 3.3.
=> openssl-3 - update from 3.3.2 to 3.4.0

build/pkg/build-arch-aarch64.sh, build/pkg/build.sh
To go along with the changes in https://github.com/omniosorg/pkg5/pull/501, a couple of things need reshuffling here, in particular with the cross build.
=> Updates to pkg5 build following reshuffle

build/openssl/build-3.sh
It's about time we stopped building OpenSSL 3 with support for the legacy
1.1.1 API enabled by default.
`16911 illumos-gate should select OpenSSL 1.x API where needed`
in gate has made this possible.
It's still possible for individual applications to opt in to the old API via
```
CPPFLAGS+=" -DOPENSSL_API_COMPAT=10101"
```
but there are no packages in omnios-build that require this.
=> Stop building OpenSSL 3 against API 1.1.1

build/sccs/build.sh, build/sccs/local.mog
=> sccs: fix build with gcc14

build/python311/build.sh
Fixes https://github.com/omniosorg/omnios-build/issues/3770
=> python 3.11 depends on latest expat library

build/binutils/build-arch-aarch64.sh, build/gcc-runtime/build-runtime++.sh, build/gcc-runtime/build-runtime.sh, build/gcc-runtime/common.sh, build/gcc14/build-arch-aarch64.sh, build/gcc14/build.sh, build/illumos/files/aarch64.env, build/meta/build-essential.p5m, build/openssh/patches/0013-Solaris-Auditing-support.patch, build/openssh/patches/gcc14.patch, build/openssh/patches/series.aarch64, doc/baseline.aarch64, doc/pkglist.aarch64
also depends on https://github.com/omniosorg/omnios-extra/pull/1558
cc @richlowe
=> aarch64: move to using gcc14

build/rsync/build.sh, build/rsync/patches/gcc14.patch, build/rsync/testsuite.log
rsync - update from 3.3.0 to 3.4.0 (r151052)
=> rsync - update from 3.3.0 to 3.4.0 (r151052)

lib/config.sh
Following "17091 Use DWARFv4 by default" in gate, let us do the same in userland
=> Use DWARFv4 by default

build/openssh/build.sh, build/openssh/patches/CVE-2025-26465.patch, build/openssh/patches/CVE-2025-26466.patch, build/openssh/patches/series, build/openssh/patches/series.aarch64, build/openssh/testsuite.log
openssh: Fixes for CVE-2025-2646[56] (r151046)
=> openssh: Fixes for CVE-2025-2646[56] (r151046)

build/aarch64-fw/build.sh, build/aarch64-fw/local.mog, build/entire/entire-aarch64.pkg, build/gfx-drm/build.sh, build/kayak-kernel/build.sh, build/kayak/build.sh, doc/baseline.aarch64, doc/pkglist.aarch64, lib/functions.sh
This delivery firmware files to `/usr/share/firmare/<arch>` on aarch64 so that `bootadm` can keep them up-to-date in the boot partition.
=> Add aarch64 firmware package

build/screen/build.sh, build/screen/patches/0001-attacher.c-prevent-temporary-0666-mode-on-PTYs-to-fi.patch, build/screen/patches/0002-Avoid-file-existence-test-information-leaks-to-fix-C.patch, build/screen/patches/0003-socket.c-don-t-send-signals-with-root-privileges-to-.patch, build/screen/patches/series
screen: fixes for CVE-2025-4680[245] (r151054)
=> screen: fixes for CVE-2025-4680[245] (r151054)

build/buildctl
There are situations when you want to define a list of packages to build without changing doc/baseline, or for example, use a non-standard path.
=> buildctl: add ability to use custom pkglist and baseline

build/xz/build.sh
The recent update to gettext has pulled in
https://github.com/autotools-mirror/gettext/commit/ec07a48b8fd1939b62d03
which rejects the illumos libc gettext implementation in favour of that
within libintl.so, which requires the post-SUSv3 iconv prototypes.
=> Build xz with XPG6
