omniosorg/omnios-build

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032ai (r151032)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030bi (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151034i (r151034)

build/curl/build.sh, build/curl/testsuite.log, build/mercurial/build.sh, build/mozilla-nss-nspr/build.sh, build/nasm/build.sh, build/python37/idna/build.sh, build/python37/importlib-metadata/build.sh, build/python37/more-itertools/build.sh, doc/packages.md
pkg5 test suite matches baseline
Did a test bhyve firmware build with the updated `nasm`
=> omnios-build Package updates

build/glib/build.sh, doc/packages.md
(testsuite results are unchanged)
=> glib: update to 2.64.4

build/illumos/build.sh
Add /usr/platform packages to ctf set (r151034)
=> Add /usr/platform packages to ctf set (r151034)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151034l

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030bl (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032al (r151032)

build/openssl/patches/libs.patch
Simplify library patch for newer gcc behaviour (r151030)
=> Simplify library patch for newer gcc behaviour (r151030)

build/openssl/patches/libs.patch
Simplify library patch for newer gcc behaviour (r151032)
=> Simplify library patch for newer gcc behaviour (r151032)

build/openssl/patches/libs.patch
Simplify library patch for newer gcc behaviour (r151034)
=> Simplify library patch for newer gcc behaviour (r151034)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151034m (r151034)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032am (r151032)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030bm (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030bn (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032an (r151032)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151034n (r151034)

build/bison/build.sh, build/bison/testsuite.log, build/mercurial/build.sh, doc/packages.md
=> mercurial: update to 5.5

build/python27/patches/CVE-2020-20907.patch, build/python27/patches/CVE-2020-8492.patch, build/python27/patches/series, build/python27/testsuite-32.log, build/python27/testsuite.log
=> Python2: CVE fixes (r151030)

build/python27/patches/CVE-2020-20907.patch, build/python27/patches/CVE-2020-8492.patch, build/python27/patches/series, build/python27/testsuite-32.log, build/python27/testsuite.log
=> Python2: CVE fixes (r151032)

build/python27/patches/CVE-2020-20907.patch, build/python27/patches/CVE-2020-8492.patch, build/python27/patches/series, build/python27/testsuite-32.log, build/python27/testsuite.log
=> Python2: CVE fixes (r151034)

build/python37/build.sh, build/python37/patches/07-closerange.patch, build/python37/patches/20-test_fixes.patch, build/python37/patches/CVE-2020-14422.patch, build/python37/patches/CVE-2020-20907.patch, build/python37/patches/regrtest-processgroup.patch, build/python37/patches/series
python3: update to 3.7.8 (r151034)
=> python3: update to 3.7.8 (r151034)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151034o (r151034)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032ao (r151032)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030bo (r151030)

build/system/files/system
=> remove disabling deep c-states by default

build/fio/build.sh, build/python37/cffi/build.sh, build/python37/cheroot/build.sh, build/python37/cheroot/local.mog, build/python37/meson/build.sh, build/python37/meson/patches/compiler_def_static_linker.patch, build/python37/setuptools/build.sh, doc/packages.md
pkg5 test-suite:
```
======================================================================
BASELINE MATCH
======================================================================
```
=> core package and python module updates

build/curl/build.sh, build/curl/testsuite.log, build/glib/build.sh, build/libmpc/build.sh, build/libmpc/local.mog, build/libmpc/testsuite.log, doc/packages.md
=> curl, glib, mpc updates

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151030bq

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151032aq

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151034q

build/unixodbc/build.sh, build/unixodbc/local.mog, build/unixodbc/patches/filterlibs.patch, build/unixodbc/patches/mutex-exit.patch, build/unixodbc/patches/series, doc/packages.md
=> unixodbc: update to 2.3.8

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151034r (r151034)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032ar (r151032)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030br (r151030)

build/brotli/build.sh, build/brotli/local.mog, build/curl/testsuite.log, build/gtar/build.sh, build/gtar/testsuite.log, build/jeos/omnios-userland.pkg, build/meta/omnios-build-tools.p5m, doc/baseline, doc/packages.md
See also https://github.com/omniosorg/omnios-extra/pull/613
=> Add brotli compression library to core

build/bison/build.sh, build/bison/testsuite.log, build/fio/build.sh, build/unixodbc/build.sh, doc/packages.md
=> Core package updates

build/git/build.sh, build/git/files/services, lib/functions.sh, lib/global-transforms.mog
git: Add /etc/inet/services fragment
=> git: Add /etc/inet/services fragment

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030bt (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032at (r151032)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151034t (r151034)

build/bind/build.sh, doc/packages.md
=> bind: update to 9.11.23

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151030bu

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151032au

build/sudo/build.sh, build/sudo/patches/Makefile.in.patch, build/sudo/patches/audit-event.patch, build/sudo/testsuite.log, doc/packages.md
=> sudo: update to 1.9.3

build/openssl/build.sh, build/openssl/testsuite.log, doc/packages.md
=> openssl: update to 1.1.1h

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151034w

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151032aw

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151030bw

build/gcc10/patches/bug_95189_builtin_memcmp.patch, build/gcc10/patches/series
=> gcc10: Fix problem with builtin memcmp() (r151036)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151034y (r151034)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032ay (r151032)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030by (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030bz

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032az

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151034z

build/entire/entire.pkg, build/ntpsec/build.sh, build/ntpsec/local.mog, build/ntpsec/patches/conf.patch, build/ntpsec/patches/mansections.patch, build/ntpsec/patches/pie.patch, build/ntpsec/patches/unneeded_libs.patch, build/ntpsec/testsuite.log, doc/packages.md
=> ntpsec: update to 1.2.0

build/openjdk8/build.sh, build/openjdk8/patches/KPIC.patch, build/openjdk8/patches/ldflags-pie.patch, build/openjdk8/patches/patch-common_autoconf_generated-configure.sh.patch, build/openjdk8/patches/patch-common_autoconf_spec.gmk.in.patch, build/openjdk8/patches/patch-hotspot_make_solaris_makefiles_vm.make.patch, build/openjdk8/patches/patch-hotspot_src_os__cpu_solaris__x86_vm_os__solaris__x86.inline.hpp.patch, build/openjdk8/patches/patch-hotspot_src_os_solaris_proc__saproc.cpp.patch, build/openjdk8/patches/patch-hotspot_src_os_solaris_vm_os__solaris.cpp.patch, build/openjdk8/patches/patch-hotspot_src_share_vm_oops_klass.hpp.patch, build/openjdk8/patches/patch-hotspot_src_share_vm_opto_library__call.cpp.patch, build/openjdk8/patches/patch-hotspot_src_share_vm_runtime_arguments.cpp.patch, build/openjdk8/patches/patch-jdk_make_CompileLaunchers.gmk.patch, build/openjdk8/patches/patch-jdk_make_CreateJars.gmk.patch, build/openjdk8/patches/patch-jdk_make_Images.gmk.patch, build/openjdk8/patches/patch-jdk_make_lib_Awt2dLibraries.gmk.patch, build/openjdk8/patches/patch-jdk_src_solaris_native_java_net_NetworkInterface.c.patch, build/openjdk8/patches/patch-jdk_src_solaris_native_java_net_net__util__md.c.patch, build/openjdk8/patches/patch-jdk_test_java_lang_management_OperatingSystemMXBean_GetSystemLoadAverage.java.patch, build/openjdk8/patches/patch-jdk_test_sun_security_ec_TestEC.java.patch, doc/packages.md
=> openjdk8: update to 1.8.275u1

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030cc (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151034ac (r151034)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151036c (r151036)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151036f (r151036)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151034af (r151034)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030cf (r151030)

build/sudo/build.sh, doc/packages.md
=> sudo: update to 1.9.5p1

build/openjdk11/build.sh, build/openjdk11/local.mog, build/openjdk11/patches/fontpath.patch, build/openjdk11/patches/series, build/openjdk11/test/Fonts.java
OpenJDK11 needs to bundle core fonts
=> OpenJDK11 needs to bundle core fonts

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151036m (r151036)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151034am (r151034)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030cm (r151030)

build/sudo/build.sh, doc/ReleaseNotes.md
sudo: update to 1.9.5p2 (r151036)
=> sudo: update to 1.9.5p2 (r151036)

build/entire/entire.pkg, build/jeos/omnios-userland.pkg, build/sudo/build.sh, doc/ReleaseNotes.md
sudo: update to 1.9.5p2 (r151034)
=> sudo: update to 1.9.5p2 (r151034)

build/sudo/build.sh, doc/packages.md
=> sudo: update to 1.9.5p2

build/screen/patches/CVE-2021-26937.patch, build/screen/patches/series
screen: add patch for CVE-2021-26937 (r151036)
=> screen: add patch for CVE-2021-26937 (r151036)

build/screen/patches/CVE-2021-26937.patch, build/screen/patches/series
screen: add patch for CVE-2021-26937 (r151034)
=> screen: add patch for CVE-2021-26937 (r151034)

build/screen/patches/CVE-2021-26937.patch, build/screen/patches/series
screen: add patch for CVE-2021-26937 (r151030)
=> screen: add patch for CVE-2021-26937 (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030co (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151034ao (r151034)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151036o (r151036)

build/python27/patches/CVE-2021-3177.patch, build/python27/patches/series, build/python39/patches/CVE-2021-3177.patch, build/python39/patches/series
python: fixes for CVE-2021-3177
=> python: fixes for CVE-2021-3177

build/python27/patches/CVE-2021-3177.patch, build/python27/patches/series, build/python35/patches/CVE-2021-3177.patch, build/python35/patches/series
python: fixes for CVE-2021-3177 (r151030)
=> python: fixes for CVE-2021-3177 (r151030)

build/python27/patches/CVE-2021-3177.patch, build/python27/patches/series, build/python37/patches/CVE-2021-3177.patch, build/python37/patches/series
python: fixes for CVE-2021-3177 (r151034)
=> python: fixes for CVE-2021-3177 (r151034)

build/python27/patches/CVE-2021-3177.patch, build/python27/patches/series, build/python37/patches/CVE-2021-3177.patch, build/python37/patches/series
python: fixes for CVE-2021-3177 (r151036)
=> python: fixes for CVE-2021-3177 (r151036)

build/openssl/build.sh
openssl: update to 1.1.1j (r151030)
=> openssl: update to 1.1.1j (r151030)

build/openssl/build.sh
openssl: update to 1.1.1j (r151034)
=> openssl: update to 1.1.1j (r151034)

build/openssl/build.sh
openssl: update to 1.1.1j (r151036)
=> openssl: update to 1.1.1j (r151036)

build/openssl/build.sh, build/openssl/testsuite.log, doc/packages.md
=> openssl: update to 1.1.1j

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030cp (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151034ap (r151034)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151036p (r151036)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030cq (r151030)

build/git/build.sh
git: update to 2.26.3 (r151034)
=> git: update to 2.26.3 (r151034)

build/git/build.sh
git: update to 2.28.1 (r151036)
=> git: update to 2.28.1 (r151036)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151036s (r151036)

build/bison/build.sh, build/bison/testsuite.log, build/fio/build.sh, build/mercurial/build.sh, build/sqlite3/build.sh, build/sudo/build.sh, build/sudo/testsuite.log, doc/packages.md
=> fio: update to 3.26

build/git/build.sh, build/git/testsuite.log, build/sqlite3/build.sh, build/sudo/build.sh, doc/packages.md
=> git: update to 2.31.0

build/mozilla-nss-nspr/build.sh, doc/packages.md
=> nss/nspr: update to 3.63/4.30

build/openssl/build.sh
openssl: update to 1.1.1k (r151036)
=> openssl: update to 1.1.1k (r151036)

build/openssl/build.sh
openssl: update to 1.1.1k (r151034)
=> openssl: update to 1.1.1k (r151034)

build/openssl/build.sh
openssl: update to 1.1.1k (r151030)
=> openssl: update to 1.1.1k (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030cu (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151034au (r151034)

build/expat/build.sh, build/expat/patches/manpage.patch, doc/packages.md
=> expat: update to 2.3.0

build/gcc44/patches/pch1.patch, build/gcc44/patches/pch2.patch, build/gcc44/patches/series
=> gcc4 PCH generation sporadically crashes (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151030cv (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151036v (r151036)

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151034av (r151034)

build/dma/patches/closefrom.patch, build/dma/patches/series
=> dma: use closefrom()

build/dma/patches/closefrom.patch, build/dma/patches/series
dma: use closefrom() (r151036)
=> dma: use closefrom() (r151036)

build/curl/build.sh
curl: update to 7.76.1 (r151038)
=> curl: update to 7.76.1 (r151038)

build/curl/build.sh
curl: update to 7.76.1 (r151036)
=> curl: update to 7.76.1 (r151036)

build/curl/build.sh
curl: update to 7.76.1 (r151034)
=> curl: update to 7.76.1 (r151034)

build/curl/build.sh
curl: update to 7.76.1 (r151030)
=> curl: update to 7.76.1 (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151036x (r151036)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151034ax (r151034)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030cx (r151030)

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
=> curl: update to 7.76.1

build/libxml2/build.sh, build/libxml2/patches/pthread.patch
libxml2: update to 2.9.12 (r151030)
=> libxml2: update to 2.9.12 (r151030)

build/libxml2/build.sh, build/libxml2/patches/pthread.patch
libxml2: update to 2.9.12 (r151036)
=> libxml2: update to 2.9.12 (r151036)

build/libxml2/build.sh, build/libxml2/patches/pthread.patch
libxml2: update to 2.9.12 (r151038)
=> libxml2: update to 2.9.12 (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030dc (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151036ac (r151036)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038c (r151038)

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
curl - update from 7.76.1 to 7.77.0
=> curl - update from 7.76.1 to 7.77.0

build/curl/build.sh
curl - update from 7.76.1 to 7.77.0 (r151038)
=> curl - update from 7.76.1 to 7.77.0 (r151038)

build/curl/build.sh
curl - update from 7.76.1 to 7.77.0 (r151036)
=> curl - update from 7.76.1 to 7.77.0 (r151036)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030dd (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151036ad (r151036)

build/curl/build.sh, build/curl/patches/series, build/curl/patches/ssl23.patch
curl - update from 7.76.1 to 7.77.0 (r151030)
=> curl - update from 7.76.1 to 7.77.0 (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038d (r151038)

build/isc-dhcp/build.sh
isc-dhcp - update from 4.4.2 to 4.4.2-P1 (r151036)
=> isc-dhcp - update from 4.4.2 to 4.4.2-P1 (r151036)

build/isc-dhcp/build.sh
isc-dhcp - update from 4.4.1 to 4.4.2-P1 (r151030)
=> isc-dhcp - update from 4.4.1 to 4.4.2-P1 (r151030)

build/isc-dhcp/build.sh
isc-dhcp - update from 4.4.2 to 4.2.2-P1 (r151038)
=> isc-dhcp - update from 4.4.2 to 4.4.2-P1 (r151038)

build/isc-dhcp/build.sh, build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030dg (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151036ag (r151036)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038g (r151038)

build/open-vm-tools/build.sh, build/open-vm-tools/patches/gnu-ld.patch, build/open-vm-tools/patches/lock.patch, build/open-vm-tools/patches/nicInfo.patch, build/open-vm-tools/patches/plugindir.patch, build/open-vm-tools/patches/unneededlibs.patch, doc/packages.md
open-vm-tools - update from 11.2.5 to 11.3.0
=> open-vm-tools - update from 11.2.5 to 11.3.0

build/python39/build.sh, build/python39/patches/disable_epoll.patch, build/python39/patches/locale-encoding.patch, build/python39/patches/no-zip-in-sys-path.patch, build/python39/patches/test-pkgutil.patch
python39 - update from 3.9.5 to 3.9.6 (r151038)
=> python39 - update from 3.9.5 to 3.9.6 (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038k (r151038)

build/curl/build.sh
curl - update from 7.77.0 to 7.78.0 (r151038)
=> curl - update from 7.77.0 to 7.78.0 (r151038)

build/curl/build.sh
curl - update from 7.77.0 to 7.78.0 (r151036)
=> curl - update from 7.77.0 to 7.78.0 (r151036)

build/curl/build.sh
curl - update from 7.77.0 to 7.78.0 (r151030)
=> curl - update from 7.77.0 to 7.78.0 (r151030)

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
curl - update from 7.77.0 to 7.78.0
=> curl - update from 7.77.0 to 7.78.0

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038l (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151036al (r151036)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030dl (r151030)

build/openssl/build-1.0.sh, build/openssl/build-1.1.sh, build/openssl/build-3.0.sh, build/openssl/patches-3.0/libs.patch, build/openssl/patches-3.0/series, build/openssl/testsuite-3.0.log
beta2 is the first release candidate - still has all tests passing on omnios.
=> openssl 3, update to beta2

build/diffutils/build.sh, build/diffutils/testsuite.log, doc/packages.md
diffutils - update from 3.7 to 3.8
=> diffutils - update from 3.7 to 3.8

build/gcc10/build.sh, build/gcc11/build.sh, build/gcc7/build.sh
=> gcc: use illumos strip

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151038q

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151036aq

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151030dq

build/gcc10/build.sh, build/gcc10/patches/0036-libstdc-must-use-thread-local-errno.patch, build/gcc10/patches/0037-OOCE-Adjust-default-library-paths-for-OmniOS.patch, build/gcc10/patches/series, build/gcc11/build.sh, build/gcc11/patches/0035-libstdc-must-use-thread-local-errno.patch, build/gcc11/patches/0036-OOCE-Adjust-default-library-paths-for-OmniOS.patch, build/gcc11/patches/series, build/gcc7/build.sh, build/gcc7/patches/0031-libstdc-must-use-thread-local-errno.patch, build/gcc7/patches/0032-OOCE-Adjust-default-library-paths-for-OmniOS.patch, build/gcc7/patches/series
See https://github.com/illumos/gcc/issues/45
=> libstdc++ must use thread-local errno

build/python39/build.sh, build/python39/patches/enable-ossaudiodev.patch, build/python39/patches/mod-socket-xpg6.patch, build/python39/patches/module-dlpi.patch, build/python39/patches/module-priv-rbac.patch, build/python39/patches/module-ucred.patch, build/python39/patches/setup.patch, build/python39/patches/test-filecomments.patch, build/python39/patches/test-processgroup.patch, doc/packages.md
pkg5 testsuite baseline matches.
=> python39 - update from 3.9.6 to 3.9.7

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030ds (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151036as (r151036)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038s (r151038)

build/curl/build.sh
curl - update from 7.78.0 to 7.79.0 (r151038)
=> curl - update from 7.78.0 to 7.79.0 (r151038)

build/curl/build.sh
curl - update from 7.78.0 to 7.79.0 (r151036)
=> curl - update from 7.78.0 to 7.79.0 (r151036)

build/curl/build.sh, build/curl/patches/ssl23.patch
curl - update from 7.78.0 to 7.79.0 (r151030)
=> curl - update from 7.78.0 to 7.79.0 (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038t (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151036at (r151036)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030dt (r151030)

build/sudo/build.sh, doc/packages.md
sudo - update from 1.9.8 to 1.9.8p1
=> sudo - update from 1.9.8 to 1.9.8p1

build/nghttp2/build.sh, build/nghttp2/testsuite.log, doc/packages.md
nghttp2 - update from 1.44.0 to 1.45.0
=> nghttp2 - update from 1.44.0 to 1.45.0

build/curl/build.sh
curl - update from 7.79.0 to 7.79.1 (r151036)
=> curl - update from 7.79.0 to 7.79.1 (r151036)

build/curl/build.sh
curl - update from 7.79.0 to 7.79.1 (r151030)
=> curl - update from 7.79.0 to 7.79.1 (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151036au (r151036)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038u (r151038)

build/bison/build.sh, build/bison/testsuite.log, doc/packages.md
bison - update from 3.8.1 to 3.8.2
=> bison - update from 3.8.1 to 3.8.2

build/openssh/build.sh, build/openssh/patches/0002-PAM-Support.patch, build/openssh/patches/0004-Reorganise-man-pages-into-illumos-numbering-adjust-t.patch, build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch, build/openssh/patches/0008-Add-DisableBanner-option.patch, build/openssh/patches/0009-PAM-conversation-fix.patch, build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch, build/openssh/patches/0013-Solaris-Auditing-support.patch, build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch, build/openssh/patches/0016-PAM-setcred-failures.patch, build/openssh/patches/0019-PubKeyPlugin-support.patch, build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch, build/openssh/patches/0028-Compatibility-for-SunSSH_1.5-should-include-old-DH-K.patch, build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch, build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch, build/openssh/patches/revert-dscp.patch, build/openssh/testsuite.log, doc/packages.md
openssh: update from 8.7p1 to 8.8p1
=> openssh: update from 8.7p1 to 8.8p1

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030dv (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151036av (r151036)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038v (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151030dz

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151038z

build/cloud-init/build.sh, doc/packages.md
=> cloudinit: update to 21.4

build/net-snmp/build.sh, build/net-snmp/testsuite.log
fixes https://github.com/omniosorg/omnios-build/issues/2568
=> net-snmp: fix library only builds

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030ec (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038ac (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151040c (r151040)

build/vim/build.sh
=> vim: update to 8.2.3582

build/bash/build.sh, build/bash/patches/bash-5.1-patches/bash51-009, build/bash/patches/bash-5.1-patches/bash51-010, build/bash/patches/bash-5.1-patches/bash51-011, build/bash/patches/bash-5.1-patches/bash51-012, build/bash/patches/series, doc/packages.md
=> bash: update to 5.1.12

build/python39/build.sh, doc/packages.md
python39 - update from 3.9.8 to 3.9.9
=> python39 - update from 3.9.8 to 3.9.9

build/git/build.sh
=> Fix git perl manpages, add bash completions

build/rsync/build.sh, doc/packages.md
xxhash: update from 0.8.0 to 0.8.1
=> xxhash: update from 0.8.0 to 0.8.1

build/buildctl, build/curl/build.sh, build/dbus/local.mog, build/nghttp2/build.sh, build/sudo/local.mog, lib/functions.sh, lib/mog/global-transforms.mog
This updates global-transforms.mog and makes it more consistent with illumos-omnios
A pkgdiff showing the differences in package manifests resulting from this change can be viewed at:
https://gist.github.com/citrus-it/3a5e446437a788c196c78525e9a82346
=> Refactor global-transforms

build/openssl/build.sh
openssl: update to 1.1.1m (r151030)
=> openssl: update to 1.1.1m (r151030)

build/openssl/build-1.1.sh
openssl: update to 1.1.1m (r151038)
=> openssl: update to 1.1.1m (r151038)

build/openssl/build-1.1.sh, build/openssl/build-3.sh, build/openssl/testsuite-1.1.log, build/openssl/testsuite-3.log
openssl: update to 3.0.1/1.1.1m (r151040)
=> openssl: update to 3.0.1/1.1.1m (r151040)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151040g (r151040)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038ag (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030eg (r151030)

build/expat/build.sh, doc/packages.md
expat - update from 2.4.2 to 2.4.3
=> expat - update from 2.4.2 to 2.4.3

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030el (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038al (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151040l (r151040)

build/python310/build.sh, build/python310/patches/disable_epoll.patch, build/python310/patches/locale-encoding.patch, doc/packages.md
pkg tests ran successfully with this new version.
=> Python: Update to 3.10.2

build/bind/build.sh, build/bind/patches/linker_flags.patch, doc/packages.md
bind - update from 9.16.24 to 9.16.25
=> bind - update from 9.16.24 to 9.16.25

build/git/build.sh, doc/packages.md
git - update from 2.35.0 to 2.35.1
=> git - update from 2.35.0 to 2.35.1

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151038an

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151040n

build/expat/build.sh
expat - update from 2.4.3 to 2.4.4 (r151040)
=> expat - update from 2.4.3 to 2.4.4 (r151040)

build/expat/build.sh
expat - update from 2.4.3 to 2.4.4 (r151030)
=> expat - update from 2.4.3 to 2.4.4 (r151030)

build/vim/build.sh
vim: upate from 8.2.3582 to 8.2.4236
=> vim: upate from 8.2.3582 to 8.2.4236

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030eq (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038aq (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151040q (r151040)

build/expat/build.sh, build/libxml2/build.sh
expat - update from 2.4.4 to 2.4.6 (r151040)
=> expat - update from 2.4.4 to 2.4.6 (r151040)

build/expat/build.sh, build/libxml2/build.sh
expat - update from 2.4.4 to 2.4.6 (r151038)
=> expat - update from 2.4.4 to 2.4.6 (r151038)

build/expat/build.sh, build/libxml2/build.sh
expat - update from 2.4.4 to 2.4.6 (r151030)
=> expat - update from 2.4.4 to 2.4.6 (r151030)

build/python27/patches/CVE-2021-3733.patch, build/python27/patches/CVE-2022-0391.patch, build/python27/patches/series
python2.7: add patches for CVE-2021-3733, CVE-2022-0391 (r151040)
=> python2.7: add patches for CVE-2021-3733, CVE-2022-0391 (r151040)

build/python27/patches/CVE-2021-3733.patch, build/python27/patches/CVE-2022-0391.patch, build/python27/patches/series
python2.7: add patches for CVE-2021-3733, CVE-2022-0391 (r151038)
=> python2.7: add patches for CVE-2021-3733, CVE-2022-0391 (r151038)

build/dbus/build.sh, build/dbus/patches/inline.patch, build/dbus/testsuite.log, doc/packages.md
On hold pending further testing with illumos-omnios.
=> dbus: update from 1.12.22 to 1.14.0

build/expat/build.sh
expat - update from 2.4.6 to 2.4.7 (r151040)
=> expat - update from 2.4.6 to 2.4.7 (r151040)

build/expat/build.sh
expat - update from 2.4.6 to 2.4.7 (r151038)
=> expat - update from 2.4.6 to 2.4.7 (r151038)

build/expat/build.sh
expat - update from 2.4.6 to 2.4.7 (r151030)
=> expat - update from 2.4.6 to 2.4.7 (r151030)

build/XML::Parser/build.sh, build/bind/build.sh, build/cloud-init/build.sh, build/coreutils/files/soname.ignore, build/gcc10/files/soname.ignore, build/gcc11/files/soname.ignore, build/gcc7/files/soname.ignore, build/illumos-closed/build.sh, build/illumos-kvm/files/soname.ignore, build/mercurial/build.sh, build/mozilla-nss-nspr/build.sh, build/open-vm-tools/build.sh, build/openjdk11/build.sh, build/openjdk17/build.sh, build/openjdk8/build.sh, build/openssl/files/soname.ignore, build/p7zip/build.sh, build/perl/build.sh, build/python27/build.sh, build/python27/common.sh, build/python310/build.sh, build/python310/common.sh, build/zlib/build.sh, build/zsh/build.sh, lib/config.sh, lib/functions.sh
Fixes https://github.com/omniosorg/omnios-build/issues/2703
=> Some libraries are missing an SONAME tag

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151030et

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151038at

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151040t

build/python310/build.sh, build/python310/patches/test-shutil.patch, doc/packages.md
```
>>> Test results for Python 3.10
======================================================================
BASELINE MATCH
======================================================================
```
=> python310 - update from 3.10.3 to 3.10.4

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151040v (r151040)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038av (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030ew (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151040w (r151040)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038aw (r151038)

build/gzip/build.sh, build/gzip/testsuite.log, doc/packages.md
gzip: update from 1.11 to 1.12
=> gzip: update from 1.11 to 1.12

build/gzip/build.sh
gzip - update from 1.11 to 1.12 (r151040)
=> gzip - update from 1.11 to 1.12 (r151040)

build/gzip/build.sh
gzip - update from 1.11 to 1.12 (r151042)
=> gzip - update from 1.11 to 1.12 (r151042)

build/gzip/build.sh
gzip - update from 1.10 to 1.12 (r151038)
=> gzip - update from 1.10 to 1.12 (r151038)

build/entire/entire.pkg, build/gzip/build.sh, build/jeos/omnios-userland.pkg
gzip - update from 1.10 to 1.12 (r151030)
=> gzip - update from 1.10 to 1.12 (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151030ex

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151038ax

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151040x

build/vim/build.sh
vim: update to 8.2.4691 (r151040)
=> vim: update to 8.2.4691 (r151040)

build/git/build.sh
git - update from 2.31.1 to 2.31.2 (r151038)
=> git - update from 2.31.1 to 2.31.2 (r151038)

build/git/build.sh
git - update from 2.35.1 to 2.35.2 (r151042)
=> git - update from 2.35.1 to 2.35.2 (r151042)

build/git/build.sh
git - update from 2.33.1 to 2.33.2 (r151040)
=> git - update from 2.33.1 to 2.33.2 (r151040)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038ay (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151040y (r151040)

build/ca-bundle/build.sh
=> Move CA certificates back to /etc/ssl/certs/

build/curl/build.sh
curl - update from 7.79.1 to 7.83.0 (r151038)
=> curl - update from 7.79.1 to 7.83.0 (r151038)

build/curl/build.sh
curl - update from 7.79.1 to 7.83.0 (r151040)
=> curl - update from 7.79.1 to 7.83.0 (r151040)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030fa (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038ba (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151040aa (r151040)

build/libxml2/build.sh
libxml2 - update from 2.9.13 to 2.9.14 (r151042)
=> libxml2 - update from 2.9.13 to 2.9.14 (r151042)

build/libxml2/build.sh
libxml2 - update from 2.9.13 to 2.9.14 (r151040)
=> libxml2 - update from 2.9.13 to 2.9.14 (r151040)

build/libxml2/build.sh
libxml2 - update from 2.9.13 to 2.9.14 (r151038)
=> libxml2 - update from 2.9.13 to 2.9.14 (r151038)

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
curl - update from 7.83.0 to 7.83.1
=> curl - update from 7.83.0 to 7.83.1

build/curl/build.sh
curl - update from 7.83.0 to 7.83.1 (r151038)
=> curl - update from 7.83.0 to 7.83.1 (r151038)

build/curl/build.sh
curl - update from 7.83.0 to 7.83.1 (r151040)
=> curl - update from 7.83.0 to 7.83.1 (r151040)

build/curl/build.sh
curl - update from 7.83.0 to 7.83.1 (r151042)
=> curl - update from 7.83.0 to 7.83.1 (r151042)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038bb (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151042b (r151042)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151040ab (r151040)

build/tcsh/build.sh, build/tcsh/testsuite.log, doc/packages.md
tcsh - update from 6.24.00 to 6.24.01
=> tcsh - update from 6.24.00 to 6.24.01

build/tcsh/build.sh
tcsh - update from 6.24.00 to 6.24.01 (r151042)
=> tcsh - update from 6.24.00 to 6.24.01 (r151042)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151042h (r151042)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151040ah (r151040)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038bh (r151038)

build/python310/build.sh, build/python310/patches/enable-ossaudiodev.patch, build/python310/patches/mod-posix-sched_priority.patch, build/python310/patches/revert-makedirs.patch, build/python310/patches/test-shutil.patch, build/python310/patches/test-vmlimit.patch
python310 - update from 3.10.4 to 3.10.5 (r151042)
=> python310 - update from 3.10.4 to 3.10.5 (r151042)

build/curl/build.sh
curl - update from 7.83.1 to 7.84.0 (r151038)
=> curl - update from 7.83.1 to 7.84.0 (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151038bi

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151040ai

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151042i

build/openssl/build-1.1.sh
openssl: update to 1.1.1q (r151038)
=> openssl: update to 1.1.1q (r151038)

build/cloud-init/build.sh, doc/packages.md
cloud-init - update from 22.2 to 22.2.2
=> cloud-init - update from 22.2 to 22.2.2

build/iso-codes/build.sh, doc/packages.md
iso-codes - update from 4.10.0 to 4.11.0
=> iso-codes - update from 4.10.0 to 4.11.0

build/python310/build.sh, build/python310/patches/enable-ossaudiodev.patch, build/python310/patches/mod-socket-xpg6.patch, build/python310/patches/module-dlpi.patch, build/python310/patches/module-priv-rbac.patch, build/python310/patches/module-ucred.patch, build/python310/patches/setup.patch, build/python310/patches/test-shutil.patch
python310 - update from 3.10.5 to 3.10.6 (r151042)
=> python310 - update from 3.10.5 to 3.10.6 (r151042)

build/openjdk8/build.sh, doc/packages.md
openjdk8: update from 1.8.342-07 -> 1.8.345-01
=> openjdk8: update from 1.8.342-07 -> 1.8.345-01

build/openjdk8/build.sh
openjdk8: update from 1.8.342-07 -> 1.8.345-01 (r151042)
=> openjdk8: update from 1.8.342-07 -> 1.8.345-01 (r151042)

build/openjdk8/build.sh
openjdk8: update from 1.8.342-07 -> 1.8.345-01 (r151040)
=> openjdk8: update from 1.8.342-07 -> 1.8.345-01 (r151040)

build/openjdk8/build.sh
openjdk8: update from 1.8.342-07 -> 1.8.345-01 (r151038)
=> openjdk8: update from 1.8.342-07 -> 1.8.345-01 (r151038)

build/binutils/build.sh, build/binutils/patches/startstop.patch, doc/packages.md
binutils - update from 2.38 to 2.39
=> binutils - update from 2.38 to 2.39

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151042o (r151042)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151040ao (r151040)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038bo (r151038)

build/cloud-init/build.sh, doc/packages.md
cloud-init - update from 22.2.2 to 22.3
=> cloud-init - update from 22.2.2 to 22.3

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151042q (r151042)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151040aq (r151040)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038bq (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151042r (r151042)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151040ar (r151040)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038br (r151038)

build/python310/build.sh, build/python310/patches/autoconf-macros.patch, doc/packages.md
python310 - update from 3.10.6 to 3.10.7
=> python310 - update from 3.10.6 to 3.10.7

build/python310/build.sh
python310 - update from 3.10.6 to 3.10.7 (r151042)
=> python310 - update from 3.10.6 to 3.10.7 (r151042)

build/python39/build.sh
python39 - update from 3.9.13 to 3.9.14 (r151038)
=> python39 - update from 3.9.13 to 3.9.14 (r151038)

build/rsync/build.sh, doc/packages.md
rsync - update from 3.2.5 to 3.2.6
=> rsync - update from 3.2.5 to 3.2.6

build/expat/build.sh
expat - update from 2.4.7 to 2.4.9 (r151040)
=> expat - update from 2.4.7 to 2.4.9 (r151040)

build/expat/build.sh
expat - update from 2.4.7 to 2.4.9 (r151038)
=> expat - update from 2.4.7 to 2.4.9 (r151038)

build/expat/build.sh
expat - update from 2.4.8 to 2.4.9 (r151042)
=> expat - update from 2.4.8 to 2.4.9 (r151042)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151042v (r151042)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151040av (r151040)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038bv (r151038)

build/dbus/build.sh, build/dbus/testsuite.log, doc/packages.md
dbus: update from 1.14.0 to 1.14.2
=> dbus: update from 1.14.0 to 1.14.2

build/sqlite3/build.sh, doc/packages.md
sqlite3 - update from 3390300 to 3390400
=> sqlite3 - update from 3390300 to 3390400

lib/config.sh, lib/functions.sh
Use explicit paths to native utilities
=> Use explicit paths to native utilities

build/python310/build.sh
python310 - update from 3.10.7 to 3.10.8 (r151044)
=> python310 - update from 3.10.7 to 3.10.8 (r151044)

build/python39/build.sh, build/python39/patches/mod-posix-sched_priority.patch
python39 - update from 3.9.14 to 3.9.15 (r151040)
=> python39 - update from 3.9.14 to 3.9.15 (r151040)

build/python310/build.sh
python310 - update from 3.10.7 to 3.10.8 (r151042)
=> python310 - update from 3.10.7 to 3.10.8 (r151042)

build/libxml2/build.sh
libxml2 - update from 2.10.1 to 2.10.3 (r151038)
=> libxml2 - update from 2.10.1 to 2.10.3 (r151038)

build/libxml2/build.sh
libxml2 - update from 2.10.1 to 2.10.3 (r151040)
=> libxml2 - update from 2.10.1 to 2.10.3 (r151040)

build/libxml2/build.sh
libxml2 - update from 2.10.1 to 2.10.3 (r151042)
=> libxml2 - update from 2.10.1 to 2.10.3 (r151042)

build/libxml2/build.sh
libxml2 - update from 2.10.2 to 2.10.3 (r151044)
=> libxml2 - update from 2.10.2 to 2.10.3 (r151044)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151040ay (r151040)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038by (r151038)

build/curl/build.sh, build/curl/patches/tests.patch
curl - update from 7.84.0 to 7.86.0 (r151040)
=> curl - update from 7.84.0 to 7.86.0 (r151040)

build/curl/build.sh, build/curl/patches/tests.patch
curl - update from 7.84.0 to 7.86.0 (r151038)
=> curl - update from 7.84.0 to 7.86.0 (r151038)

build/curl/build.sh, build/curl/patches/tests.patch
curl - update from 7.84.0 to 7.86.0 (r151042)
=> curl - update from 7.84.0 to 7.86.0 (r151042)

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151038bz

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151042z

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
curl - update from 7.85.0 to 7.86.0
=> curl - update from 7.85.0 to 7.86.0

build/curl/build.sh
curl - update from 7.85.0 to 7.86.0 (r151044)
=> curl - update from 7.85.0 to 7.86.0 (r151044)

build/openssl/build-1.1.sh
openssl - update from 1.1.1q to 1.1.1s (r151038)
=> openssl - update from 1.1.1q to 1.1.1s (r151038)

build/openssl/build-1.1.sh, build/openssl/build-3.sh
openssl - update from 3.0.5 to 3.0.7 (r151040)
=> openssl - update from 3.0.5 to 3.0.7 (r151040)

build/openssl/build-1.1.sh, build/openssl/build-3.sh, build/openssl/testsuite-1.1.log, build/openssl/testsuite-3.log, doc/packages.md
openssl - update from  to 3.0.7
=> openssl - update from  to 3.0.7

build/openssl/build-1.1.sh, build/openssl/build-3.sh
openssl - update from 3.0.5 to 3.0.7 (r151042)
=> openssl - update from 3.0.5 to 3.0.7 (r151042)

build/openssl/build-1.1.sh, build/openssl/build-3.sh
openssl - update from 3.0.5 to 3.0.7 (r151044)
=> openssl - update from 3.0.5 to 3.0.7 (r151044)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038ca (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151040ba (r151040)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151042aa (r151042)

build/sudo/build.sh, build/sudo/patches/Makefile.in.patch
sudo - update from 1.9.11p3 to 1.9.12p1 (r151044)
=> sudo - update from 1.9.11p3 to 1.9.12p1 (r151044)

build/sudo/build.sh, build/sudo/local.mog, build/sudo/patches/Makefile.in.patch
sudo - update from 1.9.6p1 to 1.9.12p1 (r151038)
=> sudo - update from 1.9.6p1 to 1.9.12p1 (r151038)

build/sudo/build.sh, build/sudo/patches/Makefile.in.patch, build/sudo/patches/mansections.patch
sudo - update from 1.9.10 to 1.9.12p1 (r151042)
=> sudo - update from 1.9.10 to 1.9.12p1 (r151042)

build/ca-bundle/build.sh, build/openssl/build-3.sh, build/openssl/local.mog, build/openssl/patches-3/cross-aarch64.patch, build/openssl/patches-3/series, doc/framework, doc/pkglist.aarch64, lib/functions.sh
Builds on #3023 - draft until that one is merged.
=> openssl: aarch64 build

build/curl/build.sh
curl - update from 7.86.0 to 7.87.0 (r151042)
=> curl - update from 7.86.0 to 7.87.0 (r151042)

build/curl/build.sh
curl - update from 7.86.0 to 7.87.0 (r151044)
=> curl - update from 7.86.0 to 7.87.0 (r151044)

build/curl/build.sh, doc/packages.md
curl - update from 7.86.0 to 7.87.0
=> curl - update from 7.86.0 to 7.87.0

build/curl/build.sh
curl - update from 7.86.0 to 7.87.0 (r151038)
=> curl - update from 7.86.0 to 7.87.0 (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038ch (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151044g (r151044)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151042ah (r151042)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038ci (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151042ai (r151042)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151044h (r151044)

build/git/build.sh, doc/packages.md
git - update from 2.39.0 to 2.39.1
=> git - update from 2.39.0 to 2.39.1

build/git/build.sh
git - update from 2.31.2 to 2.31.6 (r151038)
=> git - update from 2.31.2 to 2.31.6 (r151038)

build/git/build.sh
git - update from 2.35.2 to 2.35.6 (r151042)
=> git - update from 2.35.2 to 2.35.6 (r151042)

build/git/build.sh
git - update from 2.37.3 to 2.37.5 (r151044)
=> git - update from 2.37.3 to 2.37.5 (r151044)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151044k (r151044)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038cl (r151038)

build/openssh/build.sh, build/openssh/patches/0002-PAM-Support.patch, build/openssh/patches/0003-lastlogin.patch, build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch, build/openssh/patches/0008-Add-DisableBanner-option.patch, build/openssh/patches/0009-PAM-conversation-fix.patch, build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch, build/openssh/patches/0013-Solaris-Auditing-support.patch, build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch, build/openssh/patches/0016-PAM-setcred-failures.patch, build/openssh/patches/0018-Per-session-xauthfile.patch, build/openssh/patches/0019-PubKeyPlugin-support.patch, build/openssh/patches/0021-Try-to-create-privsep-chroot-dir-if-it-doesn-t-exist.patch, build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch, build/openssh/patches/0027-Set-default-sshd-options-based-on-etc-default-login.patch, build/openssh/patches/0028-Compatibility-for-SunSSH_1.5-should-include-old-DH-K.patch, build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch, build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch, doc/packages.md
- openssh: update from 9.1p1 to 9.2p2
- Fix packages.md alignment
=> openssh: update from 9.1p1 to 9.2p1

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151042ao (r151042)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038co (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151044n (r151044)

build/python310/build.sh, build/python310/patches/enable-ossaudiodev.patch, build/python310/patches/mod-socket-xpg6.patch, build/python310/patches/module-dlpi.patch, build/python310/patches/module-priv-rbac.patch, build/python310/patches/module-ucred.patch, build/python310/patches/setup.patch, build/python310/patches/test-zipfile.patch, build/python311/build.sh, build/python311/patches/cross-aarch64.patch, build/python311/patches/mod-posix-sched_priority.patch, build/python311/patches/module-dlpi.patch, build/python311/patches/module-priv-rbac.patch, build/python311/patches/module-ucred.patch, build/python311/patches/setup.patch, build/python311/patches/test-zipfile.patch, doc/packages.md
```
>>> Test results for Python 3.10
======================================================================
BASELINE MATCH
======================================================================
>>> Test results for Python 3.11
======================================================================
BASELINE MATCH
======================================================================
```
=> Python package updates

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151044p (r151044)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151042aq (r151042)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038cq (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038cs (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151042as (r151042)

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
curl - update from 7.88.1 to 8.0.1
=> curl - update from 7.88.1 to 8.0.1

build/openssl/build-1.0.sh, build/openssl/build-1.1.sh, build/openssl/build-3.sh, build/openssl/patches-1.0/CVE-2023-0215.patch, build/openssl/patches-1.0/CVE-2023-0286.patch, build/openssl/patches-1.0/CVE-2023-0464.patch, build/openssl/patches-1.0/series, build/openssl/patches-1.1/CVE-2023-0464.patch, build/openssl/patches-1.1/series, build/openssl/patches-3/CVE-2023-0464.patch, build/openssl/patches-3/series
openssl: patch for CVE-2023-0464 (r151044)
=> openssl: patch for CVE-2023-0464 (r151044)

build/curl/build.sh
curl - update from 7.87.0 to 8.0.1 (r151042)
=> curl - update from 7.87.0 to 8.0.1 (r151042)

build/curl/build.sh
curl - update from 7.87.0 to 8.0.1 (r151038)
=> curl - update from 7.87.0 to 8.0.1 (r151038)

build/nss/patches/illumos.patch
nss: Use mapfiles when linking libraries (r151046)
=> nss: Use mapfiles when linking libraries (r151046)

build/nss/patches/illumos.patch
=> nss: Use mapfiles when linking libraries

build/rsyslog/build.sh, doc/packages.md
fastjson: update from 0.99.9 to 0.99.9.1
=> fastjson: update from 0.99.9 to 0.99.9.1

build/rsyslog/build.sh
fastjson: update from 0.99.9 to 0.99.9.1 (r151042)
=> fastjson: update from 0.99.9 to 0.99.9.1 (r151042)

build/rsyslog/build.sh
fastjson: update from 0.99.9 to 0.99.9.1 (r151044)
=> fastjson: update from 0.99.9 to 0.99.9.1 (r151044)

build/rsyslog/build.sh
fastjson: update from 0.99.9 to 0.99.9.1 (r151046)
=> fastjson: update from 0.99.9 to 0.99.9.1 (r151046)

build/rsyslog/build.sh
fastjson: update from 0.99.9 to 0.99.9.1 (r151038)
=> fastjson: update from 0.99.9 to 0.99.9.1 (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038cw (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151044v (r151044)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151042aw (r151042)

build/python311/build.sh, build/python311/patches/test-freeze.patch
python311 - update from 3.11.2 to 3.11.3 (r151046)
=> python311 - update from 3.11.2 to 3.11.3 (r151046)

build/python310/build.sh, build/python310/patches/enable-ossaudiodev.patch, build/python310/patches/mod-socket-xpg6.patch, build/python310/patches/module-dlpi.patch, build/python310/patches/module-priv-rbac.patch, build/python310/patches/module-ucred.patch, build/python310/patches/setup.patch, build/python310/patches/test-zipfile.patch
python310 - update from 3.10.9 to 3.10.11 (r151042)
=> python310 - update from 3.10.9 to 3.10.11 (r151042)

build/python310/build.sh, build/python310/patches/enable-ossaudiodev.patch, build/python310/patches/mod-socket-xpg6.patch, build/python310/patches/module-dlpi.patch, build/python310/patches/module-priv-rbac.patch, build/python310/patches/module-ucred.patch, build/python310/patches/setup.patch, build/python310/patches/test-zipfile.patch
python310 - update from 3.10.9 to 3.10.11 (r151044)
=> python310 - update from 3.10.9 to 3.10.11 (r151044)

build/python311/build.sh, build/python311/patches/test-freeze.patch, doc/packages.md
python311 - update from 3.11.2 to 3.11.3
=> python311 - update from 3.11.2 to 3.11.3

build/ipmitool/patches/iana-pen.patch, build/ipmitool/patches/series
Fix ipmitool enterprise-numbers database (r151046)
=> Fix ipmitool enterprise-numbers database (r151046)

build/ipmitool/patches/iana-pen.patch, build/ipmitool/patches/series
Fix ipmitool enterprise-numbers database
=> Fix ipmitool enterprise-numbers database

build/libxml2/build.sh
libxml2 - update from 2.10.3 to 2.10.4 (r151042)
=> libxml2 - update from 2.10.3 to 2.10.4 (r151042)

build/libxml2/build.sh
libxml2 - update from 2.10.3 to 2.10.4 (r151044)
=> libxml2 - update from 2.10.3 to 2.10.4 (r151044)

build/libxml2/build.sh
libxml2 - update from 2.10.3 to 2.10.4 (r151038)
=> libxml2 - update from 2.10.3 to 2.10.4 (r151038)

build/libxml2/build.sh
libxml2 - update from 2.10.3 to 2.10.4 (r151046)
=> libxml2 - update from 2.10.3 to 2.10.4 (r151046)

build/coreutils/build.sh, build/coreutils/testsuite.log, doc/packages.md
coreutils - update from 9.2 to 9.3
=> coreutils - update from 9.2 to 9.3

build/coreutils/build.sh
coreutils - update from 9.2 to 9.3 (r151046)
=> coreutils - update from 9.2 to 9.3 (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151038cy

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151044x

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151042ay

lib/functions.sh
clear_archflags is a little over-zealous (r151046)
=> clear_archflags is a little over-zealous (r151046)

build/git/build.sh
git - update from 2.35.7 to 2.35.8 (r151042)
=> git - update from 2.35.7 to 2.35.8 (r151042)

build/git/build.sh
git - update from 2.37.6 to 2.37.7 (r151044)
=> git - update from 2.37.6 to 2.37.7 (r151044)

build/git/build.sh
git - update from 2.31.7 to 2.31.8 (r151038)
=> git - update from 2.31.7 to 2.31.8 (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151042az (r151042)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151044y (r151044)

build/curl/build.sh
curl - update from 8.0.1 to 8.1.0 (r151046)
=> curl - update from 8.0.1 to 8.1.0 (r151046)

build/curl/build.sh
curl - update from 8.0.1 to 8.1.0 (r151038)
=> curl - update from 8.0.1 to 8.1.0 (r151038)

build/curl/build.sh, build/curl/patches/run-compiler.patch, build/curl/patches/series
curl - update from 8.1.0 to 8.1.1 (r151038)
=> curl - update from 8.1.0 to 8.1.1 (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038de (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151044ad (r151044)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046e (r151046)

build/vim/build.sh
vim: update from 9.0.0 to 9.0.1443 (r151046)
=> vim: update from 9.0.0 to 9.0.1443 (r151046)

build/vim/build.sh
vim: update from 9.0.0 to 9.0.1443 (r151044)
=> vim: update from 9.0.0 to 9.0.1443 (r151044)

build/vim/build.sh
vim: update from 9.0.0 to 9.0.1443
=> vim: update from 9.0.0 to 9.0.1443

build/python39/build.sh
python39 - update from 3.9.15 to 3.9.17 (r151038)
=> python39 - update from 3.9.15 to 3.9.17 (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038dh (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151044ag (r151044)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046h (r151046)

build/openssh/build.sh, build/openssh/patches/0001-Skip-config-check.patch, build/openssh/patches/0002-PAM-Support.patch, build/openssh/patches/0003-lastlogin.patch, build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch, build/openssh/patches/0007-DTrace-support-for-SFTP.patch, build/openssh/patches/0008-Add-DisableBanner-option.patch, build/openssh/patches/0009-PAM-conversation-fix.patch, build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch, build/openssh/patches/0013-Solaris-Auditing-support.patch, build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch, build/openssh/patches/0016-PAM-setcred-failures.patch, build/openssh/patches/0017-Don-t-call-do_pam_setcred-twice.patch, build/openssh/patches/0018-Per-session-xauthfile.patch, build/openssh/patches/0019-PubKeyPlugin-support.patch, build/openssh/patches/0021-Try-to-create-privsep-chroot-dir-if-it-doesn-t-exist.patch, build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch, build/openssh/patches/0027-Set-default-sshd-options-based-on-etc-default-login.patch, build/openssh/patches/0028-Compatibility-for-SunSSH_1.5-should-include-old-DH-K.patch, build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch, build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch, build/openssh/patches/sk-dummy-openssl.patch, build/openssh/patches/sshd_config.patch, build/openssh/patches/test.patch, doc/packages.md
openssh - update from 9.3p1 to 9.3p2
=> openssh - update from 9.3p1 to 9.3p2

build/openssh/build.sh, build/openssh/patches/0001-Skip-config-check.patch, build/openssh/patches/0002-PAM-Support.patch, build/openssh/patches/0003-lastlogin.patch, build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch, build/openssh/patches/0007-DTrace-support-for-SFTP.patch, build/openssh/patches/0008-Add-DisableBanner-option.patch, build/openssh/patches/0009-PAM-conversation-fix.patch, build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch, build/openssh/patches/0013-Solaris-Auditing-support.patch, build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch, build/openssh/patches/0016-PAM-setcred-failures.patch, build/openssh/patches/0017-Don-t-call-do_pam_setcred-twice.patch, build/openssh/patches/0018-Per-session-xauthfile.patch, build/openssh/patches/0019-PubKeyPlugin-support.patch, build/openssh/patches/0021-Try-to-create-privsep-chroot-dir-if-it-doesn-t-exist.patch, build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch, build/openssh/patches/0027-Set-default-sshd-options-based-on-etc-default-login.patch, build/openssh/patches/0028-Compatibility-for-SunSSH_1.5-should-include-old-DH-K.patch, build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch, build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch, build/openssh/patches/sk-dummy-openssl.patch, build/openssh/patches/sshd_config.patch, build/openssh/patches/test.patch
openssh - update from 9.3p1 to 9.3p2 (r151046)
=> openssh - update from 9.3p1 to 9.3p2 (r151046)

build/openssh/build.sh, build/openssh/patches/0001-Skip-config-check.patch, build/openssh/patches/0002-PAM-Support.patch, build/openssh/patches/0003-lastlogin.patch, build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch, build/openssh/patches/0007-DTrace-support-for-SFTP.patch, build/openssh/patches/0008-Add-DisableBanner-option.patch, build/openssh/patches/0009-PAM-conversation-fix.patch, build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch, build/openssh/patches/0013-Solaris-Auditing-support.patch, build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch, build/openssh/patches/0016-PAM-setcred-failures.patch, build/openssh/patches/0017-Don-t-call-do_pam_setcred-twice.patch, build/openssh/patches/0018-Per-session-xauthfile.patch, build/openssh/patches/0019-PubKeyPlugin-support.patch, build/openssh/patches/0021-Try-to-create-privsep-chroot-dir-if-it-doesn-t-exist.patch, build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch, build/openssh/patches/0027-Set-default-sshd-options-based-on-etc-default-login.patch, build/openssh/patches/0028-Compatibility-for-SunSSH_1.5-should-include-old-DH-K.patch, build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch, build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch, build/openssh/patches/sk-dummy-openssl.patch, build/openssh/patches/sshd_config.patch, build/openssh/patches/test.patch
openssh - update from 9.0p1 to 9.3p2 (r151044)
=> openssh - update from 9.0p1 to 9.3p2 (r151044)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038dl (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151044ak (r151044)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046l (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038dm (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151044al (r151044)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046m (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046n (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151044am (r151044)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038dn (r151038)

build/chrony/build.sh, doc/packages.md, tools/test
chrony: bump bundled nettle to 3.9.1
=> chrony: bump bundled nettle to 3.9.1

build/buildctl, lib/config.sh, lib/functions.sh
This was bundling stray files from the cross venv with the package
=> Fix cross python module installation

build/screen/build.sh, build/screen/patches/Makefile.in.patch, build/screen/patches/ncurses.patch, build/screen/patches/unneededlibs.patch, doc/packages.md
screen - update from 4.9.0 to 4.9.1
=> screen - update from 4.9.0 to 4.9.1

build/screen/build.sh, build/screen/patches/Makefile.in.patch, build/screen/patches/ncurses.patch, build/screen/patches/unneededlibs.patch
screen - update from 4.9.0 to 4.9.1 (r151046)
=> screen - update from 4.9.0 to 4.9.1 (r151046)

build/screen/build.sh, build/screen/patches/Makefile.in.patch, build/screen/patches/ncurses.patch, build/screen/patches/unneededlibs.patch
screen - update from 4.9.0 to 4.9.1 (r151044)
=> screen - update from 4.9.0 to 4.9.1 (r151044)

build/screen/build.sh, build/screen/patches/Makefile.in.patch, build/screen/patches/ncurses.patch, build/screen/patches/series, build/screen/patches/unneededlibs.patch
screen - update from 4.8.0 to 4.9.1 (r151038)
=> screen - update from 4.8.0 to 4.9.1 (r151038)

build/screen/build.sh
Building screen requires XPG4v2 (r151038)
=> Building screen requires XPG4v2 (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038dq (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151044ap (r151044)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046q (r151046)

build/pcre2/build.sh, build/pcre2/local.mog, build/pcre2/patches/greptest.patch, build/pcre2/patches/no_pcre2demo.patch, build/pcre2/patches/series
fixes https://github.com/omniosorg/omnios-build/issues/3338
=> pcre2: drop pcre2demo(3) man page

build/python310/build.sh
python310 - update from 3.10.12 to 3.10.13 (r151044)
=> python310 - update from 3.10.12 to 3.10.13 (r151044)

build/python311/build.sh
python311 - update from 3.11.4 to 3.11.5 (r151046)
=> python311 - update from 3.11.4 to 3.11.5 (r151046)

build/openssl/build-3.sh, build/openssl/testsuite-3.log, doc/packages.md
openssl -update from 3.1.2 to 3.1.3
=> openssl - update from 3.1.2 to 3.1.3

build/openssl/build-3.sh
openssl - update from 3.0.10 to 3.0.11 (r151044)
=> openssl - update from 3.0.10 to 3.0.11 (r151044)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046u (r151046)

build/curl/build.sh, build/curl/patches/tests.patch, build/curl/testsuite.log, doc/packages.md
curl - update from 8.3.0 to 8.4.0
=> curl - update from 8.3.0 to 8.4.0

build/curl/build.sh, build/curl/patches/tests.patch, build/curl/testsuite.log
curl - update from 8.3.0 to 8.4.0 (r151044)
=> curl - update from 8.3.0 to 8.4.0 (r151044)

build/curl/build.sh, build/curl/patches/tests.patch, build/curl/testsuite.log
curl - update from 8.3.0 to 8.4.0 (r151046)
=> curl - update from 8.3.0 to 8.4.0 (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038dx (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151044aw (r151044)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046x (r151046)

build/openssl/build-3.sh, build/openssl/patches-3/libs.patch, build/openssl/testsuite-3.log
openssl - update from 3.1.3 to 3.1.4 (r151048)
=> openssl - update from 3.1.3 to 3.1.4 (r151048)

build/openssl/build-3.sh, build/openssl/patches-3/libs.patch, build/openssl/testsuite-3.log, doc/packages.md
openssl - update from 3.1.3 to 3.1.4
=> openssl - update from 3.1.3 to 3.1.4

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151044ay (r151044)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046z (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151048b (r151048)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038ec (r151038)

build/curl/build.sh
curl - update from 8.4.0 to 8.5.0 (r151046)
=> curl - update from 8.4.0 to 8.5.0 (r151046)

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
curl - update from 8.4.0 to 8.5.0
=> curl - update from 8.4.0 to 8.5.0

build/curl/build.sh
curl - update from 8.4.0 to 8.5.0 (r151038)
=> curl - update from 8.4.0 to 8.5.0 (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038eg (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151048f (r151048)

build/libxml2/build.sh, doc/packages.md
libxml2 - update from 2.12.1 to 2.12.3
=> libxml2 - update from 2.12.1 to 2.12.3

build/openssh/build.sh, build/openssh/patches/0002-PAM-Support.patch, build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch, build/openssh/patches/0008-Add-DisableBanner-option.patch, build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch, build/openssh/patches/0013-Solaris-Auditing-support.patch, build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch, build/openssh/patches/0019-PubKeyPlugin-support.patch, build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch, build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch, build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch, doc/packages.md
openssh - update from 9.5p1 to 9.6p1
=> openssh - update from 9.5p1 to 9.6p1

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151048i (r151048)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046aj (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038ej (r151038)

build/unzip/build.sh, build/unzip/patches/CVE-2014-8139-crc-overflow.patch, build/unzip/patches/CVE-2014-8140-test-compr-eb.patch, build/unzip/patches/CVE-2014-8141-getzip64data.patch, build/unzip/patches/CVE-2014-9636-test-compr-eb.patch, build/unzip/patches/CVE-2014-9913-unzip-buffer-overflow.patch, build/unzip/patches/CVE-2015-7696-heap-overflow.patch, build/unzip/patches/CVE-2015-7697-infinite-loop.patch, build/unzip/patches/CVE-2016-9844-zipinfo-buffer-overflow.patch, build/unzip/patches/CVE-2018-1000035-overflow-password-protect.patch, build/unzip/patches/CVE-2019-13232a.patch, build/unzip/patches/CVE-2019-13232b.patch, build/unzip/patches/CVE-2019-13232c.patch, build/unzip/patches/CVE-2019-13232d.patch, build/unzip/patches/CVE-2019-13232e.patch, build/unzip/patches/CVE-2021-4217.patch, build/unzip/patches/CVE-2022-0529-0530.patch, build/unzip/patches/configure.patch, build/unzip/patches/fileio-big-files.patch, build/unzip/patches/integer-underflow-csiz_decrypted.patch, build/unzip/patches/nostrip.patch, build/unzip/patches/series, build/unzip/patches/unix_Makefile.patch
unzip: backport fixes from bloody (r151046)
=> unzip: backport fixes from bloody (r151046)

build/unzip/build.sh, build/unzip/patches/CVE-2014-8139-crc-overflow.patch, build/unzip/patches/CVE-2014-8140-test-compr-eb.patch, build/unzip/patches/CVE-2014-8141-getzip64data.patch, build/unzip/patches/CVE-2014-9636-test-compr-eb.patch, build/unzip/patches/CVE-2014-9913-unzip-buffer-overflow.patch, build/unzip/patches/CVE-2015-7696-heap-overflow.patch, build/unzip/patches/CVE-2015-7697-infinite-loop.patch, build/unzip/patches/CVE-2016-9844-zipinfo-buffer-overflow.patch, build/unzip/patches/CVE-2018-1000035-overflow-password-protect.patch, build/unzip/patches/CVE-2019-13232a.patch, build/unzip/patches/CVE-2019-13232b.patch, build/unzip/patches/CVE-2019-13232c.patch, build/unzip/patches/CVE-2019-13232d.patch, build/unzip/patches/CVE-2019-13232e.patch, build/unzip/patches/CVE-2021-4217.patch, build/unzip/patches/CVE-2022-0529-0530.patch, build/unzip/patches/configure.patch, build/unzip/patches/fileio-big-files.patch, build/unzip/patches/integer-underflow-csiz_decrypted.patch, build/unzip/patches/nostrip.patch, build/unzip/patches/series, build/unzip/patches/unix_Makefile.patch
unzip: backport fixes from bloody (r151048)
=> unzip: backport fixes from bloody (r151048)

build/unzip/build.sh, build/unzip/patches/CVE-2014-8139-crc-overflow.patch, build/unzip/patches/CVE-2014-8140-test-compr-eb.patch, build/unzip/patches/CVE-2014-8141-getzip64data.patch, build/unzip/patches/CVE-2014-9636-test-compr-eb.patch, build/unzip/patches/CVE-2014-9913-unzip-buffer-overflow.patch, build/unzip/patches/CVE-2015-7696-heap-overflow.patch, build/unzip/patches/CVE-2015-7697-infinite-loop.patch, build/unzip/patches/CVE-2016-9844-zipinfo-buffer-overflow.patch, build/unzip/patches/CVE-2018-1000035-overflow-password-protect.patch, build/unzip/patches/CVE-2019-13232a.patch, build/unzip/patches/CVE-2019-13232b.patch, build/unzip/patches/CVE-2019-13232c.patch, build/unzip/patches/CVE-2019-13232d.patch, build/unzip/patches/CVE-2019-13232e.patch, build/unzip/patches/CVE-2021-4217.patch, build/unzip/patches/CVE-2022-0529-0530.patch, build/unzip/patches/configure.patch, build/unzip/patches/fileio-big-files.patch, build/unzip/patches/integer-underflow-csiz_decrypted.patch, build/unzip/patches/nostrip.patch, build/unzip/patches/series, build/unzip/patches/unix_Makefile.patch
unzip: backport fixes from bloody (r151038)
=> unzip: backport fixes from bloody (r151038)

build/zlib/build.sh, build/zlib/testsuite.log
zlib - update from 1.3 to 1.3.1 (r151048)
=> zlib - update from 1.3 to 1.3.1 (r151048)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151048m (r151048)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046an (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038en (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038ep (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046ap (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151048o (r151048)

build/openjdk21/build.sh
=> Fix openjdk21 description

build/buildctl
```
***
*** ***** BUILD ERROR ***** (compress/gzip)
***
Fri Feb 23 16:15:35 UTC 2024
Total build time: 0h3m19s
bloody:omnios:exit% echo $?
1
```
=> Exit with failure status if build fails

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151048t (r151048)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046au (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038eu (r151038)

build/meta/illumos-tools.p5m, build/meta/omnios-build-tools.p5m
see https://github.com/omniosorg/illumos-omnios/pull/1446
=> illumos uses jdk17 for build

build/curl/build.sh
curl - update from 8.6.0 to 8.7.1 (r151038)
=> curl - update from 8.6.0 to 8.7.1 (r151038)

build/curl/build.sh
curl - update from 8.6.0 to 8.7.1 (r151046)
=> curl - update from 8.6.0 to 8.7.1 (r151046)

build/curl/build.sh
curl - update from 8.6.0 to 8.7.1 (r151050)
=> curl - update from 8.6.0 to 8.7.1 (r151050)

build/curl/build.sh
curl - update from 8.6.0 to 8.7.1 (r151048)
=> curl - update from 8.6.0 to 8.7.1 (r151048)

build/readline/patches/README, build/readline/patches/readline82-001, build/readline/patches/readline82-002, build/readline/patches/readline82-003, build/readline/patches/readline82-004, build/readline/patches/readline82-005, build/readline/patches/readline82-006, build/readline/patches/readline82-007, build/readline/patches/readline82-008, build/readline/patches/readline82-009, build/readline/patches/readline82-010, build/readline/patches/series, doc/packages.md
=> Pull in readline 8.2 patches

build/python39/build.sh
python3 - update from 3.9.18 to 3.9.19 (r151038)
=> python3 - update from 3.9.18 to 3.9.19 (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151038ex (r151038)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046ax (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151048w (r151048)

build/ncurses/build.sh, build/ncurses/patches/drop-rin-from-screen-256color.diff, build/ncurses/patches/sun-color.patch, build/ncurses/patches/xterm-no-rep.patch
ncurses - update to 6.4.20240309 (r151048)
=> ncurses - update to 6.4.20240309 (r151048)

build/ncurses/build.sh, build/ncurses/patches/drop-rin-from-screen-256color.diff, build/ncurses/patches/sun-color.patch, build/ncurses/patches/xterm-no-rep.patch
ncurses - update to 6.4.20240309 (r151046)
=> ncurses - update to 6.4.20240309 (r151046)

build/ncurses/build.sh, build/ncurses/patches/drop-rin-from-screen-256color.diff, build/ncurses/patches/sun-color.patch, build/ncurses/patches/xterm-no-rep.patch
ncurses - update to 6.4.20240309 (r151050)
=> ncurses - update to 6.4.20240309 (r151050)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151050d (r151050)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151048ad (r151048)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046be (r151046)

build/xz/build.sh, build/xz/testsuite.log, doc/packages.md
xz - update from 5.6.1 to 5.6.2
=> xz - update from 5.6.1 to 5.6.2

build/xz/build.sh
xz - update from 5.6.1 to 5.6.2 (r151050)
=> xz - update from 5.6.1 to 5.6.2 (r151050)

build/openssl/build-3.sh, build/openssl/testsuite-3.log
openssl - update from 3.1.5 to 3.1.6 (r151050)
=> openssl - update from 3.1.5 to 3.1.6 (r151050)

build/openssl/build-3.sh, build/openssl/testsuite-3.log
openssl - update from 3.1.5 to 3.1.6 (r151048)
=> openssl - update from 3.1.5 to 3.1.6 (r151048)

build/openssl/build-3.sh, build/openssl/patches-1.1/CVE-2024-2511.patch, build/openssl/patches-1.1/CVE-2024-4741.patch, build/openssl/patches-1.1/series, build/openssl/testsuite-3.log, doc/packages.md
openssl - upate from 3.1.5 to 3.1.6
=> openssl - upate from 3.1.5 to 3.1.6

build/openssl/build-1.1.sh, build/openssl/build-3.sh, build/openssl/patches-1.1/CVE-2024-2511.patch, build/openssl/patches-1.1/CVE-2024-4741.patch, build/openssl/patches-1.1/series, build/openssl/testsuite-3.log
openssl - update from 3.0.13 to 3.0.14 (r151046)
=> openssl - update from 3.0.13 to 3.0.14 (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for release r15105e

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151048ae

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046bf

build/python312/build.sh, build/python312/patches/disable_epoll.patch, build/python312/patches/mod-posix-sched_priority.patch, build/python312/patches/posix_spawn-close_fds-support.patch, build/python312/patches/posix_spawn-environment-fix.patch, build/python312/patches/py_db.patch, build/python312/patches/revert-makedirs.patch, build/python312/patches/test-pkgutil.patch, build/python312/patches/test-tarfile.patch, build/python312/testsuite.log
python312 - update from 3.12.3 to 3.12.4 (r151050)
=> python312 - update from 3.12.3 to 3.12.4 (r151050)

build/python312/build.sh, build/readline/build.sh, build/vim/build.sh, lib/functions.sh
=> nss/nspr: fix unused RPATHs

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151050h

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151048ah

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151046bi

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151050i (r151050)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151048ai (r151048)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046bj (r151046)

build/tmux/build.sh, build/tmux/patches/manformat.patch, build/tmux/patches/series
=> tmux: deliver mdoc format man page

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046bm (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151048al (r151048)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151050l (r151050)

build/curl/build.sh
curl - update from 8.7.1 to 8.9.1 (r151048)
=> curl - update from 8.7.1 to 8.9.1 (r151048)

build/curl/build.sh
curl - update from 8.7.1 to 8.9.1 (r151046)
=> curl - update from 8.7.1 to 8.9.1 (r151046)

build/curl/build.sh
curl - update from 8.7.1 to 8.9.1 (r151050)
=> curl - update from 8.7.1 to 8.9.1 (r151050)

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
curl - update from 8.8.0 to 8.9.1
=> curl - update from 8.8.0 to 8.9.1

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151050m (r151050)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151048am (r151048)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046bn (r151046)

build/git/build.sh
git - update from 2.42.0 to 2.42.3 (r151048)
=> git - update from 2.42.0 to 2.42.3 (r151048)

build/git/build.sh
git - update from 2.44.0 to 2.44.2 (r151050)
=> git - update from 2.44.0 to 2.44.2 (r151050)

build/git/build.sh
git - update from 2.40.1 to 2.40.3 (r151046)
=> git - update from 2.40.1 to 2.40.3 (r151046)

build/vim/build.sh
vim - update from 9.1.393 to 9.1.652
=> vim - update from 9.1.393 to 9.1.652

build/openssl/build-3.sh, build/openssl/testsuite-3.log, doc/packages.md
openssl - update from 3.1.6 to 3.1.7
=> openssl - update from 3.1.6 to 3.1.7

build/openssl/build-3.sh, build/openssl/testsuite-3.log
openssl - update from 3.0.14 to 3.0.15 (r151046)
=> openssl - update from 3.0.14 to 3.0.15 (r151046)

build/openssl/build-3.sh, build/openssl/testsuite-3.log
openssl - update from 3.1.6 to 3.1.7 (r151048)
=> openssl - update from 3.1.6 to 3.1.7 (r151048)

build/openssl/build-3.sh, build/openssl/testsuite-3.log
openssl - update from 3.1.6 to 3.1.7 (r151050)
=> openssl - update from 3.1.6 to 3.1.7 (r151050)

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151050r

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151048ar

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151046bs

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151050s (r151050)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151048as (r151048)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046bt (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151048av (r151048)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046bw (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046bz (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151050y (r151050)

doc/ReleaseNotes.md
=> Preparing for r151052b (r151052)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151052c (r151052)

build/meta/illumos-tools.p5m
See https://www.illumos.org/issues/16935
=> gcc14 is to be the new illumos-gate shadow compiler

build/curl/build.sh
curl - update from 8.11.0 to 8.11.1 (r151052)
=> curl - update from 8.11.0 to 8.11.1 (r151052)

build/curl/build.sh
curl - update from 8.11.0 to 8.11.1 (r151050)
=> curl - update from 8.11.0 to 8.11.1 (r151050)

build/curl/build.sh
curl - update from 8.11.0 to 8.11.1 (r151046)
=> curl - update from 8.11.0 to 8.11.1 (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046cg (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151050af (r151050)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151052f (r151052)

build/watch/build.sh, doc/packages.md
watch - update from 3.3.16 to 4.0.5
=> watch - update from 3.3.16 to 4.0.5

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151052i (r151052)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046cj (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046cl (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151050ak (r151050)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151052k (r151052)

build/git/build.sh
git - update from 2.44.2 to 2.44.3 (r151050)
=> git - update from 2.44.2 to 2.44.3 (r151050)

build/git/build.sh
git - update from 2.40.3 to 2.40.4 (r151046)
=> git - update from 2.40.3 to 2.40.4 (r151046)

build/rsync/build.sh, build/rsync/testsuite.log
rsync - update from 3.2.7 to 3.4.0 (r151050)
=> rsync - update from 3.2.7 to 3.4.0 (r151050)

build/rsync/build.sh, build/rsync/testsuite.log
rsync - update from 3.2.7 to 3.4.0 (r151046)
=> rsync - update from 3.2.7 to 3.4.0 (r151046)

build/rsync/build.sh, build/rsync/patches/gcc14.patch, build/rsync/testsuite.log, doc/packages.md
rsync - update from 3.3.0 to 3.4.0
=> rsync - update from 3.3.0 to 3.4.0

build/git/build.sh
git - update from 2.46.2 to 2.46.3 (r151052)
=> git - update from 2.46.2 to 2.46.3 (r151052)

build/rsync/build.sh
rsync - update from 3.4.0 to 3.4.1 (r151050)
=> rsync - update from 3.4.0 to 3.4.1 (r151050)

build/rsync/build.sh
rsync - update from 3.4.0 to 3.4.1 (r151046)
=> rsync - update from 3.4.0 to 3.4.1 (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151052l

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151050al

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151046cm

build/curl/build.sh
curl - update from 8.11.1 to 8.12.0 (r151052)
=> curl - update from 8.11.1 to 8.12.0 (r151052)

build/curl/build.sh
curl - update from 8.11.1 to 8.12.0 (r151046)
=> curl - update from 8.11.1 to 8.12.0 (r151046)

build/curl/build.sh
curl - update from 8.11.1 to 8.12.0 (r151050)
=> curl - update from 8.11.1 to 8.12.0 (r151050)

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
curl - update from 8.11.1 to 8.12.0
=> curl - update from 8.11.1 to 8.12.0

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046co (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151050an (r151050)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151052n (r151052)

build/openssl/build-3.sh, build/openssl/testsuite-3.log
openssl - update from 3.3.2 to 3.3.3 (r151052)
=> openssl - update from 3.3.2 to 3.3.3 (r151052)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151052o (r151052)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151050ao (r151050)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046cp (r151046)

build/openssh/build.sh, build/openssh/patches/0002-PAM-Support.patch, build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch, build/openssh/patches/0008-Add-DisableBanner-option.patch, build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch, build/openssh/patches/0013-Solaris-Auditing-support.patch, build/openssh/patches/0019-PubKeyPlugin-support.patch, build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch, build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch, build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch
openssh - update from 9.9p1 to 9.9p2 (r151052)
=> openssh - update from 9.9p1 to 9.9p2 (r151052)

build/openssh/build.sh, build/openssh/patches/0002-PAM-Support.patch, build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch, build/openssh/patches/0008-Add-DisableBanner-option.patch, build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch, build/openssh/patches/0013-Solaris-Auditing-support.patch, build/openssh/patches/0019-PubKeyPlugin-support.patch, build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch, build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch, build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch, doc/packages.md
openssh - update from 9.9p1 to 9.9p2
=> openssh - update from 9.9p1 to 9.9p2

build/libxml2/build.sh, doc/packages.md
libxml2 - update from 2.13.5 to 2.13.6
=> libxml2 - update from 2.13.5 to 2.13.6

build/openssh/build.sh, build/openssh/patches/CVE-2025-26465.patch, build/openssh/patches/CVE-2025-26466.patch, build/openssh/patches/series, build/openssh/patches/series.aarch64
openssh: Fixes for CVE-2025-2646[56] (r151050)
=> openssh: Fixes for CVE-2025-2646[56] (r151050)

build/libxml2/build.sh
libxml2 - update from 2.12.6 to 2.12.10 (r151050)
=> libxml2 - update from 2.12.6 to 2.12.10 (r151050)

build/libxml2/build.sh
libxml2 - update from 2.13.4 to 2.13.6 (r151052)
=> libxml2 - update from 2.13.4 to 2.13.6 (r151052)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151052p (r151052)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151050ap (r151050)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046cq (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046cu (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151052t (r151052)

build/expat/build.sh, build/expat/patches/no_link_libm.patch, doc/packages.md
expat - update from 2.6.4 to 2.7.0
=> expat - update from 2.6.4 to 2.7.0

build/expat/build.sh
expat - update from 2.6.4 to 2.7.0 (r151052)
=> expat - update from 2.6.4 to 2.7.0 (r151052)

build/expat/build.sh
expat - update from 2.6.4 to 2.7.0 (r151050)
=> expat - update from 2.6.4 to 2.7.0 (r151050)

build/expat/build.sh
expat - update from 2.6.4 to 2.7.0 (r151046)
=> expat - update from 2.6.4 to 2.7.0 (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046cv (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151050au (r151050)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151052u (r151052)

build/expat/build.sh
expat - update from 2.7.0 to 2.7.1 (r151050)
=> expat - update from 2.7.0 to 2.7.1 (r151050)

build/expat/build.sh
expat - update from 2.7.0 to 2.7.1 (r151052)
=> expat - update from 2.7.0 to 2.7.1 (r151052)

build/expat/build.sh
expat - update from 2.7.0 to 2.7.1 (r151046)
=> expat - update from 2.7.0 to 2.7.1 (r151046)

build/expat/build.sh, doc/packages.md
expat - update from 2.7.0 to 2.7.1
=> expat - update from 2.7.0 to 2.7.1

build/expat/build.sh, build/expat/patches/no_link_libm.patch
=> expat: disable unnecessary linking with libm

build/entire/entire-aarch64.pkg, build/pkg/build-arch-aarch64.sh, doc/baseline.aarch64
requires https://github.com/omniosorg/pkg5/pull/513
=> aarch64: ship native zone brands

build/libmagic/build.sh, build/libmagic/file.mog, build/libmagic/local.mog, build/meta/aarch64-build-tools.p5m, build/meta/omnios-build-tools.p5m, doc/baseline, doc/baseline.aarch64, doc/packages.md, doc/pkglist.aarch64, lib/config.sh
~~This depends on https://www.illumos.org/issues/17141 landing, so draft for now.~~
Undrafted since illumos 17141 is integrated upstream and will be merged to OmniOS today.
=> Add darwinsys libmagic and file alternate

build/screen/build.sh, build/screen/patches/0001-attacher.c-prevent-temporary-0666-mode-on-PTYs-to-fi.patch, build/screen/patches/0002-Avoid-file-existence-test-information-leaks-to-fix-C.patch, build/screen/patches/0003-socket.c-don-t-send-signals-with-root-privileges-to-.patch, build/screen/patches/series
screen: fixes for CVE-2025-4680[245] (r151046)
=> screen: fixes for CVE-2025-4680[245] (r151046)

build/screen/patches/0001-attacher.c-prevent-temporary-0666-mode-on-PTYs-to-fi.patch, build/screen/patches/0002-Avoid-file-existence-test-information-leaks-to-fix-C.patch, build/screen/patches/0003-socket.c-don-t-send-signals-with-root-privileges-to-.patch, build/screen/patches/series
screen: fixes for CVE-2025-4680[245]
=> screen: fixes for CVE-2025-4680[245]

build/curl/build.sh
curl - update from 8.12.0 to 8.14.0 (r151052)
=> curl - update from 8.12.0 to 8.14.0 (r151052)

build/curl/build.sh
curl - update from 8.13.0 to 8.14.0 (r151054)
=> curl - update from 8.13.0 to 8.14.0 (r151054)

build/libxml2/build.sh
libxml2 - update from 2.13.6 to 2.13.8 (r151052)
=> libxml2 - update from 2.13.6 to 2.13.8 (r151052)

build/libxml2/build.sh
libxml2 - update from 2.13.6 to 2.13.8 (r151054)
=> libxml2 - update from 2.13.6 to 2.13.8 (r151054)

build/curl/build.sh
curl - update from 8.12.0 to 8.14.0 (r151046)
=> curl - update from 8.12.0 to 8.14.0 (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151054e (r151054)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151052ae (r151052)

build/glib/build.sh, build/glib/patches/libsocket.patch, build/glib/patches/mntent.patch, build/glib/patches/no_inotify.patch, build/glib/patches/standards.patch, build/glib/testsuite.log, doc/packages.md
glib - update from 2.82.5 to 2.84.3
=> glib - update from 2.82.5 to 2.84.3

build/sudo/build.sh, doc/packages.md
sudo - update from 1.9.17 to 1.9.17p1
=> sudo - update from 1.9.17 to 1.9.17p1

build/sudo/build.sh, build/sudo/patches/CVE-2025-32462.patch, build/sudo/patches/series
sudo: fix for CVE-2025-32562 (r151046)
=> sudo: fix for CVE-2025-32562 (r151046)

build/openssl/build-3.sh, build/openssl/testsuite-3.log, doc/packages.md
openssl - update from  to 3.5.1
=> openssl - update from  to 3.5.1

build/openssl/build-3.sh
openssl-3 - update from 3.3.3 to 3.3.4 (r151052)
=> openssl-3 - update from 3.3.3 to 3.3.4 (r151052)

build/openssl/build-3.sh
openssl-3 - update from 3.0.16 to 3.0.17 (r151046)
=> openssl-3 - update from 3.0.16 to 3.0.17 (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151054i (r151054)

build/binutils/build.sh, doc/packages.md
binutils - update from 2.44 to 2.45
=> binutils - update from 2.44 to 2.45

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151054r (r151054)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151052ar (r151052)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046ds (r151046)

build/curl/build.sh
curl - update from 8.14.0 to 8.16.0 (r151046)
=> curl - update from 8.14.0 to 8.16.0 (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151046dw (r151046)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151052av (r151052)
