build/bind/build.sh
Upgrade bind to latest stable version, fixing several security issues.
=> bind: update to version 9.10.5-P2

build/bind/build.sh, build/curl/build.sh
**bind 9.10.5-P3**:
```
hadfl@mars:~$ dig -v
DiG 9.10.5-P3
```
**curl 7.54.1**:
```
hadfl@mars:~$ curl -V
curl 7.54.1 (i386-pc-solaris2.11) libcurl/7.54.1 OpenSSL/1.0.2k zlib/1.2.11 nghttp2/1.21.1
Release-Date: 2017-06-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy 
```
=> pkg security fixes

build/buildctl, build/g11n/build.sh, build/gcc44/build.sh, build/gcc51/build-libgmp.sh, build/illumos/build.sh, build/ipmitool/build.sh, build/kayak-kernel/build.sh, build/kayak/build.sh, build/pci.ids/build.sh, build/perl/build.sh, build/pkg/build.sh, build/studio/sunstudio12.1.p5m, lib/config.sh, lib/functions.sh
`omnios-build` fixes. reference master PR:
https://github.com/omniosorg/omnios-build/pull/13
https://github.com/omniosorg/omnios-build/pull/12
https://github.com/omniosorg/omnios-build/pull/11
https://github.com/omniosorg/omnios-build/pull/8
https://github.com/omniosorg/omnios-build/pull/5
=> r151022 backport/2017070902

build/bind/build.sh, build/curl/build.sh
reference master PR: https://github.com/omniosorg/omnios-build/pull/15
=> r151022 backport/2017070901

.gitignore, build/buildctl
See https://github.com/omniosorg/omnios-build/pull/50
=> Add options for resuming builds after fixing problems (backport to r151022)

build/pkg/build.sh
pkg: Clean up pkg5-localizable publisher
=> pkg: Clean up pkg5-localizable publisher (backport to r151022)

build/illumos/build.sh, lib/functions.sh
By default, ONU publishes packages under the `on-nightly` publisher in the repository which means that after running an end-to-end OmniOS build, the repository looks like the output below, and the build of the `kayak-kernel` package fails because it can't find all of the packages it needs under the omnios publisher.
```
build% pkgrepo -s _repo_22 info
PUBLISHER        PACKAGES STATUS           UPDATED
on-nightly       495      online           2017-07-12T00:49:48.587358Z
omnios           198      online           2017-07-12T02:46:50.429806Z
```
Extra work is then required to move the packages to the correct publisher.
This change modifies the `illumos-gate` package build so that it re-publishes packages under the omnios publisher automatically, resulting in a repository that looks like: …
=> Publish illumos-omnios packages under omnios publisher

build/omnios-build-tools/omnios-build-tools.p5m
Backporting:
PR https://github.com/omniosorg/omnios-build/pull/14 & PR https://github.com/omniosorg/omnios-build/pull/41
=> Add omnios-build-tools package (backport to r151022)

build/kayak-kernel/build.sh
At present, building the `kayak-kernel` package requires that the build be run as root (or with passwordless sudo to root) within the global zone.
This change allows building `kayak-kernel` within a suitably configured non-global zone by modifying the checks to look for whether the expected files are available rather than explicitly checking for running in the global zone.
The zone needs to be specially configured to support this:
```
add fs
set dir=/platform/i86pc/kernel/amd64
set special=/platform/i86pc/kernel/amd64
set type=lofs
set options=ro
add fs
set dir=/boot
set special=/boot
set type=lofs
set options=ro
set fs-allowed=ufs
```
This does not remove the requirement for running as root or with passwordless sudo.
site.sh must also be configured with the name of a target dataset to …
=> Allow kayak-kernel to build within zone

build/kayak-kernel/build.sh
Backporting https://github.com/omniosorg/omnios-build/pull/55
=> Allow kayak-kernel to build within zone (backport to r151022)

build/illumos/build.sh, lib/functions.sh
Backporting https://github.com/omniosorg/omnios-build/pull/54
=> Publish illumos-omnios packages under omnios publisher (backport to r151022)

build/expat/build.sh
release notes: https://github.com/libexpat/libexpat/blob/R_2_2_2/expat/Changes
=> expat: update to version 2.2.2

build/pv/build.sh
Ref: https://github.com/omniosorg/omnios-build/issues/31
```
bloody# pv -V
pv 1.6.6 - Copyright 2015 Andrew Wood <andrew.wood@ivarch.com>
Web site: http://www.ivarch.com/programs/pv.shtml
This program is free software, and is being distributed under the
terms of the Artistic License 2.0.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
=> pv: update to 1.6.1

build/entire/entire.p5m, build/jeos/omnios-userland.p5m, build/sqlite3/build.sh
```shell
hadfl@mars:~/tmp.sqlite3$ cat sqlite.sql 
create table events(timestamp text, description text);
insert into events values(datetime("now"),"First test event");
insert into events values(datetime("now"),"Second test event");
hadfl@mars:~/tmp.sqlite3$ sqlite3 db.sqlite < sqlite.sql 
hadfl@mars:~/tmp.sqlite3$ sqlite3 db.sqlite 
SQLite version 3.19.3 2017-06-08 14:26:16
Enter ".help" for usage hints.
sqlite> select * from events;
2017-07-16 12:13:04|First test event
2017-07-16 12:13:04|Second test event
sqlite> .quit
```
=> sqlite-3: update to 3.19.3

doc/ReleaseNotes.md
Release notes for r151022i, ready for tomorrow.
**Please don't push until the update is made available tomorrow**
=> Update release notes for r151022i

build/iso-codes/build.sh, build/openjdk/build.sh
reference PR: https://github.com/omniosorg/omnios-build/pull/67 https://github.com/omniosorg/omnios-build/pull/69
=> make openjdk and iso-codes ooce aware

build/ipmitool/build.sh, build/ipmitool/patches/configure.patch, build/ipmitool/patches/fix-MAX.patch, build/ipmitool/patches/no-POSIX.patch, build/jeos/omnios-userland.p5m
needs testing. cf. https://github.com/omniosorg/omnios-build/issues/39
```shell
hadfl@mars:~$ ipmitool -V
ipmitool version 1.8.18
hadfl@mars:~$ ipmitool -H x.x.x.x -U ... sensor
Password:
CPU Temp         | 47.000     | degrees C  | ok    | 0.000     | 0.000     | 0.000     | 95.000    | 100.000   | 100.000   
System Temp      | 42.000     | degrees C  | ok    | -9.000    | -7.000    | -5.000    | 80.000    | 85.000    | 90.000    
Peripheral Temp  | 40.000     | degrees C  | ok    | -9.000    | -7.000    | -5.000    | 80.000    | 85.000    | 90.000    
PCH Temp         | 47.000     | degrees C  | ok    | -11.000   | -8.000    | -5.000    | 90.000    | 95.000    | 100.000   
VRM Temp         | 44.000     | degrees C  | ok    | -9.000    | -7.000    | -5.000    | 87.000    | 92.000    | …
```
=> ipmitool: update to 1.8.18

build/jeos/omnios-userland.p5m, build/tmux/build.sh
```
bloody% tmux -V
tmux 2.5
```
=> tmux: upgrade to 2.5

doc/packages.md
This adds a document tracking the packages that make up `omnios-build` along with their current versions and links where updates can be found.
=> add packages.md

build/entire/entire.p5m, build/jeos/omnios-userland.p5m, build/pcre/build.sh, build/pcre/testsuite.log, doc/packages.md
Minor version update to PCRE + addition of testsuite run.
=> pcre: update to 8.41

build/entire/entire.p5m, build/jeos/omnios-userland.p5m, build/nghttp2/build.sh, build/nghttp2/testsuite.log, doc/packages.md
no actual tests in this one but it supports a test suite so I've hooked it in.
=> nghttp2: upgrade to 1.24.0

lib/config.sh
Ensure all packages are built with the same locale.
fixes: https://github.com/omniosorg/omnios-build/issues/43 and https://github.com/omniosorg/omnios-build/issues/9
=> set locale to C

build/kayak-kernel/build.sh
…ore reasonable default boot image location for zones
=> remove checks for binaries as they are now retrieved from miniroot; more reasonable default boot image location for zones

build/bind/build.sh, build/bind/testsuite.log, doc/packages.md
```
hadfl@mars:~$ dig -v
DiG 9.10.6
```
=> bind: update to 9.10.6

build/release/root/etc/release, doc/ReleaseNotes.md
Here are the changes for the r151022k release scheduled for Monday.
Let's not merge until we promote the updated packages on Monday morning.
=> Update release notes and /etc/release for r151022k

build/gtar/build.sh
reference PR: https://github.com/omniosorg/omnios-build/pull/109
=> gtar: Add missing dependencies

build/release/root/etc/release, doc/ReleaseNotes.md
Here are the changes for the r151022l release scheduled for Monday.
Let's not merge until we promote the updated packages.
=> update release notes and /etc/release for r151022l

build/git/build.sh, build/mercurial/build.sh
backport to r22
cf. https://github.com/omniosorg/omnios-build/pull/115
=> security fixes for git/hg (r151022)

build/release/root/etc/release, doc/ReleaseNotes.md
Here are the changes for the r151022m release.
Let's not merge until we promote the updated packages.
=> Update release notes and /etc/release for r151022m

build/entire/entire.p5m, build/jeos/omnios-userland.p5m, build/zsh/build.sh, build/zsh/testsuite.log, doc/packages.md
```
bloody# zsh --version
zsh 5.4.1 (i386-pc-solaris2.11)
```
=> zsh: update to 5.4.1

build/openssl/build.sh
Fix for the directory name in which the pkcs11 engine is located.
=> fix engine location

build/openjdk/build.sh
cf. https://github.com/omniosorg/omnios-build/pull/131
=> openjdk: update openjdk to version 1.7.0_141-b02

build/fio/build.sh, doc/packages.md
```
bloody% fio -version
fio-3.0
```
=> fio: update to 3.0

build/sudo/build.sh, build/sudo/testsuite.log, doc/packages.md
+ add testsuite.
```
bloody% sudo -V
Sudo version 1.8.21
Sudoers policy plugin version 1.8.21
Sudoers file grammar version 46
Sudoers I/O plugin version 1.8.21
```
=> sudo: update to 1.8.21

build/isc-dhcp/build.sh, doc/packages.md
=> isc dhcp: update to 4.3.6

build/expat/build.sh, build/expat/testsuite.log, doc/packages.md
=> expat: update to 2.2.4

build/release/root/etc/release, doc/ReleaseNotes.md
Release notes for next Monday's release.
Please don't merge before we do the release.
=> Update release notes for r151022o

build/jeos/build-userland.sh
Fix small typo in jeos/omnios-userland.
=> Remove stray " in build-userland.sh

build/pkg/build.sh
The code to do this was commented out and marked as 'hugely expensive' - presumably a historic comment based on having to build all of illumos just to grab the updated header files.
It was disabled 6 years ago and the pkg build does not require them.
There are also some minor whitespace/text cleanups here.
=> pkg: remove header file update code

build/illumos/build.sh
PR https://github.com/omniosorg/illumos-omnios/pull/44 changes  `illumos-omnios` so that it publishes packages using the `omnios` publisher instead of `on-nightly`.
This means that the post-processing step of changing the publisher can be avoided in `omnios-build`, 
improving build time.
=> Use omnios as the default package publisher

build/python27/setuptools/build.sh
Full build test done with new version.
=> setuptools: update to 36.4.0

build/binutils/patches/CVE-2017-14129.patch, build/binutils/patches/series
http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-14129
=> binutils: fix CVE-2017-14129

build/jeos/omnios-userland.pkg, doc/packages.md
=> setuptools: Update package list and incorporation

build/release/root/etc/release, doc/ReleaseNotes.md
No backports from the weekly merges, so just the one package update for Monday's release unless there is something over the weekend.
As usual, let's not merge until we make the release on Sunday evening/Monday morning.
=> Getting ready for r151022q

doc/ReleaseNotes.md
These are draft release notes for r151024. By adding them to the repository, we can keep them up-to-date each week as we merge upstream changes.
=> Add draft release notes for r151024

build/omnios-build-tools/omnios-build-tools.p5m
see https://github.com/omniosorg/omnios-build/pull/196
=> add coverage-27 to omnios-build-tools (r151022)

doc/ReleaseNotes.md
Some draft release notes updates following this week's upstream merge.
=> Update release notes following weekly merge

build/python27/m2crypto/patches/M2Crypto-crl.patch
fixing regression of m2crypto update
see also https://github.com/omniosorg/pkg5/pull/8
=> fix m2crypto ASN1_TIME

build/omnios-build-tools/omnios-build-tools.p5m
=> add coverage-27 to omnios-build-tools

build/jeos/omnios-userland.p5m
Need to update the consolidation for the new package versions.
=> update userland consolidation for new nss/nspr versions

build/release/root/etc/release, doc/ReleaseNotes.md
Let's not merge until ready to release.
=> Getting ready for r151022r

build/ncurses/build.sh, doc/packages.md
Tested with various curses programs (vim, kvm, less).
=> ncurses: update to 20170916

build/perl/patches/CVE-2017-12837.patch, build/perl/patches/CVE-2017-12883.patch, build/perl/patches/series
see https://github.com/omniosorg/omnios-build/pull/235
=> perl: fixing CVEs (r151022)

build/perl/patches/CVE-2017-12837.patch, build/perl/patches/CVE-2017-12883.patch, build/perl/patches/series
fixing:
- CVE-2017-12837
- CVE-2017-12883
=> perl: fixing CVEs

build/g11n/build.sh, build/illumos-kvm/build.sh, build/illumos/build.sh, build/jeos/build-gate.sh, build/openssl/README, build/pci.ids/build.sh, lib/config.sh, lib/functions.sh
The retab and cleaning of functions.sh causes most of the noise so please see individual commits below.
I've run a complete bloody userland build with these changes in place (+https://github.com/omniosorg/g11n/pull/1)
=> Various miscellaneous build system improvements.

build/jeos/omnios-userland.pkg, build/python27/m2crypto/build.sh, build/python27/portend/build.sh, build/python27/portend/local.mog, doc/packages.md
pkg tests are the same as baseline.
```Total tests:1046 Tests run:1046 Errors:64 Failures:6 Skips:2```
=> Python module updates

build/python27/numpy/build.sh, build/python27/pylint/build.sh, doc/packages.md
`pkg(5)` test suite results according to baseline.
=> python - modules update

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
```
hadfl@mars:/build$ curl -V
curl 7.56.0 (i386-pc-solaris2.11) libcurl/7.56.0 OpenSSL/1.0.2l zlib/1.2.11 nghttp2/1.26.0
Release-Date: 2017-10-04
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy 
```
=> curl: update to 7.56.0

build/curl/build.sh
```
hadfl@r151022:~$ curl -V
curl 7.56.0 (i386-pc-solaris2.11) libcurl/7.56.0 OpenSSL/1.0.2l zlib/1.2.11 nghttp2/1.21.1
Release-Date: 2017-10-04
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy 
```
=> curl: update to 7.56.0 (r151022)

build/jeos/omnios-userland.pkg, build/tmux/build.sh, build/tmux/patches/errno-for-errno.patch, build/tmux/patches/job-libevheader.patch, build/tmux/patches/tmux.h.patch, doc/packages.md
Update + patch re-baseline.
Tested basic functionality and found no problems.
=> tmux: update to 2.6

build/openssh/patches/2001-sftp-readonly.patch, build/openssh/patches/series
see https://github.com/omniosorg/omnios-build/pull/267
=> openssh: sftp-readonly patch

build/release/root/etc/release, doc/ReleaseNotes.md
As per usual, let's hold off merging until we're ready to publish the packages.
=> Getting ready for r151022u

build/ntp/local.mog
see https://github.com/omniosorg/omnios-build/pull/279
=> Allow other packages to overwrite ntp.conf (r151024)

build/openjdk/build.sh
The Java build is very noisy to stdout so this PR fixes that so that the verbose output ends up in the log file (as it did before) but stdout is cleaner.
It also stops building documentation (Japanese man pages)
and although the build was previously parallelised, it only used two jobs. Change that to use the calculated number of jobs (based on CPU count, calculated in config.sh).
Java build is now down to 20 minutes on my server - about twice as fast as before.
I'll backport this to r151024 too.
=> jdk: less on stdout, parallelise, no docs

build/openjdk/build.sh
see: https://github.com/omniosorg/omnios-build/pull/286
=> jdk: less on stdout, parallelise, no docs (r151024)

.gitignore, build/buildctl, build/gcc5/common.sh, build/gcc6/common.sh, lib/functions.sh
see: https://github.com/omniosorg/omnios-build/pull/287
=> Support building in multiple parallel threads (r151024)

build/ncurses/build.sh
backport for https://github.com/omniosorg/omnios-build/pull/295
=> ncurses: update to 6.0-20171014 (r151024)

build/ncurses/patches/series, build/ncurses/patches/xterm-no-rep.patch
backport for https://github.com/omniosorg/omnios-build/pull/297
=> remove "rep" from xterm

doc/ReleaseNotes.md
+ a couple of fixes for previous upgrades that were missed in the release notes.
=> Update release notes following merges

build/illumos-kvm/build.sh, lib/site.sh
=> Move KVM locking revisions to illumos-kvm/

build/illumos-kvm/build.sh, lib/site.sh
Since KVM has moved ahead of what r151022 supports.
=> Lock KVM to a specific revision (r151022)

build/illumos-kvm/build.sh, lib/site.sh
=> Move KVM locking revisions to illumos-kvm/ (r151024)

build/curl/build.sh, build/curl/testsuite.log, doc/baseline, doc/packages.md
=> curl: update to 7.56.1

build/curl/build.sh
see: https://github.com/omniosorg/omnios-build/pull/313
=> curl: update to version 7.56.1 (r151022)

build/curl/build.sh, build/curl/testsuite.log, doc/baseline
see: https://github.com/omniosorg/omnios-build/pull/313
=> curl: update to version 7.56.1 (r151024)

build/buildctl
=> Report illumos stage during parallel build (r151024)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Getting ready for r151022w

build/screen/build.sh, doc/baseline, doc/packages.md
and add check that ncurses was properly picked up.
=> screen: update to 4.6.2

build/autoconf/build.sh, build/bash/build.sh, build/diffutils/build.sh, build/findutils/build.sh, build/gawk/build.sh, build/gettext/build.sh, build/gnu-make/build.sh, build/grep/build.sh, build/groff/build.sh, build/gtar/build.sh, build/prerequisite-gnu/gnu.p5m, build/sed/build.sh
and fix group ownership on `/usr/gnu/share` to match existing packages.
=> Use fully-qualified FMRI for prerequisite/gnu

build/wget/build.sh, build/wget/testsuite.log, doc/baseline, doc/packages.md
Fixes: CVE-2017-13089, CVE-2017-13090
=> wget: update to 1.19.2

build/wget/build.sh
=> wget: update to 1.19.2 (r151022)

build/wget/build.sh, doc/baseline
=> wget: update to 1.19.2 (r151024)

build/release/root/etc/release, doc/ReleaseNotes.md
The openssh fix that was in r151022u has been allocated a CVE now so I've added that in too.
Please don't merge until we're ready to promote the packages on Sunday evening.
=> Preparing for r151022x

doc/ReleaseNotes.md
Updating the release notes ready for Monday.
NSS/NSPR were recently updated in r151022 so the package version changes for these have been removed too.
=> Preparing for r151024 release

doc/ReleaseNotes.md
=> Adding help wanted section

build/openssl/build.sh, build/openssl/testsuite.1.0.log, build/openssl/testsuite.log, doc/baseline
=> openssl: update to 1.0.2m / 1.1.0g  (r151024)

doc/ReleaseNotes.md
minor changes to release notes.
=> Change release date + add illumos issue for iscsi

build/bmake/build.sh, doc/baseline, doc/packages.md
```
hadfl@mars:/build$ bmake -V MAKE_VERSION
20171028
```
=> bmake: update to 20171028

build/entire/entire.p5m, build/jeos/omnios-userland.pkg, build/nghttp2/build.sh, build/nghttp2/testsuite.log, build/python27/cffi/build.sh, build/python27/coverage/build.sh, build/python27/cryptography/build.sh, build/python27/enum/build.sh, build/python27/enum/local.mog, build/python27/lxml/build.sh, build/python27/pytz/build.sh, build/python27/setuptools/build.sh, build/python27/simplejson/build.sh, doc/baseline, doc/packages.md
`pkg(5)` test suite results according to baseline.
=> Package updates

build/buildctl, doc/baseline, tools/test
=> Backport improvements to baseline check process.

doc/sync-upstream-detail.md, doc/sync-upstream.md
Note that the manual command and output are still in the detailed version of this document - sync-upstream-detail.md
=> Add omni pull_request

build/openssh/build.sh
see: https://github.com/omniosorg/omnios-build/pull/398
=> man page illumos numbering (r151024)

build/entire/entire.p5m, build/jeos/omnios-userland.pkg, build/python27/cheroot/build.sh, build/python27/cheroot/local.mog, build/python27/pyopenssl/build.sh, build/python27/setuptools/build.sh, doc/packages.md
pkg testsuite is passing with these updates.
=> Python module updates.

build/autoconf/build.sh, build/automake/build.sh, build/bind/build.sh, build/buildctl, build/coreutils/build.sh, build/curl/build.sh, build/diffutils/build.sh, build/findutils/build.sh, build/gettext/build.sh, build/gnu-make/build.sh, build/grep/build.sh, build/gtar/build.sh, build/m4/build.sh, build/sed/build.sh, build/sigcpp/build.sh, build/wget/build.sh, build/zsh/build.sh, lib/functions.sh
Re-structure flags for child build.sh processes.
=> Add -t flag for skipping the test-suite.

build/vim/patches/8.0.1263-CVE-2017-17087, build/vim/patches/series
=> vim: Fix CVE-2017-17087 (r151022)

build/sudo/build.sh, build/sudo/patches/audit-event.patch, build/sudo/patches/printflike.patch, build/sudo/patches/sudo_edit.c.patch
see: https://github.com/omniosorg/omnios-build/pull/420
=> sudo: enhanced patchset (r24)

build/release/root/etc/release, doc/ReleaseNotes.md
Let's not merge until ready tomorrow.
=> Preparing for r151024e

build/release/root/etc/release, doc/ReleaseNotes.md
Let's not merge this until ready for release tomorrow.
=> Preparing for r151022ac

build/openssl/build.sh, build/release/root/etc/release, doc/ReleaseNotes.md
Please don't merge until packages are published.
=> Preparing for early r151022ad

build/openssl/build.sh, build/release/root/etc/release, doc/ReleaseNotes.md
Please don't merge until ready to release.
=> Preparing for early r151024f

build/openssl/build.sh, doc/packages.md
Backports already done as #432 & #431
=> openssl: update to 1.0.2n

build/mozilla-nss-nspr/patches/sse-align.patch
=> nss: Force alignment for gcm_HashMult_hw

build/mozilla-nss-nspr/patches/sse-align.patch
=> nss: Force alignment for gcm_HashMult_hw (r151024)

build/openjdk/build.sh, doc/packages.md
```
hadfl@mars:~$ java -version
openjdk version "1.7.0_161"
OpenJDK Runtime Environment (build 1.7.0_161-b01)
OpenJDK Server VM (build 24.161-b01, mixed mode)
```
=> openjdk: update to 1.7.0_161-b01

build/cpuid/build.sh, build/cpuid/local.mog, build/cpuid/patches/platform.h.patch, build/cpuid/patches/series, build/cpuid/patches/threads.c.patch, build/jeos/omnios-userland.pkg, doc/baseline, doc/packages.md
given the recent CPU issues a CPUID decoder might be useful.
=> cpuid added

build/jeos/omnios-userland.pkg, build/libmpfr/build.sh, build/libmpfr/testsuite.log, doc/packages.md
bulding `libmpc` is broken with `libmpfr` 4.x
=> libmpfr 4.x on-hold

build/release/root/etc/release, doc/ReleaseNotes.md
Ready for Monday. Please don't merge until release.
=> Preparing for r151024j

build/ncurses/build.sh, doc/packages.md
Have done basic testing with screen, vim & sysstat
=> ncurses: update to 6.0-20180106

build/bind/build.sh
=> bind: update to 9.10.6-P1 (r151024)

build/gzip/build.sh, build/gzip/local.mog, lib/functions.sh
Move script to lines in local.mog
Resolve non-deterministic resolution of gunzip<->uncompress hardlink
pkgdiff shows no changes between current and new gzip package.
=> Simplify gzip build script

build/cpuid/build.sh
=> cpuid: update to 1.6.1 (r151024)

build/cpuid/build.sh
=> cpuid: update to 1.6.1 (r151022)

build/release/root/etc/release, doc/ReleaseNotes.md
Getting ready for release on Monday. Please don't merge until everything is in place.
=> Preparing for r151024l

build/release/root/etc/release, doc/ReleaseNotes.md
Please review but don't merge until we're ready for release.
=> Preparing for r151022aj

doc/ReleaseNotes.md
Wrong bug number was referenced.
=> Fix release-notes typo

build/sudo/build.sh, build/sudo/testsuite.log, doc/packages.md
```
hadfl@mars:~$ sudo --version
Sudo version 1.8.22
Sudoers policy plugin version 1.8.22
Sudoers file grammar version 46
Sudoers I/O plugin version 1.8.22
```
=> sudo: update to 1.8.22

build/ca-bundle/build.sh
Bringing CA certificates up-to-date.
=> ca-bundle: update to nss 3.35 (r151022)

build/release/root/etc/release, doc/ReleaseNotes.md
Please don't merge until we're ready.
=> Preparing for r151022ak

build/release/root/etc/release, doc/ReleaseNotes.md
As per usual, please review but do not merge until we are ready to release.
=> Preparing for r151024m

build/p7zip/patches/CVE-2017-17969.patch, build/p7zip/patches/series
=> p7zip: Fix for CVE-2017-17969

build/patch/patches/CVE-2018-6951.patch, build/patch/patches/series
=> gpatch: fix CVE-2018-6951

build/release/root/etc/release, doc/ReleaseNotes.md
Getting ready for Monday, please don't merge.
=> Preparing for r151022ao

build/release/root/etc/release, doc/ReleaseNotes.md
Getting ready for Monday - please don't merge.
=> Preparing for r151024q

build/isc-dhcp/build.sh
=> dhcp: update to 4.3.6-P1 (r151022)

build/libxml2/build.sh, build/libxml2/testsuite.log, doc/packages.md
Waiting for release announcement before determining backport status.
=> libxml2: update to 2.9.8

build/bhyve-fw/build.sh
Allow selection of specific versions to build via -f
=> bhyve: Select more verbose debug level for debug firmware.

build/python27/tempora/local.mog
=> tempora: drop test-suite

build/jeos/omnios-userland.pkg, build/python27/tempora/build.sh, doc/packages.md
pkg test suite ran successfully with updated version.
=> tempora: update to 1.11

build/release/root/etc/release, doc/ReleaseNotes.md
Initial release notes for next week's release. Please don't merge.
=> Preparing for r151022ar

build/release/root/etc/release, doc/ReleaseNotes.md
Initial release notes for next week's release. Please don't merge.
=> Preparing for r151024t

build/entire/entire.pkg, build/jeos/omnios-userland.pkg, build/python27/cryptography/build.sh, build/python27/setuptools/build.sh, doc/packages.md
All python modules build successfully after this update and the pkg5 test suite completes successfully once the certificates are fixed (see https://github.com/omniosorg/pkg5/pull/38)
=> Python module update.

build/git/build.sh, doc/packages.md
... and fix more hardlink targets.
=> git: update to 2.16.3

build/bhyve-fw/build.sh, build/g11n/build.sh, build/kayak-kernel/build.sh, build/kayak-kernel/kayak-kernel.mog, build/kayak-kernel/sudo-bits.sh, build/kayak/build.sh, build/pkg/build.sh, lib/config.sh, lib/functions.sh
and centralise the common git checkout code from kayak, g11n, pkg & bhyve-fw
=> Update kayak & kayak-kernel for new kayak layout

build/openssl/build.sh
see: https://github.com/omniosorg/omnios-build/pull/641
=> openssl: update to 1.0.2o (r151022)

build/openssl/build.sh, build/openssl/testsuite.1.0.log, build/openssl/testsuite.log
see: https://github.com/omniosorg/omnios-build/pull/641
=> openssl: update to 1.1.0h/1.0.2o (r151024)

build/release/root/etc/release, doc/ReleaseNotes.md
release notes for this week's late release. please don't merge, yet.
=> preparing for r151022as

build/release/root/etc/release, doc/ReleaseNotes.md
release notes for this week's late release. please don't merge, yet.
=> preparing for r151024u

build/ncurses/build.sh, doc/packages.md
Last update before branching for r151026.
=> ncurses: update to 6.1.20180331

lib/functions.sh
to be able to switch branches we need to clone all available branches.
needs backporting to r26
=> clone all branches

build/illumos-kvm/kvm.mog
=> Fix KVM variants to allow r24->r26 upgrade (r151026)

build/sqlite3/build.sh, doc/packages.md
=> sqlite3: update to 3.23.1

build/release/root/etc/release, doc/ReleaseNotes.md
Please don't merge until we're ready to release.
=> Preparing for r151022av

build/zsh/build.sh
=> zsh: update to 5.5.1 (r151026)

build/fio/build.sh, doc/packages.md, lib/config.sh, lib/functions.sh
=> fio: update to 3.6

build/python27/pytz/build.sh, doc/packages.md
=> pytz: update to 2018.4

build/openssh/files/ssh.xml, build/openssh/files/sshd
SMF ipfilter does not work with ssh (r151026)
=> SMF ipfilter does not work with ssh (r151026)

build/openssh/files/ssh.xml, build/openssh/files/sshd
SMF ipfilter does not work with ssh (r151024)
=> SMF ipfilter does not work with ssh (r151024)

build/openssh/files/ssh.xml, build/openssh/files/sshd-method
SMF ipfilter does not work with ssh (r151022)
=> SMF ipfilter does not work with ssh (r151022)

build/release/build.sh
Drop 1510* prefix from version
=> Drop 1510* prefix from version

build/release/build.sh
Drop 1510* prefix from version (r151026)
=> Drop 1510* prefix from version (r151026)

lib/config.sh
Adjust package comparison URL for r151026 (r151026)
=> Adjust package comparison URL for r151026

build/xz/build.sh, doc/packages.md
=> xz: update to 5.2.4

lib/functions.sh
When downloading a source file from https://mirrors.omniosce.org/ we should also fetch and automatically verify the associated checksum file.
Following this change, we'll need to always provide a .sha256 file containing the checksum with any new files rather than the mix of things we had (which have now been removed and replaced).
We will continue to validate the downloads against the source site as we do now, using whatever method they provide, when we add them to the mirrors site.
=> Verify the checksum of downloaded source

build/sudo/build.sh, build/sudo/local.mog, doc/packages.md
=> sudo: update to 1.8.23

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for release r151024z

build/release/root/etc/release, doc/ReleaseNotes.md
until we're ready for release.
=> Preparing for release r151022ax

doc/ReleaseNotes.md
=> update release notes for r151022ax

doc/ReleaseNotes.md
=> Update r26 release notes ready for release.

build/p7zip/patches/CVE-2016-9296.patch, build/p7zip/patches/CVE-2017-17969.patch, build/p7zip/patches/CVE-2018-10115.patch, build/p7zip/patches/bash.patch, build/p7zip/patches/makefile.patch, build/p7zip/patches/series
p7zip - add patch for CVE-2018-10115 (r151022)
=> p7zip - add patch for CVE-2018-10115 (r151022)

build/p7zip/patches/CVE-2016-9296.patch, build/p7zip/patches/CVE-2017-17969.patch, build/p7zip/patches/CVE-2018-10115.patch, build/p7zip/patches/bash.patch, build/p7zip/patches/makefile.patch, build/p7zip/patches/series, build/p7zip/testsuite.log
p7zip - add patch for CVE-2018-10115 (r151024)
=> p7zip - add patch for CVE-2018-10115 (r151024)

build/p7zip/patches/CVE-2016-9296.patch, build/p7zip/patches/CVE-2017-17969.patch, build/p7zip/patches/CVE-2018-10115.patch, build/p7zip/patches/bash.patch, build/p7zip/patches/makefile.patch, build/p7zip/patches/series, build/p7zip/testsuite.log
p7zip - add patch for CVE-2018-10115 (r151026)
=> p7zip - add patch for CVE-2018-10115 (r151026)

build/p7zip/patches/CVE-2016-9296.patch, build/p7zip/patches/CVE-2017-17969.patch, build/p7zip/patches/CVE-2018-10115.patch, build/p7zip/patches/bash.patch, build/p7zip/patches/makefile.patch, build/p7zip/patches/series, build/p7zip/testsuite.log
p7zip - add patch for CVE-2018-10115
=> p7zip - add patch for CVE-2018-10115

build/p7zip/patches/CVE-2018-10115.patch, build/p7zip/patches/CVE-2018-5996.patch, build/p7zip/patches/series
p7zip: patch for CVE-2018-5996
=> p7zip: patch for CVE-2018-5996

build/p7zip/patches/CVE-2018-10115.patch, build/p7zip/patches/CVE-2018-5996.patch, build/p7zip/patches/series
p7zip: patch for CVE-2018-5996 (r151022)
=> p7zip: patch for CVE-2018-5996 (r151022)

doc/ReleaseNotes.md
Update release notes with rc2 kernel hash (r151026)
=> Update release notes with rc2 kernel hash (r151026)

build/ncurses/build.sh
ncurses: update to 6.1.20180428 (r151026)
=> ncurses: update to 6.1.20180428 (r151026)

build/wget/build.sh, build/wget/patches/nofuzz.patch, build/wget/patches/series, doc/packages.md
=> wget: update to 1.19.5

build/wget/build.sh, build/wget/patches/nofuzz.patch, build/wget/patches/series
wget: update to 1.19.5 (r151026)
=> wget: update to 1.19.5 (r151026)

build/wget/build.sh
wget: update to 1.19.5 (r151024)
=> wget: update to 1.19.5 (r151024)

build/wget/build.sh
wget: update to 1.19.5 (r151022)
=> wget: update to 1.19.5 (r151022)

build/release/root/etc/release, doc/ReleaseNotes.md
This is next Monday's release.
=> Preparing for release r151022ay

build/release/root/etc/release, doc/ReleaseNotes.md
This is next Monday's release.
=> Preparing for release r151024aa

build/perl/build.sh
Fixes our 32-bit perl build to work with gcc7, specifically through `-Dlibs="-lsocket -lnsl -lm -lc -lgcc_s"` which adds libgcc_s to provide _udivvmod64_ and friends. That line also removes a couple of unnecessary filter libraries that would otherwise have been added (-lpthread, -ldl).
Additionally I have restructured the build script to fit better with the framework - overriding configure*() functions for the custom perl configuration and still using the standard build*() functions.
Tested on bloody - only difference in the package is a new dependency on gcc-runtime as expected.
=> Use gcc7 for perl build. Restructure build script.

build/acpica/build.sh, doc/packages.md
=> acpica: update to 20180508

build/nghttp2/build.sh, build/nghttp2/testsuite.log, doc/packages.md
=> nghttp2: update to 1.32.0

build/entire/entire.pkg, build/jeos/omnios-userland.pkg, build/libidn/build.sh, doc/packages.md
=> libidn: update to 1.35

lib/config.sh, lib/functions.sh
More environment cleanups for build environment
=> More environment cleanups for build environment

build/cdrtools/patches/detect-gcc.patch, build/cdrtools/patches/series
Fix cdrtools gcc compiler detection
=> Fix cdrtools gcc compiler detection

build/mozilla-nss-nspr/patches/series, build/mozilla-nss-nspr/patches/shadowing.patch
This fixes a shadowing variable error in pkcs11.c
=> fix shadowing issue in pkcs11.c

build/curl/build.sh, build/curl/testsuite.log, build/openssl/patches/rehash.patch, build/openssl/patches/series, build/python27/pycurl/patches/openssl11.patch, build/python27/pycurl/patches/series, doc/packages.md
curl: update to 7.60.0
and fix some fallout from the switch to openssl 1.1
=> curl: update to 7.60.0

build/curl/build.sh
curl: update to 7.60.0 (r151026)
=> curl: update to 7.60.0 (r151026)

build/curl/build.sh
curl: update to 7.60.0 (r151024)
=> curl: update to 7.60.0 (r151024)

build/curl/build.sh
curl: update to 7.60.0 (r151022)
=> curl: update to 7.60.0 (r151022)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for release r151022ba (r151022)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for release r151024ac (r151024)

lib/functions.sh
Ignore whitespace when rebasing patches
=> Ignore whitespace when rebasing patches

build/bmake/build.sh, doc/packages.md
=> bmake: update to 20180512

build/mozilla-nss-nspr/build.sh, doc/packages.md
=> nss: update to 3.37.1

build/bison/build.sh, build/bison/testsuite.log, doc/packages.md
=> bison: update to 3.0.5

build/iso-codes/build.sh, build/jeos/omnios-userland.pkg, doc/packages.md
=> iso-codes: update to 3.79

build/git/build.sh
git: update to 2.13.7 (r151022)
=> git: update to 2.13.7 (r151022)

build/git/build.sh
git: update to 2.14.4 (r151024)
=> git: update to 2.14.4 (r151024)

build/git/build.sh
git: update to 2.17.1 (r151026)
=> git: update to 2.17.1 (r151026)

build/git/build.sh, build/git/testsuite.log, doc/packages.md
=> git: update to 2.17.1

build/gcc7/local.mog, build/gcc8/local.mog
Make gcc version 7 the default
=> Make gcc version 7 the default

build/openjdk/build.sh, build/openjdk/patches/hotspot-ccsbins.patch, build/openjdk/patches/jdk-fixes.patch, build/openjdk/patches/series, doc/packages.md
```
hadfl@mars:~$ java -version
openjdk version "1.7.0_181"
OpenJDK Runtime Environment (build 1.7.0_181-b01)
OpenJDK Server VM (build 24.181-b01, mixed mode)
```
=> openjdk: update to 1.7.0_181-b01

build/release/root/etc/release, doc/ReleaseNotes.md
Preparing for release r151022bc (r151022)
=> Preparing for release r151022bc (r151022)

build/release/root/etc/release, doc/ReleaseNotes.md
Preparing for release r151024ae (r151024)
=> Preparing for release r151024ae (r151024)

build/bash/build.sh, build/bash/patches/bash-4.4-patches/bash44-020, build/bash/patches/bash-4.4-patches/bash44-021, build/bash/patches/bash-4.4-patches/bash44-022, build/bash/patches/bash-4.4-patches/bash44-023, build/bash/patches/series, doc/packages.md
=> bash: update to 4.4.23

build/acpica/build.sh, doc/packages.md
=> acpica: update to 20180531

build/ntpsec/build.sh, doc/packages.md
ntpsec: update to version 1.1.1
=> ntpsec: update to version 1.1.1

build/rsync/build.sh
Switch rsync to 64-bit and enable optimisation. This more than doubles the speed of the checksumming code (r151026)
=> Switch rsync to 64-bit and enable optimisation. This more than doubles the speed of the checksumming code (r151026)

build/illumos-kvm/build.sh
Required to support KPTI and Eager FPU - see https://github.com/omniosorg/illumos-omnios/pull/227
=> Update KVM version to latest Joyent HEAD (r151022)

build/XML::Parser/build.sh, build/python27/asn1crypto/build.sh, build/python27/cffi/build.sh, build/python27/cheroot/build.sh, build/python27/cherrypy/build.sh, build/python27/coverage/build.sh, build/python27/cryptography/build.sh, build/python27/enum/build.sh, build/python27/functools32/build.sh, build/python27/idna/build.sh, build/python27/ipaddress/build.sh, build/python27/jsonrpclib/build.sh, build/python27/jsonschema/build.sh, build/python27/lxml/build.sh, build/python27/m2crypto/build.sh, build/python27/mako/build.sh, build/python27/numpy/build.sh, build/python27/ply/build.sh, build/python27/portend/build.sh, build/python27/pybonjour/build.sh, build/python27/pycurl/build.sh, build/python27/pylint/build.sh, build/python27/pyopenssl/build.sh, build/python27/pyrex/build.sh, build/python27/pytz/build.sh, build/python27/setuptools/build.sh, build/python27/simplejson/build.sh, build/python27/six/build.sh, build/python27/tempora/build.sh, build/python27/typing/build.sh
Restructuring mirrors download area (r151024)
=> Restructuring mirrors download area (r151024)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151024ai (r151024)

build/mercurial/build.sh, doc/packages.md
=> mercurial: update to 4.6.2

doc/baseline
Update baseline following python3 integration
=> Update baseline following python3 integration

build/gcc-runtime/build-runtime++.sh, build/gcc-runtime/build-runtime.sh, build/gcc-runtime/build-runtimef.sh, lib/functions.sh
Full build was successful with this change.
=> Check all packages for dangling symlinks

build/jeos/omnios-userland.pkg, build/pciutils/build.sh, doc/packages.md
=> pciutils: update to 3.6.0

build/coreutils/build.sh, build/coreutils/patches/series, build/coreutils/patches/sys-limits.patch, build/coreutils/testsuite.log, doc/packages.md
=> coreutils: update to 8.30

build/openssl/build.sh, build/openssl/local.mog
Create /etc/ssl/certs so that symlink checker is satisfied
=> Create /etc/ssl/certs so that symlink checker is satisfied

build/curl/build.sh
curl: update to 7.61.0 (r151022)
=> curl: update to 7.61.0 (r151022)

build/curl/build.sh
curl: update to 7.61.0 (r151024)
=> curl: update to 7.61.0 (r151024)

build/curl/build.sh
curl: update to 7.61.0 (r151026)
=> curl: update to 7.61.0 (r151026)

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
=> curl: update to 7.61.0

.travis.yml, build/bind/build.sh
bind: update to 9.10.8 (r151022)
=> bind: update to 9.10.8 (r151022)

.travis.yml, build/bind/build.sh
bind: update to 9.10.8 (r151024)
=> bind: update to 9.10.8 (r151024)

build/bhyve-fw/build.sh
At present, our "release" firmware images are too verbose. Changing their debug level down to INFO and putting the output on COM2.
=> Adjust debug port and verbosity for release/debug firmwares

build/pciutils/build.sh, doc/packages.md
=> pciutils: update to 3.6.1

build/ncurses/build.sh, doc/packages.md
=> ncurses: update to 20180707

build/acpica/build.sh, doc/packages.md
=> acpi: update to 20180629

build/pkg/build.sh, doc/baseline
Add new brand/bhyve and brand/kvm packages
Take the opportunity to clean up and simplify the build script.
=> Add new brand/bhyve and brand/kvm packages

build/binutils/build.sh, doc/packages.md
=> binutils: update to 2.31

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151024ak

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022bi

build/release/local.mog
=> Add ooce prefix to release/name properties (r151026)

build/binutils/build.sh, doc/packages.md
=> binutils: update to 2.31.1

build/ca-bundle/build.sh
Remove text representations from cacert.pem (r151022)
=> Remove text representations from cacert.pem (r151022)

build/ca-bundle/build.sh
Remove text representations from cacert.pem (r151024)
=> Remove text representations from cacert.pem (r151024)

build/ca-bundle/build.sh
Remove text representations from cacert.pem (r151026)
=> Remove text representations from cacert.pem (r151026)

doc/ReleaseNotes.md
Seems light - what have I missed?
=> Update draft release notes

doc/ReleaseNotes.md
A couple of small edits after proof reading.
=> Improve release notes regarding auto-be-name

build/python27/prettytable/build.sh, build/python35/prettytable/build.sh, doc/packages.md
=> prettytable: update to 0.7.2

build/prerequisite-gnu/gnu.p5m, build/python27/obsolete/extra.p5m, build/python27/obsolete/lxml.p5m, build/python27/obsolete/numpy.p5m, build/python27/obsolete/pylint.p5m, build/python27/obsolete/pyrex.p5m, build/python27/obsolete/typing.p5m, build/release/notices.p5m, build/studio/sunstudio12.1.p5m, build/sunpro/sunpro.p5m
Clean up use of legacy attributes
=> Clean up use of legacy attributes

build/release/root/etc/release, doc/ReleaseNotes.md
until we are ready to release.
=> Preparing for r151022bk

build/illumos-kvm/build.sh
see: https://github.com/omniosorg/illumos-omnios/pull/248
=> kvm: OS-7090 GDT limit reset to 0xffff

build/unixodbc/build.sh, doc/packages.md
=> unixodbc: update to 2.3.7

build/acpica/build.sh, doc/packages.md
=> acpica: update to 20180810

build/python27/jsonschema/build.sh, build/python35/README
Add missing functools32 dependency
=> Add missing functools32 dependency

build/ntp/build.sh
ntp: update to 4.2.8p12 (r151022)
=> ntp: update to 4.2.8p12 (r151022)

build/ntp/build.sh
ntp: update to 4.2.8p12 (r151024)
=> ntp: update to 4.2.8p12 (r151024)

build/ntp/build.sh
ntp: update to 4.2.8p12 (r151026)
=> ntp: update to 4.2.8p12 (r151026)

build/openssl/build.sh
openssl: update to 1.0.2p/1.1.0i (r151024)
=> openssl: update to 1.0.2p/1.1.0i (r151024)

build/ntp/build.sh, build/ntp/patches/etcfix.patch, build/ntp/patches/ins-ntpd.patch, build/ntp/patches/no-arc4random-addrandom.patch, build/ntp/patches/noextra.patch, build/ntp/patches/series, build/ntp/patches/timing.patch, doc/packages.md
=> ntp: update to 4.2.8p12

build/openssl/build.sh, build/openssl/patches-1.0/opensslconf.patch, build/openssl/patches-1.0/pkcs11.patch, build/openssl/patches-1.0/series, build/openssl/patches-1.0/unused-dep.patch, build/openssl/patches/libs.patch, build/openssl/testsuite.log
openssl: update to 1.0.2p/1.1.0i (r151026)
=> openssl: update to 1.0.2p/1.1.0i (r151026)

build/openssl/build.sh
openssl: update to 1.0.2p (r151022)
=> openssl: update to 1.0.2p (r151022)

build/pciutils/build.sh, doc/packages.md
=> pciutils: update to 3.6.2

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151024ao (r151024)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022bm (r151022)

build/openssh/patches/CVE-2018-15473.patch, build/openssh/patches/series
openssh: patch for CVE-2018-15473 (r151022)
=> openssh: patch for CVE-2018-15473 (r151022)

build/openssh/patches/CVE-2018-15473.patch, build/openssh/patches/series
openssh: patch for CVE-2018-15473 (r151024)
=> openssh: patch for CVE-2018-15473 (r151024)

build/openssh/patches/CVE-2018-15473.patch, build/openssh/patches/series
openssh: patch for CVE-2018-15473 (r151026)
=> openssh: patch for CVE-2018-15473 (r151026)

build/openssh/patches/CVE-2018-15473.patch, build/openssh/patches/series
openssh: patch for CVE-2018-15473
=> openssh: patch for CVE-2018-15473

build/expat/build.sh, build/expat/testsuite.log, doc/packages.md
=> expat: update to 2.2.6

build/ncurses/build.sh, build/ncurses/patches/extra-newline.patch, build/ncurses/patches/xterm-no-rep.patch, doc/packages.md
=> ncurses: update to 20180818

build/release/root/etc/release, doc/ReleaseNotes.md
Preparing for r151024ap (r151024)
=> Preparing for r151024ap (r151024)

build/release/root/etc/release, doc/ReleaseNotes.md
Preparing for r151022bn (r151022)
=> Preparing for r151022bn (r151022)

build/ipmitool/build.sh, build/ipmitool/patches/7052161.patch, build/ipmitool/patches/configure.patch, build/ipmitool/patches/fix-MAX.patch, build/ipmitool/patches/ipmievd.local4.patch, build/ipmitool/patches/no-POSIX.patch, build/ipmitool/patches/openssl11.patch, build/ipmitool/patches/series, build/ipmitool/patches/v6-noaddr16.patch, doc/packages.md
Also, development has moved to github so adjust packages URL.
=> ipmitool: Patch to build with openssl 1.1

build/iso-codes/build.sh, build/jeos/omnios-userland.pkg, build/meta/omnios-build-tools.p5m, build/nghttp2/build.sh, build/nghttp2/testsuite.log, doc/packages.md
=> Update iso-codes and nghttp2 packages

build/cpuid/build.sh
cpuid: update to 1.6.5 (r151022)
=> cpuid: update to 1.6.5 (r151022)

build/cpuid/build.sh
cpuid: update to 1.6.5 (r151024)
=> cpuid: update to 1.6.5 (r151024)

build/bison/build.sh, build/bison/local.mog, build/bison/testsuite.log, build/jeos/omnios-userland.pkg, doc/packages.md
=> bison: update to 3.1

doc/baseline
=> Update package baseline

build/mozilla-nss-nspr/build.sh, build/mozilla-nss-nspr/patches/endian.patch, build/mozilla-nss-nspr/patches/nss-makefile.patch, build/mozilla-nss-nspr/patches/nss-modernize.patch, build/mozilla-nss-nspr/patches/shadowing.patch, build/mozilla-nss-nspr/patches/sse-align.patch, doc/packages.md
=> nss/nspr: update to 3.39/4.20

build/zsh/patches/CVE-2018-0502,13259.patch, build/zsh/patches/series
zsh: add patches for CVE-2018-0502,13259 (r151026)
=> zsh: add patches for CVE-2018-0502,13259 (r151026)

build/zsh/patches/CVE-2018-0502,13259.patch, build/zsh/patches/series
zsh: add patches for CVE-2018-0502,13259 (r151024)
=> zsh: add patches for CVE-2018-0502,13259 (r151024)

build/zsh/patches/CVE-2018-0502,13259.patch, build/zsh/patches/series
zsh: add patches for CVE-2018-0502,13259 (r151022)
=> zsh: add patches for CVE-2018-0502,13259 (r151022)

build/sudo/build.sh, build/sudo/patches/Makefile.in.patch, build/sudo/patches/audit-event.patch, build/sudo/testsuite.log, doc/packages.md
=> sudo: update to 1.8.25

build/mercurial/build.sh, doc/packages.md
=> mercurial: update to 4.7.1

build/cpuid/build.sh, doc/packages.md
=> cpuid: update to 1.7.0

build/git/build.sh, build/git/testsuite.log, doc/packages.md
=> git: update to 2.19.0

build/fio/build.sh, doc/packages.md
=> fio: update to 3.10

build/zsh/build.sh, build/zsh/testsuite.log, doc/packages.md
=> zsh: update to 5.6.2

build/sudo/build.sh, doc/packages.md
=> sudo: update to 1.8.25p1

build/cpuid/build.sh, doc/packages.md
=> cpuid: update to 1.7.1

build/python35/build.sh
Python3 package misses version number
=> Python3 package misses version number

lib/functions.sh
=> Return explicit success status (r151026)

build/illumos-kvm/build.sh
export CTFCONVERT to allow utility to be found
=> export CTFCONVERT to allow utility to be found

doc/packages.md
=> Fix cherrypy-27 link

build/gcc.obs/g++4-obs.p5m, build/gcc.obs/gcc4-obs.p5m, build/gcc.obs/runtime-g++5-obsolete.p5m, build/gcc.obs/runtime-g++6-obsolete.p5m, build/gcc.obs/runtime-gcc5-obsolete.p5m, build/gcc.obs/runtime-gcc6-obsolete.p5m, build/prerequisite-gnu/gnu.p5m, build/python27/obsolete/extra.p5m, build/python27/obsolete/lxml.p5m, build/python27/obsolete/m2crypto.p5m, build/python27/obsolete/numpy.p5m, build/python27/obsolete/pylint.p5m, build/python27/obsolete/pyrex.p5m, build/python27/obsolete/typing.p5m, build/sunpro/sunpro.p5m
Use @PVER@ in manifests rather than 0.@RELVER@
=> Use @PVER@ in manifests rather than 0.@RELVER@

build/sqlite3/build.sh, doc/packages.md
=> sqlite3: update to 3.25.1

build/g11n/build.sh
Build g11n with new dashrev order
=> Build g11n with new dashrev order

doc/ReleaseNotes.md
As we approach the freeze for r151028, updating the release notes with things we missed during r151027.
=> Update release notes

build/studio/README, build/studio/sunstudio12.1.p5m
Remove old date from sunstudio package
=> Remove old date from sunstudio package

build/readline/build.sh, build/readline/local.mog, build/readline/patches-6/readline63-001, build/readline/patches-6/readline63-002, build/readline/patches-6/readline63-003, build/readline/patches-6/readline63-004, build/readline/patches-6/readline63-005, build/readline/patches-6/readline63-006, build/readline/patches-6/readline63-007, build/readline/patches-6/readline63-008, build/readline/patches-6/series, build/readline/patches/readline70-004, build/readline/patches/readline70-005, build/readline/patches/series, doc/packages.md, tools/test
=> Add missing files for readline

lib/functions.sh
Always clean the tree when syncing from local clone
=> Always clean the tree when syncing from local clone

build/glib/build.sh, doc/packages.md
=> glib2: update to 2.58.1

build/ncurses/build.sh, doc/packages.md
Last planned update before the r151028 freeze.
=> ncurses: update to 6.1.20180923

build/gcc-runtime/build-runtime++.sh, build/gcc-runtime/build-runtime.sh, build/gcc-runtime/build-runtimef.sh
Include gcc libatomic.so in gcc-runtime
=> Include gcc libatomic.so in gcc-runtime

build/sqlite3/build.sh, doc/packages.md
=> sqlite3: update to 3.25.2

build/python35/pyopenssl/test
=> Add simple pyopenssl test

build/cpuid/build.sh, doc/packages.md
=> cpuid: update to 1.7.2

build/release/root/etc/release, doc/ReleaseNotes.md
Scheduling this release for w/c 1.10.2018
=> Preparing for r151022bt

build/kayak-kernel/build.sh, build/kayak-kernel/sudo-bits.sh
Use $RELVER for building miniroot
=> Use $RELVER for building miniroot

build/libidn/build.sh, build/net-snmp/build.sh
=> Restore legacy libraries (r151028)

build/buildctl
built package cache pipe can fill up (r151028)
=> built package cache pipe can fill up (r151028)

build/buildctl
built package cache pipe can fill up
=> built package cache pipe can fill up

build/release/root/etc/release, doc/ReleaseNotes.md
Scheduling this release for w/c 8.10.2018
=> Preparing for r151022bu

build/release/root/etc/release, doc/ReleaseNotes.md
Scheduling this release for w/c 8.10.2018
=> Preparing for r151024aw

build/git/build.sh
Strip git binaries, leaving the symbol table
=> Strip git binaries, leaving the symbol table

build/git/build.sh
Strip git binaries, leaving the symbol table (r151028)
=> Strip git binaries, leaving the symbol table (r151028)

build/buildctl
=> Cannot use logcmd with pipe

build/buildctl
Cannot use logcmd with pipe (r151028)
=> Cannot use logcmd with pipe (r151028)

build/gfx-drm/build.sh, build/jeos/illumos-gate.exclude
=> Provide packages for build/gfx-drm to use github.com/illumos/gfx-drm source (r151028)

build/buildctl
Flag expensive and newly started builds in buildctl status
=> Flag expensive and newly started builds in buildctl status

build/bmake/build.sh, doc/packages.md
=> bmake: update to 20180919

build/nghttp2/build.sh, build/nghttp2/testsuite.log, doc/packages.md
=> nghttp2: update to 1.34

doc/ReleaseNotes.md
Resetting release notes ready for r151029 cycle
=> Resetting release notes ready for r151029 cycle

doc/ReleaseNotes.md
The code changes to add this support are in final testing.
=> Add note about new Emulex hardware support (r151028)

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
=> curl: update to 7.62.0

build/curl/build.sh
curl: update to 7.62.0 (r151028)
=> curl: update to 7.62.0 (r151028)

build/curl/build.sh
curl: update to 7.62.0 (r151026)
=> curl: update to 7.62.0 (r151026)

build/curl/build.sh
curl: update to 7.62.0 (r151022)
=> curl: update to 7.62.0 (r151022)

doc/ReleaseNotes.md
Record new qlc 16G FC support (r151028)
=> Record new qlc 16G FC support (r151028)

build/gfx-drm/build.sh
and add package diff after publication.
=> Update gfx-drm to use bundled "bldenv" tool

lib/config.sh
=> Bump personality to r151029

build/entire/build-entire.sh, build/jeos/build-gate.sh, build/jeos/build-userland.sh
Fix missing quote and adjust bail -> logerr
=> Fix missing quote and adjust bail -> logerr

build/ipmitool/patches/openssl11.patch
=> Fix ipmitool openssl patch

build/ipmitool/patches/openssl11.patch
Fix ipmitool openssl patch (r151028)
=> Fix ipmitool openssl patch (r151028)

build/pkg/build.sh, doc/ReleaseNotes.md
Update release notes for pkg5 changes
=> Update release notes for pkg5 changes

build/jeos/build-userland.sh, build/jeos/omnios-userland.pkg, build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151028b (r151028)

build/entire/build-entire.sh, build/jeos/build-gate.sh, build/jeos/build-userland.sh, build/pkg/build.sh, lib/functions.sh
=> Diff more packages

build/buildctl, build/entire/build-entire.sh, build/jeos/build-gate.sh, build/jeos/build-userland.sh, lib/functions.sh
Centralise manifest translation logic; cleanups
=> Centralise manifest translation logic; cleanups

build/buildctl, lib/functions.sh
Use human readable elapsed times
=> Use human readable elapsed times

lib/functions.sh
Improve python site-to-vendor relocation, accommodate python3
=> Improve python site-to-vendor relocation, accommodate python3

build/buildctl
and consolidate job reap behaviour across normal run and draining states.
=> Ensure kayak-kernel is built last

lib/config.sh, lib/functions.sh
Use correct URL for package comparison
=> Use correct URL for package comparison

lib/config.sh
Use correct URL for package comparisons (r151028)
=> Use correct URL for package comparisons (r151028)

build/openssl/build.sh, build/openssl/testsuite.log, doc/packages.md
openssl: update to 1.1.0i/1.0.2p
=> openssl: update to 1.1.0i/1.0.2p

build/openssl/build.sh
openssl: update to 1.1.0i/1.0.2p (r151028)
=> openssl: update to 1.1.0i/1.0.2p (r151028)

build/openssl/build.sh
openssl: update to 1.1.0i/1.0.2p (r151026)
=> openssl: update to 1.1.0i/1.0.2p (r151026)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151028c (r151028)

build/openjdk/patches/hotspot-ccsbins.patch, build/openjdk/patches/jdk-fixes.patch, build/openjdk/patches/series, build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022ca (r151022)

build/git/build.sh, build/git/testsuite.log, doc/packages.md
=> git: update to 2.19.2

build/git/build.sh
git: update to 2.19.2 (r151028)
=> git: update to 2.19.2 (r151028)

build/wget/build.sh, build/wget/patches/hostos.patch, build/wget/patches/series
wget: move to 64-bit, change transmitted OS identification
=> wget: move to 64-bit, change transmitted OS identification

build/libxslt/build.sh
libxslt: drop python bindings
python3 is not currently supported by this software.
=> libxslt: drop python bindings

build/ntpsec/build.sh, build/ntpsec/local.mog, build/ntpsec/testsuite.log
=> ntpsec: switch to python3

build/glib/build.sh, build/glib/local.mog
=> glib: move to python3

build/XML::Parser/build.sh, build/gcc5/build.sh, build/perl/build.sh, build/perl/testsuite.log, build/perl/testsuite64.log, build/pkgtree/build.sh, doc/packages.md, lib/config.sh
Also a restructure to remove the legacy DEPVER and duplication of version numbers.
=> perl: update to 5.28.1

build/perl/build.sh, build/perl/testsuite.log, build/perl/testsuite64.log, lib/config.sh
perl: update to 5.26.3 (r151026)
=> perl: update to 5.26.3 (r151026)

build/perl/build.sh, lib/config.sh
perl: update to 5.28.1 (r151028)
=> perl: update to 5.28.1 (r151028)

build/mozilla-nss-nspr/build.sh, doc/packages.md
=> nss: update to 3.40.1

build/mozilla-nss-nspr/build.sh
nss: update to 3.40.1 (r151028)
=> nss: update to 3.40.1 (r151028)

build/mozilla-nss-nspr/build.sh
nss/nspr: update to 3.40.1/4.20 (r151026)
=> nss/nspr: update to 3.40.1/4.20 (r151026)

build/entire/entire.p5m, build/jeos/omnios-userland.p5m, build/mozilla-nss-nspr/build.sh
nss/nspr: update to 3.40.1/4.20 (r151022)
=> nss/nspr: update to 3.40.1/4.20 (r151022)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151028e (r151028)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022cc (r151022)

build/entire/entire.pkg, doc/baseline
Depends on https://github.com/omniosorg/illumos-omnios/pull/339
=> Add driver/inotify to entire

build/tmux/build.sh, build/tmux/local.mog, lib/functions.sh
Adjust tmux build to use new dependency function
=> Add dependency function, adjust tmux to use it and switch to 64-bit, support multiple source URLs

build/meta/omnios-build-tools.p5m
Add library/pcre2 to omnios-build-tools
=> Add library/pcre2 to omnios-build-tools

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022cd (r151022)

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151028f (r151028)

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
=> curl: update to 7.63.0

build/openssl/local.mog
Fix bad OpenSSL 1.1 include link
=> Fix bad OpenSSL 1.1 include link

build/coreutils/build.sh, build/dbus-glib/build.sh, build/g11n/utf-8-manual.p5m, build/glib/build.sh, build/glib/local.mog, doc/baseline, lib/functions.sh
This is a set of changes to catch up following recent changes, to get back to a clean build state.
=> Changes required to restore clean build

build/libxml2/build.sh
libxml2: update to 2.9.9 (r151026)
=> libxml2: update to 2.9.9 (r151026)

build/libxml2/build.sh
libxml2: update to 2.9.9 (r151028)
=> libxml2: update to 2.9.9 (r151028)

build/release/root/etc/notices/COPYRIGHT, build/release/root/etc/notices/LICENSE, build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022ch (r151022)

build/release/build.sh, build/release/root/etc/notices/COPYRIGHT, build/release/root/etc/notices/LICENSE, doc/ReleaseNotes.md
=> Preparing for r151026aj (r151026)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151028j (r151028)

build/mercurial/build.sh, doc/packages.md
=> mercurial: update to 4.8.2

build/readline/build.sh
Build readline versions in ascending order
=> Build readline versions in ascending order

build/obsolete/developer-acpi-compiler.p5m
Use later version for renamed acpi/compiler
=> Use later version for renamed acpi/compiler

build/ntpsec/build.sh, build/ntpsec/patches/conf.patch, build/ntpsec/patches/mansections.patch, build/ntpsec/patches/nonet.patch, build/ntpsec/patches/pie.patch, build/ntpsec/testsuite.log, doc/packages.md
=> ntpsec: update to 1.1.3

build/openssh/build.sh, build/openssh/patches/scp-name-validator.patch, build/openssh/patches/series
Add scp client CVE mitigations
=> Add scp client CVE mitigations

build/jeos/omnios-userland.pkg, build/openssh/build.sh, build/openssh/patches/scp-name-validator.patch, build/openssh/patches/series, build/openssh/testsuite.log
Add scp client CVE mitigations (r151028)
=> Add scp client CVE mitigations (r151028)

build/openssh/patches/scp-name-validator.patch, build/openssh/patches/series
Add scp client CVE mitigations (r151026)
=> Add scp client CVE mitigations (r151026)

build/openssh/patches/scp-name-validator.patch, build/openssh/patches/series
Add scp client CVE mitigations (r151022)
=> Add scp client CVE mitigations (r151022)

build/sudo/build.sh, build/sudo/local.mog, build/sudo/testsuite.log, doc/packages.md
=> sudo: update to 1.8.27

build/ntpsec/build.sh, build/ntpsec/patches/conf.patch, build/ntpsec/patches/mansections.patch, build/ntpsec/patches/nonet.patch, build/ntpsec/patches/pie.patch, build/ntpsec/testsuite.log
ntpsec: update to 1.1.3 (r151028)
=> ntpsec: update to 1.1.3 (r151028)

build/ntpsec/build.sh, build/ntpsec/patches/conf.patch, build/ntpsec/patches/mansections.patch, build/ntpsec/patches/nonet.patch, build/ntpsec/patches/pie.patch
ntpsec: update to 1.1.3 (r151026)
=> ntpsec: update to 1.1.3 (r151026)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151028l (r151028)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022cj (r151022)

build/nghttp2/build.sh, doc/packages.md
=> nghttp2: update to 1.36.0

build/ncurses/build.sh, doc/packages.md
=> ncurses: update to 20190112

build/mozilla-nss-nspr/build.sh, doc/packages.md
=> nss: update to 3.41.1

build/jeos/omnios-userland.pkg, build/zsh/build.sh, build/zsh/testsuite.log, doc/packages.md
zsh: update to 5.7 (and 64-bit)
=> zsh: update to 5.7 (and 64-bit)

build/bison/build.sh, build/bison/testsuite.log, build/jeos/omnios-userland.pkg, doc/packages.md
=> bison: update to 3.3

build/bison/build.sh, build/bison/testsuite.log, doc/packages.md
=> bison: update to 3.3.1

build/mozilla-nss-nspr/build.sh, doc/packages.md
=> nss: update to 3.42

build/ec2-credential/files/ec2-credential.xml, build/ec2-credential/files/install-ec2-credential
see: https://github.com/omniosorg/omnios-build/issues/1247
=> EC2 credential service needs to try harder

build/mercurial/build.sh, doc/packages.md
=> mercurial: update to 4.9

build/iso-codes/build.sh, doc/packages.md
=> iso-codes: update to 4.2

build/binutils/build.sh, doc/packages.md
=> binutils: update to 2.32

build/bison/build.sh, build/bison/testsuite.log, doc/packages.md
=> bison: update to 3.3.2

build/zsh/build.sh, doc/packages.md, lib/functions.sh
=> zsh: update to 5.7.1

build/curl/build.sh
curl: update to 7.64.0 (r151022)
=> curl: update to 7.64.0 (r151022)

build/curl/build.sh
curl: update to 7.64.0 (r151026)
=> curl: update to 7.64.0 (r151026)

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
=> curl: update to 7.64.0

build/curl/build.sh
curl: update to r151028 (r151028)
=> curl: update to 7.64.0 (r151028)

build/entire/entire.p5m, build/python27/build.sh
Add developer/object-file dependency to python and install by default (r151022)
=> Add developer/object-file dependency to python and install by default (r151022)

build/entire/entire.pkg, build/python27/build.sh
Add developer/object-file dependency to python and install by default (r151026)
=> Add developer/object-file dependency to python and install by default (r151026)

build/entire/entire.pkg, build/python27/build.sh, build/python35/build.sh
Add developer/object-file dependency to python and install by default (r151028)
=> Add developer/object-file dependency to python and install by default (r151028)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151028o (r151028)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022cm (r151022)

build/pkg/build.sh, doc/baseline
=> Add system/zones/brand/pkgsrc

build/ncurses/patches/sun-color.patch
ncurses: sun-color now supports 256 colours
=> ncurses: sun-color now supports 256 colours

build/gcc44/build.sh, build/gcc5/build.sh, build/gcc7/build.sh, build/gcc8/build.sh, build/meta/illumos-tools.p5m, doc/baseline
Adjust for obsolete lint library
=> Adjust for obsolete lint library

build/illumos-kvm/build.sh
Adjust kvm build for new CTF tools in gate
=> Adjust kvm build for new CTF tools in gate

build/git/build.sh, build/git/testsuite.log, doc/packages.md
=> git: update to 2.21.0

build/kayak/build.sh
Fixes https://github.com/omniosorg/kayak/issues/98
=> Add cherrypy-35 dependency for kayak package

build/gcc44/build.sh, build/gcc5/build.sh, build/gcc7/build.sh, build/gcc8/build.sh
=> Compiler packages require library/c-runtime

build/sqlite3/build.sh, doc/packages.md
=> sqlite3: update to 3.27.2

build/openssl/build.sh, build/openssl/testsuite.log, doc/packages.md
openssl: update to 1.1.1b/1.0.2q
=> openssl: update to 1.1.1b/1.0.2q

build/openssl/build.sh
openssl: update to 1.0.2r (r151026)
=> openssl: update to 1.0.2r (r151026)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022co (r151022)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151028q (r151028)

build/openssl/build.sh
openssl: update to 1.0.2r (r151022)
=> openssl: update to 1.0.2r (r151022)

doc/ReleaseNotes.md
Interim draft release notes updates
=> Interim draft release notes updates

build/openssl/build.sh, build/openssl/local.mog, build/openssl/preview/build.sh
openssl: update to 1.0.2r/1.1.1b (r151028)
=> openssl: update to 1.0.2r/1.1.1b (r151028)

build/openjdk/patches/patch-common_autoconf_generated-configure.sh.patch
Tested a full illumos-omnios build with this changes and it was successful.
=> Fix openjdk build library dependencies

build/jeos/omnios-userland.pkg, build/mdata-client/build.sh
mdata-client: update to 20190228
=> mdata-client: update to 20190228

build/python27/build.sh
python2: update to 2.7.16 (r151022)
=> python2: update to 2.7.16 (r151022)

build/python27/build.sh
python2: update to 2.7.16 (r151026)
=> python2: update to 2.7.16 (r151026)

doc/ReleaseNotes.md
=> Release notes update

build/kayak/build.sh
Add cherrypy-35 dependency for kayak package (r151028)
=> Add cherrypy-35 dependency for kayak package (r151028)

build/ntp/build.sh, doc/packages.md
=> ntp: update to 4.2.8p13

build/ntp/build.sh
ntp: update to 4.2.8p13 (r151028)
=> ntp: update to 4.2.8p13 (r151028)

build/ntp/build.sh
ntp: update to 4.2.8p13 (r151026)
=> ntp: update to 4.2.8p13 (r151026)

build/ntp/build.sh
ntp: update to 4.2.8p13 (r151022)
=> ntp: update to 4.2.8p13 (r151022)

build/entire/entire.pkg, doc/baseline
=> Add hyperv driver

build/python35/meson/build.sh, build/python35/meson/local.mog, build/python35/meson/patches/illumos_gcc.patch, doc/packages.md
=> meson: update to 0.50.0

build/ntp/patches/const.patch, build/ntp/patches/series
ntp: fix build error (r151022)
=> ntp: fix build error (r151022)

build/ntp/patches/const.patch, build/ntp/patches/series
ntp: fix build error (r151026)
=> ntp: fix build error (r151026)

build/entire/entire.pkg
Make hyperv an optional package
=> Make hyperv an optional package

build/libedit/build.sh, doc/packages.md
libedit: update to 20190324-3.1
=> libedit: update to 20190324-3.1

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
=> curl: update to 7.64.1

build/illumos-kvm/build.sh
kvm build needs to pass PRIMARY_COMPILER_VER
=> kvm build needs to pass PRIMARY_COMPILER_VER

build/entire/build-entire.sh, build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151028u (r151028)

build/python27/build.sh
Build python2 under python2 environment
=> Build python2 under python2 environment

build/obsolete/developer-java-jdk.p5m, build/obsolete/runtime-java.p5m
Fix obsolete java package version
=> Fix obsolete java package version

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022ct (r151022)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151028v (r151028)

build/openjdk8/jdk.mog, build/openjdk8/jre.mog
Fix openjdk CA cert links (r151030)
=> Fix openjdk CA cert links (r151030)

build/openjdk8/jdk.mog, build/openjdk8/jre.mog
=> Fix openjdk CA cert links

doc/baseline
=> Update baseline (r151030)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022cx (r151022)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151028z (r151028)

build/jeos/omnios-userland.pkg, build/tmux/build.sh, doc/packages.md, tools/test
=> tmux: update to 2.9

doc/ReleaseNotes.md
Update release notes ready for r151030 (r151030)
=> Update release notes ready for r151030 (r151030)

lib/config.sh
=> Time for r151031

doc/ReleaseNotes.md
Clear release notes for r151031
=> Clear release notes for r151031

build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch, build/openssh/patches/series
openssh: restore TCP wrappers support
=> openssh: restore TCP wrappers support

build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch, build/openssh/patches/series
openssh: restore TCP wrappers support (r151030)
=> openssh: restore TCP wrappers support (r151030)

build/illumos/build.sh
Skip ooce packages for illumos ctf (r151030)
=> Skip ooce packages for illumos ctf (r151030)

build/illumos/build.sh
Skip ooce packages for illumos ctf
=> Skip ooce packages for illumos ctf

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030c (r151030)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022da (r151022)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151028ac (r151028)

build/curl/build.sh
see: https://github.com/omniosorg/omnios-build/pull/1413
=> curl: update to 7.65.0 (r151022)

build/curl/build.sh
see: https://github.com/omniosorg/omnios-build/pull/1413
=> curl: update to 7.65.0 (r151028)

build/curl/build.sh
see: https://github.com/omniosorg/omnios-build/pull/1413
=> curl: update to 7.65.0 (r151030)

build/openssl/build.sh, build/openssl/testsuite.log, doc/packages.md
openssl: update to 1.1.1c/1.0.2s
=> openssl: update to 1.1.1c/1.0.2s

build/openssl/build.sh
openssl: update to 1.1.1c/1.0.2s (r151030)
=> openssl: update to 1.1.1c/1.0.2s (r151030)

build/openssl/build.sh
openssl: update to 1.1.0k/1.0.2s (r151028)
=> openssl: update to 1.1.0k/1.0.2s (r151028)

build/openssl/build.sh
openssl: update to 1.0.2s (r151022)
=> openssl: update to 1.0.2s (r151022)

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for 151030e

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for 151028ae

build/release/root/etc/release, doc/ReleaseNotes.md
=> preparing for r151022dc

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
=> curl: update to 7.65.1

build/curl/build.sh
curl: update to 7.65.1 (r151030)
=> curl: update to 7.65.1 (r151030)

build/curl/build.sh
curl: update to 7.65.1 (r151028)
=> curl: update to 7.65.1 (r151028)

build/curl/build.sh
curl: update to 7.65.1 (r151022)
=> curl: update to 7.65.1 (r151022)

build/azure/build.sh, build/azure/local.mog, build/jeos/omnios-userland.pkg
Add Azure Guest Agent (r151030)
=> Add Azure Guest Agent (r151030)

build/mercurial/build.sh, doc/packages.md
=> hg: update to 5.0.1

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030f (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151028af (r151028)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022dd (r151022)

build/gcc7/build.sh, build/gcc7/patches/0002-compare_tests-Use-nawk-1-on-illumos-since-awk-1-is-o.patch, build/gcc7/patches/0003-gcc-enable-the-.eh_frame-based-unwinder.patch, build/gcc7/patches/0004-intl-Don-t-use-UTF-8-quotes.-Ever.patch, build/gcc7/patches/0005-Implement-fstrict-calling-conventions.patch, build/gcc7/patches/0006-allow-the-global-disabling-of-function-cloning.patch, build/gcc7/patches/0007-strict-cc2-check-that-disabling-function-cloning-pre.patch, build/gcc7/patches/0008-sol2-enable-full-__cxa_atexit-support.patch, build/gcc7/patches/0009-sol2-Use-appropriate-values-objects-for-the-various-.patch, build/gcc7/patches/0010-i386-Save-integer-passed-arguments-to-the-stack-to-a.patch, build/gcc7/patches/0011-16-update-cmn_err-format-specifier.patch, build/gcc7/patches/0012-19-cmn_err-b-conversion-should-accept-0-flag.patch, build/gcc7/patches/0013-We-never-want-to-omit-the-frame-pointer-regardless-o.patch, build/gcc7/patches/0014-libstdc-v3-illumos-and-Solaris-haven-t-needed-lrt-in.patch, build/gcc7/patches/0015-libgo-libelf-on-illumos-doesn-t-support-largefile.patch, build/gcc7/patches/0016-libgcc-unwind.map-should-be-v2-style.patch, build/gcc7/patches/0017-libpthread-is-a-filter-in-illumos-all-functionality-.patch, build/gcc7/patches/0018-i386-Fix-grammar-of-msave-args-usage-message.patch, build/gcc7/patches/0019-OOCE-Adjust-default-library-paths-for-OmniOS.patch, build/gcc7/patches/0020-tests-x86_64-pro_and_epilogue-RTL-can-t-work-with-ms.patch, build/gcc7/patches/0021-i386-don-t-assert-the-FP-is-valid-during-epilogue-ad.patch, build/gcc7/patches/0022-gcc.target-i386-retarg-skip-if-msave-args.patch, build/gcc7/patches/0023-i386-use-correct-error-message-about-msave-args-and-.patch, build/gcc7/patches/0024-gcc.target-i386-skip-16bit-tests-when-msave-args.patch, build/gcc7/patches/series
gcc7: Update patches to upstream illumos gcc-7.4.0 branch
=> gcc7: Update patches to upstream illumos gcc-7.4.0 branch

build/expat/local.mog, build/expat/patches/security-186.patch, build/expat/patches/series
expat: Fix security bug (r151022)
=> expat: Fix security bug (r151022)

build/azure/build.sh, doc/packages.md
=> azure agent: update to 2.2.41

build/azure/build.sh
azure agent: update to 2.2.41 (r151030)
=> azure agent: update to 2.2.41 (r151030)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022df (r151022)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151028ah (r151028)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030h (r151030)

build/ntpsec/build.sh, build/ntpsec/testsuite.log, doc/packages.md
=> ntpsec: update to 1.1.5

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030j (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151028aj (r151028)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022dh (r151022)

build/glib/build.sh, build/glib/testsuite.log
Fix glib testsuite.log creation
=> Fix glib testsuite.log creation

build/iso-codes/build.sh, build/ntpsec/build.sh, doc/packages.md
=> iso-codes: update to 4.3

build/ca-bundle/build.sh
=> Tweak ca-bundle description

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
=> curl: update to 7.65.2

build/ipmitool/build.sh, build/ipmitool/patches/POSIX.patch, build/ipmitool/patches/series
Use POSIX+EXTENSIONS instead of removing POSIX definitions
=> Use POSIX+EXTENSIONS instead of removing POSIX definitions

build/release/root/etc/release, doc/ReleaseNotes.md
=> preparing for r151022dj

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151028al

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151030l

build/coreutils/patches/ln-port-to-platforms-lacking-O_DIRECTORY.patch, build/coreutils/patches/ln-s-catch-EINVAL.patch, build/coreutils/patches/series
=> coreutils: fix bugs in GNU ln (r151030)

build/glib/build.sh, doc/packages.md
=> glib: update to 2.60.6

build/libgmp/build.sh
libgmp: fix variable to limit use of CPU features (r151030)
=> libgmp: fix variable to limit use of CPU features (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030m (r151030)

build/zsh/local.mog
Preserve local /etc/zshrc changes
=> Preserve local /etc/zshrc changes

build/bash/build.sh, build/bash/patches/README, build/bash/patches/bash-5.0-patches/bash50-001, build/bash/patches/bash-5.0-patches/bash50-002, build/bash/patches/bash-5.0-patches/bash50-003, build/bash/patches/bash-5.0-patches/bash50-004, build/bash/patches/bash-5.0-patches/bash50-005, build/bash/patches/bash-5.0-patches/bash50-006, build/bash/patches/bash-5.0-patches/bash50-007, build/bash/patches/bash-5.0-patches/bash50-008, build/bash/patches/bash-5.0-patches/bash50-009, build/bash/patches/fetch-patches, build/bash/patches/series
Import latest bash patches (r151030)
=> Import latest bash patches (r151030)

build/entire/entire.pkg, build/jeos/omnios-userland.pkg, build/less/build.sh, doc/packages.md
=> less: update to 551

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030q (r151030)

build/ntpsec/build.sh, build/ntpsec/patches/conf.patch, build/ntpsec/patches/mansections.patch, doc/packages.md
=> ntpsec: update to 1.1.7

build/mozilla-nss-nspr/build.sh
nss: udpate to 3.46; nspr: update to 4.22 (r151028)
=> nss: udpate to 3.46; nspr: update to 4.22 (r151028)

build/entire/entire.p5m, build/jeos/omnios-userland.p5m, build/mozilla-nss-nspr/build.sh
nss: udpate to 3.46; nspr: update to 4.22 (r151022)
=> nss: udpate to 3.46; nspr: update to 4.22 (r151022)

build/entire/entire.pkg, build/jeos/omnios-userland.pkg, build/urxvt/build.sh, build/urxvt/local.mog, doc/baseline
Add rxvt-unicode terminfo to ncurses (r151030)
=> Add rxvt-unicode terminfo to ncurses (r151030)

build/entire/entire.pkg, build/jeos/omnios-userland.pkg, build/urxvt/build.sh, build/urxvt/local.mog, doc/baseline, doc/packages.md
=> Add rxvt-unicode terminfo to ncurses

build/urxvt/build.sh
=> urxvt - missed some logcmds

build/openssl/build.sh, doc/packages.md
openssl: update to 1.1.1d/1.0.2t
=> openssl: update to 1.1.1d/1.0.2t

build/openssl/build.sh
openssl: update to 1.0.2t (r151022)
=> openssl: update to 1.0.2t (r151022)

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
=> curl: update to 7.66.0

build/curl/build.sh
curl: update to 7.66.0 (r151028)
=> curl: update to 7.66.0 (r151028)

build/curl/build.sh
curl: update to 7.66.0 (r151022)
=> curl: update to 7.66.0 (r151022)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030s (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151028as (r151028)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022dq (r151022)

build/gfx-drm/build.sh, build/illumos-kvm/build.sh, lib/functions.sh, lib/global-transforms.mog
Create build version file for illumos-kvm
=> Create build version files for illumos-kvm and gfx-drm

build/expat/build.sh, doc/packages.md
=> expat: update to 2.2.8

build/expat/build.sh
expat: update to 2.2.8 (r151030)
=> expat: update to 2.2.8 (r151030)

build/expat/build.sh
expat: update to 2.2.8 (r151028)
=> expat: update to 2.2.8 (r151028)

build/expat/patches/CVE-2019-15903.patch, build/expat/patches/series
expat: Add patch for CVE-2019-15903 (r151022)
=> expat: Add patch for CVE-2019-15903 (r151022)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030u (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151028au (r151028)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022ds (r151022)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030v (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151028av (r151028)

build/entire/entire.pkg, build/jeos/omnios-userland.pkg, build/screen/build.sh, doc/packages.md
=> screen: update to 4.7.0

build/glib/build.sh, build/glib/patches/gobject.h.patch, build/glib/patches/libsocket.patch, build/glib/patches/no_export_dynamic.patch, build/glib/patches/no_inotify.patch, build/glib/testsuite.log, build/iso-codes/build.sh, build/jeos/omnios-userland.pkg, build/python35/asn1crypto/build.sh, build/python35/cherrypy/build.sh, build/sqlite3/build.sh, doc/packages.md
`pkg` test suite matches baseline
=> package update

build/sudo/build.sh, build/sudo/testsuite.log, doc/packages.md
=> sudo: update to 1.8.28

build/sudo/build.sh
sudo: update to 1.8.28 (r151032)
=> sudo: update to 1.8.28 (r151032)

build/sudo/build.sh
sudo: update to 1.8.28 (r151030)
=> sudo: update to 1.8.28 (r151030)

build/sudo/build.sh
sudo: update to 1.8.28 (r151028)
=> sudo: update to 1.8.28 (r151028)

build/sudo/patches/CVE-2019-14287.patch, build/sudo/patches/series
sudo: add patch for CVE-2019-14287 (r151022)
=> sudo: add patch for CVE-2019-14287 (r151022)

build/sudo/build.sh
sudo: update to 1.8.28p1 (r151028)
=> sudo: update to 1.8.28p1 (r151028)

build/python37/build.sh, build/python37/patches/00-dtrace.patch, build/python37/patches/07-closerange.patch, build/python37/patches/08-py_db.patch, build/python37/patches/13-SOABI.patch, build/python37/patches/20-test_fixes.patch, build/python37/patches/25-sparc-pgo.patch, build/python37/testsuite-d.log, build/python37/testsuite.log, doc/packages.md
=> Python: update to 3.7.5

build/mozilla-nss-nspr/build.sh, doc/packages.md
=> nss/nspr: update to 3.47/4.23

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022dw (r151022)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151028ay (r151028)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030y (r151030)

doc/packages.md
=> python: update to 3.5.8

build/python35/build.sh
python: update to 3.5.8 (r151030)
=> python: update to 3.5.8 (r151030)

build/python27/build.sh
python: update to 2.7.17 (r151032)
=> python: update to 2.7.17 (r151032)

build/python27/build.sh
python: update to 2.7.17 (r151030)
=> python: update to 2.7.17 (r151030)

build/python27/build.sh
Python: update to 2.7.17 (r151022)
=> Python: update to 2.7.17 (r151022)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022dx (r151022)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030z (r151030)

doc/ReleaseNotes.md
Final proposed release notes for r151032 (will be released tomorrow).
Please review!
=> Update r151032 release notes (r151032)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030ab (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032b (r151032)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032e (r151032)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030ae (r151030)

build/azure/build.sh, build/azure/patches/0001-Initial-drop-of-generic-illumos-support.-Ported-from.patch, build/azure/patches/0002-Simplify-hostname-setting.patch, build/azure/patches/0003-Explicitly-use-python3.patch, build/azure/patches/0004-Add-dependency-on-rmvolmgr-service.patch, build/azure/patches/0005-Relocate-files-to-usr-lib-hyperv.patch, build/azure/patches/0006-Use-etc-system.d-over-etc-system.patch, build/azure/patches/0007-Reduce-SCSI-IO-timeout-to-match-OmniOS-defaults.patch, build/azure/patches/0008-Disable-verbose-logs-by-default.patch, build/azure/patches/0009-Clear-IPS-UUIDs-on-de-provision.patch, build/azure/patches/0010-Pattern-for-sd_io_time-needs-relaxing.patch, build/azure/patches/0011-Fix-check-for-existing-IO-timeout-remove-log-message.patch, build/azure/patches/0012-Add-empty-read_route_table-to-stop-errors-about-proc.patch, build/azure/patches/series, doc/packages.md
~~This still needs testing in an azure environment.~~
Tested deployment of a new VM in Azure.
=> azure-agent: update to 2.2.45

build/openssl/build.sh
openssl: update to 1.0.2u (r151032)
=> openssl: update to 1.0.2u (r151032)

build/openssl/build.sh, doc/packages.md
=> openssl: update to 1.0.2u

build/openssl/build.sh, build/release/root/etc/release, doc/ReleaseNotes.md
openssl: update to 1.0.2u (r151022)
=> openssl: update to 1.0.2u (r151022)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022ef (r151022)

build/openssl/build.sh
openssl: update to 1.0.2u (r151030)
=> openssl: update to 1.0.2u (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032h (r151032)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030ah (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032l (r151032)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030al (r151030)

build/azure/build.sh, build/isc-dhcp/build.sh, build/pciutils/build.sh, build/pciutils/local.mog, doc/packages.md
=> Package updates (isc-dhcp/pciutils/azure-agent)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030ap (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032p (r151032)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022en (r151022)

build/jeos/omnios-userland.pkg, build/zsh/build.sh, build/zsh/patches/no-posix.patch, build/zsh/patches/series, build/zsh/patches/shared.patch, build/zsh/patches/testsuite.patch, doc/packages.md
=> zsh: update to 5.8

build/jeos/omnios-userland.pkg, build/python37/rapidjson/build.sh, build/python37/rapidjson/local.mog, build/python37/rapidjson/test, doc/baseline, doc/packages.md
=> Add python3 rapidjson module

build/entire/entire.pkg, build/openssh/build.sh, build/openssh/patches/0001-Skip-config-check.patch, build/openssh/patches/0002-PAM-Support.patch, build/openssh/patches/0003-lastlogin.patch, build/openssh/patches/0004-Reorganise-man-pages-into-illumos-numbering-adjust-t.patch, build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch, build/openssh/patches/0007-DTrace-support-for-SFTP.patch, build/openssh/patches/0008-Add-DisableBanner-option.patch, build/openssh/patches/0009-PAM-conversation-fix.patch, build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch, build/openssh/patches/0013-Solaris-Auditing-support.patch, build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch, build/openssh/patches/0016-PAM-setcred-failures.patch, build/openssh/patches/0018-Per-session-xauthfile.patch, build/openssh/patches/0019-PubKeyPlugin-support.patch, build/openssh/patches/0021-Try-to-create-privsep-chroot-dir-if-it-doesn-t-exist.patch, build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch, build/openssh/patches/0027-Set-default-sshd-options-based-on-etc-default-login.patch, build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch, build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch, build/openssh/patches/gssapi.patch, build/openssh/patches/revert-dscp.patch, build/openssh/server.mog, build/openssh/testsuite.log, doc/packages.md
=> openssh: update to 8.2p1

doc/ReleaseNotes.md
Starter for 10, it's quite likely I've missed something in this initial pass.
@danmcd - can you please look at the NFS zone bit in particular - is there anywhere that would be worth linking to from here?
=> Draft release notes for r151034

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030av (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032v (r151032)

build/ncurses/patches/drop-rin-from-screen-256color.diff, build/ncurses/patches/extra-newline.patch, build/ncurses/patches/series, build/ncurses/patches/sun-color.patch, build/ncurses/patches/xterm-no-rep.patch
See https://github.com/joyent/pkgsrc/issues/248
=> ncurses: Remove "rin" from screen-256color (r151034)

build/ncurses/patches/drop-rin-from-screen-256color.diff, build/ncurses/patches/extra-newline.patch, build/ncurses/patches/series, build/ncurses/patches/sun-color.patch, build/ncurses/patches/xterm-no-rep.patch
See https://github.com/joyent/pkgsrc/issues/248
=> ncurses: Remove "rin" from screen-256color

build/openssl/build.sh
openssl: update to 1.1.1f (r151030)
=> openssl: update to 1.1.1f (r151030)

build/openssl/build.sh
openssl: update to 1.1.1.f (r151032)
=> openssl: update to 1.1.1f (r151032)

build/openssl/build.sh, doc/packages.md
=> openssl: update to 1.1.1f

build/openssl/build.sh
openssl: update to 1.1.1.f (r151034)
=> openssl: update to 1.1.1f (r151034)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030aw (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032w (r151032)

tools/idlist
```
% ./tools/idlist
group 92 sshd
user 18 dhcpserv
user 26 dma
user 92 sshd
```
=> Add tools/idlist

build/entire/entire.pkg, build/jeos/omnios-userland.pkg, build/watch/build.sh, build/watch/local.mog, doc/baseline, doc/packages.md
=> Adding GNU watch

build/openssl/build.sh, build/openssl/testsuite.log, build/python27/build.sh, build/python27/patches/disable_epoll.patch, build/python27/patches/series, build/python27/testsuite-32.log, build/python27/testsuite.log, build/python35/patches/disable_epoll.patch, build/python35/patches/series, build/python35/testsuite-d.log, build/python35/testsuite.log
openssl: update to 1.1.1g (r151030)
=> openssl: update to 1.1.1g (r151030)

build/openssl/build.sh, build/openssl/testsuite.log, build/python27/build.sh, build/python27/patches/disable_epoll.patch, build/python27/patches/series, build/python27/testsuite-32.log, build/python27/testsuite.log, build/python37/patches/disable_epoll.patch, build/python37/patches/series, build/python37/testsuite-d.log, build/python37/testsuite.log
openssl: update to 1.1.1g (r151032)
=> openssl: update to 1.1.1g (r151032)

build/openssl/build.sh, build/openssl/testsuite.log, build/python27/build.sh, build/python27/patches/disable_epoll.patch, build/python27/patches/series, build/python27/testsuite-32.log, build/python27/testsuite.log, build/python37/patches/disable_epoll.patch, build/python37/patches/series, build/python37/testsuite-d.log, build/python37/testsuite.log
openssl: update to 1.1.1g (r151034)
=> openssl: update to 1.1.1g (r151034)

build/git/build.sh, doc/packages.md
=> git: update to 2.26.2

build/git/build.sh, build/jeos/omnios-userland.p5m
git: update to 2.17.5 (r151022)
=> git: update to 2.17.5 (r151022)

build/git/build.sh
git: update to 2.21.3 (r151030)
=> git: update to 2.21.3 (r151030)

build/git/build.sh
git: update to 2.23.3 (r151032)
=> git: update to 2.23.3 (r151032)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032z (r151032)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030az (r151030)

build/release/root/etc/release, doc/ReleaseNotes.md
=> Preparing for r151022ey (r151022)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032ab (r151032)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030bb (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151034d (r151034)

build/entire/entire.pkg, build/openssh/build.sh, build/openssh/files/sshd, build/openssh/patches/0001-Skip-config-check.patch, build/openssh/patches/0002-PAM-Support.patch, build/openssh/patches/0003-lastlogin.patch, build/openssh/patches/0004-Reorganise-man-pages-into-illumos-numbering-adjust-t.patch, build/openssh/patches/0006-GSS-store-creds-for-Solaris.patch, build/openssh/patches/0007-DTrace-support-for-SFTP.patch, build/openssh/patches/0008-Add-DisableBanner-option.patch, build/openssh/patches/0010-PAM-enhancements-for-Solaris.patch, build/openssh/patches/0013-Solaris-Auditing-support.patch, build/openssh/patches/0015-Enable-login-to-a-role-if-PAM-is-ok-with-it.patch, build/openssh/patches/0019-PubKeyPlugin-support.patch, build/openssh/patches/0021-Try-to-create-privsep-chroot-dir-if-it-doesn-t-exist.patch, build/openssh/patches/0026-Don-t-use-krb5-config-to-check-for-GSSAPI-on-illumos.patch, build/openssh/patches/0027-Set-default-sshd-options-based-on-etc-default-login.patch, build/openssh/patches/0029-Accept-LANG-and-LC_-environment-variables-from-clien.patch, build/openssh/patches/0031-Restore-tcpwrappers-libwrap-support.patch, build/openssh/patches/gssapi.patch, build/openssh/patches/revert-dscp.patch, build/openssh/patches/ssh-copy-id.patch, build/openssh/testsuite.log, doc/packages.md
=> openssh: update to 8.3p1

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151030be (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151032ae (r151032)

build/release/build.sh, doc/ReleaseNotes.md
=> Preparing for r151034e (r151034)

build/git/build.sh, build/git/testsuite.log, doc/packages.md
=> git: update to 2.27.0

build/nghttp2/build.sh
nghttp2: update to 1.41.0 (r151030)
=> nghttp2: update to 1.41.0 (r151030)

build/nghttp2/build.sh
nghttp2: update to 1.41.0 (r151034)
=> nghttp2: update to 1.41.0 (r151034)

build/nghttp2/build.sh, build/nghttp2/testsuite.log, doc/packages.md
=> nghttp2: update to 1.41.0

build/dbus/build.sh, build/dbus/patches/inline.patch, build/dbus/patches/msg_ctrunc.patch, build/dbus/patches/series, build/dbus/testsuite.log, doc/packages.md
=> dbus: update to 1.12.18

build/bison/build.sh, build/bison/testsuite.log, doc/packages.md
=> bison: update to 3.6.3

build/mercurial/build.sh, doc/packages.md
=> mercurial: update to 5.4.1

build/jeos/omnios-userland.pkg, build/open-vm-tools/build.sh, build/open-vm-tools/patches/gnu-ld.patch, build/open-vm-tools/patches/lock.patch, build/open-vm-tools/patches/nicInfo.patch
fixes https://github.com/omniosorg/omnios-build/issues/1901
=> open-vm-tools: update to 11.1.0 (r151030)

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151030bf

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151032af

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151034f

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151032ag

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151034g

build/release/build.sh, doc/ReleaseNotes.md
=> preparing for r151030bg

build/readline/build.sh, build/readline/patches-6/link-ltermcap.patch, build/readline/patches-6/series, build/readline/patches-7/link-ltermcap.patch, build/readline/patches-7/series, build/readline/patches/README, build/readline/patches/link-ltermcap.patch, build/readline/patches/readline80-001, build/readline/patches/readline80-002, build/readline/patches/readline80-003, build/readline/patches/readline80-004, build/readline/patches/series
readline: add patches + fix linkage (r151034)
=> readline: add patches + fix linkage (r151034)

build/readline/build.sh, build/readline/patches-6/link-ltermcap.patch, build/readline/patches-6/series, build/readline/patches-7/link-ltermcap.patch, build/readline/patches-7/series, build/readline/patches/README, build/readline/patches/link-ltermcap.patch, build/readline/patches/readline80-001, build/readline/patches/readline80-002, build/readline/patches/readline80-003, build/readline/patches/readline80-004, build/readline/patches/series
readline: add patches + fix linkage (r151032)
=> readline: add patches + fix linkage (r151032)

build/readline/build.sh, build/readline/patches-6/link-ltermcap.patch, build/readline/patches-6/series, build/readline/patches-7/link-ltermcap.patch, build/readline/patches-7/series, build/readline/patches/README, build/readline/patches/link-ltermcap.patch, build/readline/patches/readline80-001, build/readline/patches/readline80-002, build/readline/patches/readline80-003, build/readline/patches/readline80-004, build/readline/patches/series
readline: add patches + fix linkage (r151030)
=> readline: add patches + fix linkage (r151030)

build/curl/build.sh, build/curl/testsuite.log, doc/packages.md
=> curl: update to 7.71.0

build/curl/patches/CVE-2020-8169.patch, build/curl/patches/CVE-2020-8177.patch, build/curl/patches/series
curl: fixes for CVE-2020-{8169,9177} (r151034)
=> curl: fixes for CVE-2020-{8169,9177} (r151034)

build/curl/patches/CVE-2020-8169.patch, build/curl/patches/CVE-2020-8177.patch, build/curl/patches/series
curl: fixes for CVE-2020-{8169,9177} (r151032)
=> curl: fixes for CVE-2020-{8169,9177} (r151032)

build/curl/patches/CVE-2020-8169.patch, build/curl/patches/CVE-2020-8177.patch, build/curl/patches/series
curl: fixes for CVE-2020-{8169,9177} (r151030)
=> curl: fixes for CVE-2020-{8169,9177} (r151030)
